### ISSUE TITLE
GCDAsyncUdpSocket sending data with timeout not work

### ISSUE THREAD

**Issue by jerryGu** [robbiehanson/CocoaAsyncSocket#104]
hi,
 when I use method "- (void)sendData:(NSData *)data toHost:(NSString *)host port:(uint16_t)port  withTimeout (NSTimeInterval)timeout tag:(long)tag", I set timeout to 5,but no matter how long passed, I didn't receive any feedback informing me timeout. how can I use 'Timeout' ?

ps: regularly, if I don't think about the timeout, just set it with -1, it works pretty good. any mistakes ?

 thanks.

**Comment by eightx2** [comment]
I have the same problem. If this is never going to be fixed, what's the best way to check if a response was *not* received within a given time frame?

**Comment by zxl777** [comment]
+1,I'm facing the same problem.

**Comment by vancentvan** [comment]
Never worked for me, either. Are there any requirements for this function calling? Any piece of help is greatly appreciated.
