### ISSUE TITLE
Cannot read responses from server

### ISSUE THREAD

**Issue by 88fsantos** [robbiehanson/CocoaAsyncSocket#108]
Hi!

I implemented of GCDAsyncSocket, but I'not receiving any responses from the server. Any ideia?
- (void) initNetworkCommunication {
  socket = [[GCDAsyncSocket alloc] initWithDelegate:self delegateQueue:dispatch_get_main_queue()];
  NSError *err = nil;
  if (![socket connectToHost:@"54.246.xxx.xxx" onPort:xxxx error:&err]) // Asynchronous!
  {
          // If there was an error, it's likely something like "already connected" or "no delegate set"
      NSLog(@"I goofed: %@", err);
  }
  
  [socket readDataToData:[GCDAsyncSocket CRLFData] withTimeout:-1.0 tag:0];

}
- (void)socket:(GCDAsyncSocket *)sender didConnectToHost:(NSString *)host port:(UInt16)port
  {
  NSLog(@"Cool, I'm connected! That was easy.");
  [[NSNotificationCenter defaultCenter]
   postNotificationName:@"beginSyncronization"
   object:nil];
  }
- (void) sendMessage:(NSDictionary *)message {
  contactDictionary=[[NSMutableDictionary alloc]init];
  contactDictionary=[message copy];
  
  (some code for dictionary here)
  
  ```
    //DICIONARY TO SEND
  ```
  
    NSDictionary _dic=[[NSDictionary alloc]initWithObjectsAndKeys:userId,@"token",@"add",@"action",simpleContactList,@"data",@"contact",@"element", nil];
    NSString_dicString=[dic JSONRepresentation];
    NSLog(@"send message: %@",dic);
    dicString = [dicString stringByAppendingFormat:@"\r\n"];
  
    NSData *data = [[NSData alloc] initWithData:[dicString dataUsingEncoding:NSASCIIStringEncoding]];
        //uint32_t length = (uint32_t)htonl([data length]);
        //[outputStream write:[data bytes] maxLength:[data length]];
  
    [socket writeData:data withTimeout:-1 tag:10];

}
- (void)onSocket:(GCDAsyncSocket *)sock didReadData:(NSData *)data withTag:(long)tag
  {
  NSLog(@"recebeu resposta");
  NSData *strData = [data subdataWithRange:NSMakeRange(0, [data length])];
  NSString *msg = [[NSString alloc] initWithData:strData encoding:NSUTF8StringEncoding];
  if(msg)
  {
      NSLog(@"RX:%@",msg);
  }
  }

The server is fine. I send the dictionary for telnet and it gives me responses. But on ios I can't receive the responses. I'm hable to connect, The dic reaches the server, but I don't receive any response after it. Any idea?

**Comment by fukemy** [comment]
Hi. Could u explain why the message need to end with \r\n? Thanks you
