### ISSUE TITLE
Set property for StreamSetProperty kCFStreamPropertySOCKSProxy fails

### ISSUE THREAD

**Issue by davidchiles** [robbiehanson/CocoaAsyncSocket#122]
I'm attempting to modify CocoaAsyncSocket and specifically GCDAsyncSocket to allow for a SOCKS proxy.

When the readStream and writeStream are created in -(BOOL)createReadAndWriteStream I attempt to [set the property kCFStreamPropertySOCKSProxy](https://github.com/ChatSecure/CocoaAsyncSocket/blob/master/GCD/GCDAsyncSocket.m#L7004). The result for both is always NO. 

Any ideas why it will not recognize or accept this property value?

**Comment by chrisballinger** [comment]
@davidchiles Really would like to try again on this for 7.5.

Looks like this guy was able to make it partially work: http://stackoverflow.com/questions/20388193/adding-socks-proxy-support-in-cocoaasyncsocket

**Comment by WillyWu0201** [comment]
@chrisballinger
Do you have any idea how to add HTTP proxy support in GCDAsyncSocket?
