### ISSUE TITLE
socketDidDisconnect  not to be call on iOS6

### ISSUE THREAD

**Issue by momor** [robbiehanson/CocoaAsyncSocket#131]
It always be called on  iOS5,but when I test it on iOS6 ,it doesn't work.
I tried connect to a TCP sever using GCDAsyncSocket,when I stop sharing Internet over WIFI,I found CFReadStreamCallback and CFWriteStreamCallback not to be call.There is not any error event.

**Comment by gresrun** [comment]
@robbiehanson Any love for this bug? I believe we're experiencing this in low WiFi signal environments.

**Comment by buffpojken** [comment]
@gresrun I believe we are too. 

We're seeing very odd behaviour (using GDAsyncSocket for communication over STOMP), and in some conditions (i.e. when wifi signal is dropping below a yet undetermined threshold), the socket is properly closed (as determined by the server) - but the delegate is never informed that the socket has been closed, and thus can not trigger a reconnect or similar.
