### ISSUE TITLE
No time to live support (TTL)

### ISSUE THREAD

**Issue by vincentjames501** [robbiehanson/CocoaAsyncSocket#137]
It would be nice to add api level support for setting the time to live value on the multicast socket for GCDAsyncUdpSocket.  The code below is the hacked way of adding the feature inside the createSocket4 method.

```
    unsigned char ttl = 7;  //where 7 is the user specified value or zero for default
    setsockopt(socketFD, IPPROTO_IP, IP_MULTICAST_TTL, &ttl, sizeof(ttl));
    if (status == -1)
    {
        if (errPtr)
            *errPtr = [self errnoErrorWithReason:@"Error setting ttl (setsockopt)"];

        close(socketFD);
        return SOCKET_NULL;
    }
```

**Comment by mofus** [comment]
I am unsure if this has been implemented yet?

**Comment by wallisch** [comment]
Still not implemented i guess? Also, the hack doesn't work anymore.

**Comment by mjannace** [comment]
Created A pull Request for this issue #520
