### ISSUE TITLE
Should the host name include rtmp://?

### ISSUE THREAD

**Issue by justinmakaila** [robbiehanson/CocoaAsyncSocket#142]
I'm attempting to use your socket for rtmp streaming of h264 video and aac audio. The stream goes to a wowza media server on port 1935, and is executed like so:

``` objective-c
    [_socket connectToHost:hostURL onPort:1935 error:&error];
```

No error ever comes back, yet the `[_socket connectedHost] && [_socket connectedPort]` are always null, even though `[_socket isConnected]` returns true. Also, should the hostURL be "http://example.com/", "http://example.com/app/stream", or "rtmp://example.com/app/stream"?

**Comment by ttran4040** [comment]
I'm having this issue now. Anyone else worked on this?
