### ISSUE TITLE
GCDAsyncSocket never deallocs

### ISSUE THREAD

**Issue by peternlewis** [robbiehanson/CocoaAsyncSocket#146]
GCDAsyncSocket will never deallocate because the dispatch_source_set_event_handler holds a reference to a block which holds a reference to the GCDAsyncSocket self.

This results in the inability to close and then reopen a GCDAsyncSocket listener as the address is already in use.

This can be resolved by changing the reference to a weak reference.  Before the dispatch_source_set_event_handler, add the line:

  __weak GCDAsyncSocket\* weakSelf = self;

and then using weakSelf instead of self to call doAccept.

  while ([weakSelf doAccept:socketFD] && (++i < numPendingConnections));

You need to repeat this twice, once for ipv4 and once for ipv6.

At this point, you'll discover that it is a good thing GCDAsyncSocket is never dealloced because it crashes immediately the dealloc is run.  This is because dealloc calls closeWithError, which in turn calls the delegate socketDidDisconnect, passing the GCDAsyncSocket self as a parameter.  ARC promptly retains the GCDAsyncSocket which crashes as the GCDAsyncSocket is currently being deallocate.

This can be resolved by moving the "delegate = nil" to the start of the dealloc, which you may as well do as it is impossible to call the delegate safely at that point (well, it is impossible if you want to be able to pass the GCDAsyncSocket, which you can no longer do).  An alternative would be to call socketDidDisconnect:nil in this case.

Either way, it means that socketDidDisconnect will not be called, or alternatively, will not be called with the appropriate GCDAsyncSocket as a parameter, which may break the API contract, but is unavoidable at this point.

A better API would be to have some sort of "Kill" method call to kill the GCDAsyncSocket before the dealloc happens.

**Comment by chinna834** [comment]
I am using GCDAsyncSocket as a server and tried to 'acceptOnPort' . Method returned YES and didAcceptNewSocket delegate is not fired . Couldn't able to identify wether this is a issue from my end or it is a bug.

It would be great to call a delegate to notify the issue if socket is not accepted .

**Comment by ExoticObjects** [comment]
I'm still getting this bug in 7.4.2. Maybe I'm doing something wrong? 

Basically, I can't close and reopen a GCDAsyncSocket. The `acceptOnPort` method returns NO...

Any advice?

**Comment by ExoticObjects** [comment]
A note for future readers. If you encounter this error, my guess is that you did one of the things @robbiehanson lists above:

1. The delegate/owner is deallocated, and doesn't bother cleaning up the socket
2. The delegate/owner explicitly invokes asyncSocket = nil without disconnecting it first

With ARC I'd gotten used to not having to implement dealloc. So, when my `GCDAsyncSocketDelegate` was destroyed, I wasn't disconnecting the socket. Doing the following in my delegate - which is the owner of the socket instance - solved the problem:

```
- (void)dealloc {
    [self.server disconnect];
    self.server.delegate = nil;
    self.server = nil;
}
```

**Comment by quhaoran007** [comment]
Hi @robbiehanson,
Is there a solution for this ?

**Comment by osfunapps** [comment]
This worked for me:
send a close() command to the socket, wait for it to close, and in the close delegate clean the client:

```
    /// will kill the client, if exists
    func killClient() {
        self.client?.close()
    }
```

```
/// disconnected
    func udpSocketDidClose(_ sock: GCDAsyncUdpSocket, withError error: Error?) {
        delegate.onUdpClientDisconnected(error: error)
        cleanClient()
    }
```
```
/// will reset (allocate) the client
    private func cleanClient() {
        self.client?.setDelegateQueue(nil)
        self.client?.setDelegate(nil)
        self.client?.pauseReceiving()
        self.client = nil
    }
```
