### ISSUE TITLE
GCDAsyncSocket.m:5865:32: Access to instance variable 'tlsSettings' results in a dereference of a null pointer (loaded from variable 'tlsPacket')

### ISSUE THREAD

**Issue by albyho** [robbiehanson/CocoaAsyncSocket#147]
XCode 4.6.1:

GCDAsyncSocket.m:5865:32: Access to instance variable 'tlsSettings' results in a dereference of a null pointer (loaded from variable 'tlsPacket')

How to fix this?

**Comment by funnel20** [comment]
It seems that the solution for this issue is not present in the current version (7.4.3).
Xcode 7.2.1 still shows the same warning, when running Product -> Analyze.

Is this removed by accident?

**Comment by mbeaty** [comment]
Bump. Seeing the same thing as @tunnel20

**Comment by tsznober** [comment]
Seeing the same thing from Xcode 7.3.

**Comment by funnel20** [comment]
Created new issue #464 to follow this up.
