### ISSUE TITLE
Client certificate authentication

### ISSUE THREAD

**Issue by AdamSelene** [robbiehanson/CocoaAsyncSocket#15]
GCDAsyncSocket does not allow client certificate authentication, even if the certificate is transmitted by the client.
This is because SecureTransport has a default authentication requirement set to kNeverAuthenticate and, as far as I know, there's no way to change this with GCDAsyncSocket.
Because of that, SSLCopyPeerCertificates(sslContext, &certs) will get you a nil object.

Simple patch below

GCDAsyncSocket.h:
extern NSString *const GCDAsyncSocketSSLClientSideAuthentication;

GCDAsyncSocket.m:
NSString *const GCDAsyncSocketSSLClientSideAuthentication = @"GCDAsyncSocketClientSideAuthentication";

in maybeStartTls:

// Configure SSLContext from given settings
// 
// Checklist:
// 1. kCFStreamSSLPeerName
// 2. kCFStreamSSLAllowsAnyRoot
// 3. kCFStreamSSLAllowsExpiredRoots
// 4. kCFStreamSSLValidatesCertificateChain
// 5. kCFStreamSSLAllowsExpiredCertificates
// 6. kCFStreamSSLCertificates
// 7. kCFStreamSSLLevel
// 8. GCDAsyncSocketSSLCipherSuites
// 9. GCDAsyncSocketSSLDiffieHellmanParameters
// 10. GCDAsyncSocketSSLClientSideAuthentication

...
// 10. GCDAsyncSocketSSLClientSideAuthentication
        if (isServer) {
            value = [tlsSettings objectForKey:GCDAsyncSocketSSLClientSideAuthentication];
            NSNumber *sslAuthNumber = (NSNumber *)value;
            int sslAuth = [sslAuthNumber intValue];
            if (sslAuth == kTryAuthenticate
                || sslAuth == kAlwaysAuthenticate
                || sslAuth == kNeverAuthenticate)
                status = SSLSetClientSideAuthenticate(sslContext, sslAuth);
            if (status != noErr)
            {
                [self closeWithError:[self otherError:@"Error in SSLSetClientSideAuthenticate"]];
                return;
            }
        }

Then just set the tlsSettings (on the server side only) like this:
    [tlsSettings setObject:[NSNumber numberWithInt:kAlwaysAuthenticate] forKey:(NSString *)GCDAsyncSocketSSLClientSideAuthentication];

**Comment by rypyl** [comment]
we are looking all over for an example of how to get mutual authentication working with this library, we accomplished it with openssl, but it does not always play well with IOS especially in certain case when device powers down or if we want background processing.

Any way to get some example code on how to setup mutual authentication

**Comment by glaszig** [comment]
@snej would you be willing to share parts of your code critical to the solution of this issue?

**Comment by snej** [comment]
It should be in https://github.com/couchbaselabs/CocoaHTTPServer somewhere...

**Comment by alisolutions** [comment]
Did anyone find any solution for mutual Authentication? I need client authentications as well.

**Comment by matthiasnagel** [comment]
I will ping again. Is it still a topic for anybody?
