### ISSUE TITLE
Long delays or timeouts in Mac/SSL connections

### ISSUE THREAD

**Issue by peternlewis** [robbiehanson/CocoaAsyncSocket#151]
There is at least one case where reading from an SSL connection suffers either a long delay or timeout because data is left unread.  This is caused by readLengthForNonTermWithHint returning a short value instead of simply reading until you run out of data and get a "will block" error.

Change 

```
    return MIN(bytesAvailable, (readLength - bytesDone));
```

to

```
    return readLength - bytesDone;
```

Given the available of reading until you get a "will block" error, you should always do that rather than read less.

Even given this fix, I am suspicious there can still be cases where data comes in while you are reading and then goes unnoticed.  Determining the real root cause of this issue would probably be required to know exactly why the data is being left behind.

**Comment by jdeff** [comment]
Perhaps this is related #599
