### ISSUE TITLE
GCDAsyncUdpSocket bound to specified interface does not receive broadcast packets

### ISSUE THREAD

**Issue by ochong** [robbiehanson/CocoaAsyncSocket#153]
The way the socket is configured when `- (BOOL)bindToPort:(uint16_t)port interface:(NSString *)interface error:(NSError **)errPtr` is called does not allow broadcast packets to be received.

From some research it looks as though `nativeAddr4.sin_addr.s_addr = htonl(INADDR_ANY);` would need to be added (for IPv4) to allow a specified interface to accept broadcast packets, similar to when no interface is specified.

Assuming it is safe to do this, I would propose that the message signature change from `- (BOOL)bindToPort:(uint16_t)port interface:(NSString *)interface error:(NSError **)errPtr` to `- (BOOL)bindToPort:(uint16_t)port interface:(NSString *)interface broadcastAllowed:(BOOL)allowed error:(NSError **)errPtr` and act appropriately.

What I don't fully know are all the consequences of setting this parameter. Hopefully, someone with more experience will comment.

**Comment by gyurisc** [comment]
I would be very interested in solving this issue. Did anyone attempted to change the signature and try the library this way?

**Comment by svdo** [comment]
I just ran into this issue as well. Any new insights/comments?

**Comment by Joebayld** [comment]
I have this issue as well.. Broken on both multicast and regular udp. Any idea for a fix?

**Comment by zxl777** [comment]
Yes,This is a bug. But I can use 
[sock bindToPort:port interface:nil error:errPtr];
to fix it.
