### ISSUE TITLE
socketDidDisconnectWithError not getting called if socket is disconnected by other party after a write?

### ISSUE THREAD

**Issue by kneeraj1762** [robbiehanson/CocoaAsyncSocket#173]
socketDidDisconnectWithError not getting called if socket is disconnected by other party after a write?

If I write something in socket and then the other party disconnects no callback function is there..

If there is no write then I get a callback?

**Comment by githubdbbest** [comment]
I got this when after delegate xmppStreamDidAuthenticate i sent not correct presence
XMPPPresence *presence = [XMPPPresence presenceWithType:@"available"]
this should be 
XMPPPresence *presence = [XMPPPresence presence];
[presence addChild:[NSXMLElement elementWithName:@"status" stringValue:@"Logged in (iOS)"]];
