### ISSUE TITLE
GCDAsyncSocket delegate calls are not working

### ISSUE THREAD

**Issue by timlukens** [robbiehanson/CocoaAsyncSocket#186]
I'm a little baffled by this one. I modded the ConnectTest project a little to connect to localhost (I'm also running the echoTest project as a host), and it works fine. Delegate calls go through as expected.

In my app, I have a class doing exactly this:

```
// in .h file
GCDAsyncSocket* socket_;

// in .m file
-(void)someFunction {
    socket_ = [[GCDAsyncSocket alloc] initWithDelegate:self delegateQueue:dispatch_get_main_queue()];

    if(![self.socket connectToHost:@"localhost" onPort:9413 error:&error])
    {
        NSLog(@"ServerRequestController: error connecting to host");
        return;
    }
}

- (void)socket:(GCDAsyncSocket *)sock didConnectToHost:(NSString *)host port:(UInt16)port {
    NSLog(@"connected");
}
```

Looks good, no? The delegate call never happens. When I step through the didConnect code in GCDAsyncSocket.m I notice it gets to

```
if (delegateQueue && [delegate respondsToSelector:@selector(socket:didConnectToHost:port:)])
```

And it doesn't make it through this. Added an NSLog to tell me the result of delegate respondsToSelector - It doesn't respond - in fact the delegate seems to be garbage data.

Any tips?

**Comment by Calvin-Shen** [comment]
thanks,your solution give me hints for my same problems @timlukens
