### ISSUE TITLE
Unable to accept new socket (iOS)

### ISSUE THREAD

**Issue by alexmerkel** [robbiehanson/CocoaAsyncSocket#193]
I'm writing the server socket on Mac and iOS and I'm use the exact same code for both of these.

On my Mac, the Firewall popup shows up after starting the server and after that it accepts a client as normal.
But on my iPad, nothing happens after the server is started. The method socket:didAcceptNewSocket: isn't even called.

Has anybody an idea why?

**Comment by chinna834** [comment]
Hi ,

Can you explain what was the issue you faced . I stuck with the same issue .The method socket:didAcceptNewSocket: isn't even called. Below is the code i used .Thanks in Advance.

    int port = 5552;
    socketQueue = dispatch_queue_create("socketQueue", NULL);
    tcplistenSocket = [[GCDAsyncSocket alloc] initWithDelegate:self delegateQueue:socketQueue];
    NSError *error = nil;
    
    if([tcplistenSocket acceptOnPort:port error:&error])
    {
        NSLog(@"Accepted");
    }
    else{
        NSLog(@"Not Accepted");
    }

**Comment by alexmerkel** [comment]
Oh man, that was over a year ago, I really can't remember what the problem was :/
I just have two general things, that might be the cause of your problem.
1) make sure you are holding on to a reference to tcplistenSocket, so that the ARC doesn't dealloc it before the connection is established
2) in case the device is behind a NAT enable port forwarding
Not sure if that was helpful, I sadly didn't use git frequently enough back than so I can't go back and see what I changed to make it work.
