### ISSUE TITLE
Problem with storing large amount of data

### ISSUE THREAD

**Issue by mbutan** [robbiehanson/CocoaAsyncSocket#199]
Sorry for same topic, but I moved this topic from incorrect issue list.
"
I have really strange problem with SSL async connection. Everything works perfectly when reading data is small and could be received in one package. For this operation I use these methods:
[_asyncSocket writeData:data withTimeout:-1 tag:0];
[sock readDataToData:[GCDAsyncSocket LFData] withTimeout:-1 tag:0];

However when coming data has to be split on some parts ("didReadPartialDataOfLength" is invoked). Method didReadData is never called by first time, I have to invoke once again same request then in results I receive twice same response in didReadData. It's really wierd problem. Anybody have any idea what's wrong.

Sometimes happen that I writeData with some tag (for example 1) and in didReadData I receive tag that I used before that request (for example 0). 
Only after the second call the same method receives a valid tag.

Everything happens only for bigger parts of data."

**Comment by HB-Dimple** [comment]
Any solution for this?

**Comment by seanm** [comment]
How about a repro case? (I doubt you'll get unpaid volunteers to debug this for you without one.)
