### ISSUE TITLE
AsyncSocket crash on close

### ISSUE THREAD

**Issue by PrernaChavan** [robbiehanson/CocoaAsyncSocket#213]
I am using ARC so when my iPad device go into sleep mode my app gets crash saying [AsyncSocket close] unrecognised instance send to selector.

**Comment by arayinfree** [comment]
try this 
- (void) closeSocket
{
    if (_asyncSocket != nil) {
        [_asyncSocket disconnect];
        [_asyncSocket setDelegate:nil];
        _asyncSocket = nil;
    }
}

**Comment by WangJace** [comment]
@arayinfree  I can't Find the method -(void) closeSocket in AsyncSocket.m
