### ISSUE TITLE
GCDAsyncSocket and dealing with multiple TCP client sockets to different hosts

### ISSUE THREAD

**Issue by ghost** [robbiehanson/CocoaAsyncSocket#231]
Hello, i know this is not a discussion list here, but i have a short question about GCDAsyncSocket and handling multiple tcp client sockets. Maybe somebody would be that greatful to help me out.

What is the prefered way of dealing and working with multiple tcp client sockets?  

We want to implement an app which has a tableview where serveral servers can be added.  Those servers can be connected to and information gets pulled from them.  At the moment we have implemented the connection with a single socket which is working great for one server, but selecting a second server will currently disconnect the existing socket and re-use it for the new connection, which means we have no connection persistance.

Ideally we would like to initiate three different sockets with different ports for each server selected. So for example lets say you select server1 there will three sockets initiated and connected to  server1.com:80, server1.com:22 and server1.com:25 , which means each socket therefore would require different request and response handling for the callbacks and delegates as the server-side protocol implementation is different for each socket connection.

How to deal with the different callbacks and delegates required for each socket?

How this would be ideally achieved from a design perspective?

Thank you very much in Advance

Edit: Stackoverflow link with my current code for reference
http://stackoverflow.com/questions/23177235/implementing-a-socketmanger-for-cocoaasyncsocket-to-handle-multiple-simultaneous

**Comment by zhangtemplar** [comment]
@dschallert I have the same problem.
