### ISSUE TITLE
Add method for setting maxSendPacketSize on UDP socket

### ISSUE THREAD

**Issue by EvilClay** [robbiehanson/CocoaAsyncSocket#244]
Please add method to set max UDP packet size using and parameter setsockopt() SO_SNDBUF. Currently the default value on iOS is 8000 and if I try to send larger packets the send silently fails.

Thank you.

**Comment by Jageen** [comment]
Any one here to response for this issue  ? 

I wrote below code before sending message but still not working
setsockopt(socket4FD, SOL_SOCKET, SO_SNDBUF, (const void *)&length, sizeof(length));

It will be great full if some one come up with hint or something.

Thanks
