### ISSUE TITLE
Clarify license position

### ISSUE THREAD

**Issue by andyp1per** [robbiehanson/CocoaAsyncSocket#257]
Hi Robbie,

Any chance you could clarify the license position of CocoaAsyncSocket by putting a LICENSE file in the the repo? I believe it's public domain, but it would be good for it to be called out explicitly.

Thanks!

andy

**Comment by joeljfischer** [comment]
All the code files have the license callout at the top of the file.

**Comment by adamn** [comment]
A LICENSE file would still be nice.  Some classes don't have the license, nor do the images, etc...

The simple MIT license: http://choosealicense.com/licenses/mit/

Or more consistent with the existing public domain headers: http://choosealicense.com/licenses/unlicense/

**Comment by albertodebortoli** [comment]
+1 Would be great to have a license file. Could you please pick one and update the repo @robbiehanson ?
