### ISSUE TITLE
THE CONNECTION DONE ONCE then second time stopped at connectToHost not call diddisconnectwitherr function

### ISSUE THREAD

**Issue by anthonyios** [robbiehanson/CocoaAsyncSocket#260]
I'm currently working on using GCDAsyncSocket my aim is to set up the app can support changing ip(s) [in total 3 ip] which means if mainip doest work when calls diddiconnectwitherr i used a call to do again with secondip and seconport if still cannot then use the backup ip and backup port

and my testing is mainip set and second set is wrong, and the backup one corrects the application is working perfectly fine with the first time [which means i successfully change ip] then if i do once again the log shows that when call connectToHOST function then no more changing and stop at there

may i ask how to fix it ? i through its socket dealloc problem but not really then searched through here and tried to change it to weak self socket -> still not working

Please help me. Thank You

**Comment by PeterHan1981** [comment]
I encounter the same trouble too.
my disconnect code is:

**Comment by PeterHan1981** [comment]
I encounter the same trouble too.
my disconnect code is:
- (void)myDisconnect
{
    [self.mSocket setDelegate:nil delegateQueue:NULL];
    [self.mSocket disconnect];
    self.mSocket = nil;
}
But the second time I connect the same host, The GCDAsyncSocket's function named setupReadAndWriteSourcesForNewlyConnectedSocket in to socketFDBytesAvailable=0, so it calls 
[strongSelf doReadEOF]; and then automatic disconnect. So I can't connect the host. Can you help me ?
Thanks
