### ISSUE TITLE
associate arbitrary information with the socket

### ISSUE THREAD

**Issue by hashemp206** [robbiehanson/CocoaAsyncSocket#262]
Thanks for developing this great library
I have created a simple client server application with GCDAsyncSocket.

host broadcast its service via bonjour, clients get connected to it, then each client send specific information to host, after completing requests by host, it should now be able to send each request to its corresponding client.

Here when client disconnected (maybe rebooting WiFi) before It gets its completed request and connected again its connected host and port can change.

so for I denitrifying clients I want to store list of connected clients in a dictionary

key : vendorID (specific to each client and can't change)
value :  connected host and port (gcdAsyncSocket instance) 

it seems GCDAsyncSocket has a property named UserData, I set it with vendorID in the client but in the host it's NULL.

client:

   `- (BOOL)connectWithService:(NSNetService *)service { 
   BOOL _isConnected = NO;

   // Copy Service Addresses 
   NSArray *addresses = [[service addresses] mutableCopy];

   if (!self.socket || ![self.socket isConnected]) {
    // Initialize Socket

```
   self.socket = [[GCDAsyncSocket alloc] initWithDelegate:self      delegateQueue:dispatch_get_main_queue()];

    //adding deviceID to sockect to identify connected clients in the host

    self.socket.userData = @"Aboonjami2308746238764021";

    // Connect
    while (!_isConnected && [addresses count]) {
        NSData *address = [addresses objectAtIndex:0];
        NSError *error = nil;

        if ([self.socket connectToAddress:address error:&error]) {
            _isConnected = true;
        }

        else if (error) {
            NSLog(@"Unable to connect to address. Error %@ with user info %@.", error, [error userInfo]);
        }
    }

} else {
    _isConnected = [self.socket isConnected];
}

return _isConnected;
```

}`

Host:
- (void)socket:(GCDAsyncSocket *)socket didAcceptNewSocket:(GCDAsyncSocket *)newSocket {
  NSLog(@"Accepted New Socket from %@:%hu", [newSocket connectedHost], [newSocket connectedPort]);
  
  //both userData is null!
  NSLog(@"%@",newSocket.userData);
  NSLog(@"%@",socket.userData);
  //adding new socket to the list of connected clients
  //using ip and port of the scoket as key
  [self.clients setObject:newSocket forKey:[NSString stringWithFormat:@"%@-%d", [newSocket connectedHost], [newSocket connectedPort]]];
  // Notify Delegate
  [self.delegate tcpHost:self didHostClientOnSocket:newSocket];
  }

**Comment by mohammdsss1** [comment]
@hashemp206 did find a solution for this one?

**Comment by hashemp206** [comment]
It's very old issue, and I don't remember. I maybe used other solutions, otherwise I would mention it here
