### ISSUE TITLE
Multicasting packet using GCDAsyncUdpSocket is not working

### ISSUE THREAD

**Issue by adel-tahir14** [robbiehanson/CocoaAsyncSocket#270]
Hi,

I have very strange problem with UDP Multicasting on iOS.

My app is multicasting packets to address "239.19.92.72" at port no "1411".

I run this app on Simulator and my iPhone.

Problem is packets from iPhone is discoverable on Simulator, but packets from Simulator is not received on iPhone.
(The IP addresses are in the same network. 192.168.1.126/24 and 192.168.1.137/24)

The packet sent from itself is received.

If I run this app on two devices, no one's working at all.

Thanks in advance.

Adel

**Comment by suxinde2009** [comment]
Same as mine, I come across the same problem, I run it on two devices, none of it works, it seems the udp packet was dropped when it goes through the router casuse gcdasyncudpsocket's ttl
is 1 by default, and it doesn't provide an interface to change the value of ttl.

**Comment by mjannace** [comment]
Created A pull Request for this issue #520
