### ISSUE TITLE
xcode kCFStreamSSLAllowsAnyRoot Deprecated warning when build with Xcode 6 

### ISSUE THREAD

**Issue by yangzhihao** [robbiehanson/CocoaAsyncSocket#273]
![image](https://cloud.githubusercontent.com/assets/1145330/4285533/d1fa1d3e-3d87-11e4-8d14-23377d41243d.png)

how to solve it?

**Comment by ChrisAshworth** [comment]
This is a duplicate issue of #269 filed earlier.
