### ISSUE TITLE
didAcceptNewSocket Never calls 

### ISSUE THREAD

**Issue by chinna834** [robbiehanson/CocoaAsyncSocket#299]
I am using GCDAsyncSocket as a server and tried to 'acceptOnPort' . Method returned YES and didAcceptNewSocket delegate is not fired . Couldn't able to identify wether this is a issue from my end or it is a bug.

It would be great to call a delegate to notify the issue if socket is not accepted .

**Comment by oxrider** [comment]
@chinna834 were you able to solve your problem? I am encountering the same problem and could use your experience if you'd like to share :)

**Comment by mtzaquia** [comment]
I'm facing the same issue. Using swift. Sockets are strongly referenced and server delegates are never called :(

Anyone?

**Comment by oxrider** [comment]
@mtzaquia the problem is that for cell phones, you don't always get a public IP address that can be connected to from outside. I solved my problem by changing my design so that I don't use phone as a server.
