### ISSUE TITLE
General CFSocket error - only with iphone 6 to earlier devices

### ISSUE THREAD

**Issue by canoliehuber** [robbiehanson/CocoaAsyncSocket#300]
I am running an app I made a while back. It works great in all scenarios except one. Creating the server on an older device... i.e. ipad 3, iphone 5 and trying to connect a client running on iphone 6. If I run the server on the iphone 6 the older devices can connect to it but not visa versa. I spent a good amount of time debugging and it look like that the iphone 6 sees that the address of the server is not ipv4 or ipv6 and so it fails. Has anyone else run into this? Thanks.  

forgot to mention... if I try several connection attempts over time ( a couple minutes ) the iphone 6 will eventually connect to the server at the expected IPV4 address. I have tested now for about a week and the issue only seems to happen with the new iphone 6 connecting as a client to a server on an older device. If all devices are older they all connect to each other fine. if the server is running on the new iphone 6 all old devices connect to it fine. 

thanks again,
c

**Comment by praveensharma** [comment]
I'm having the same issue did you ever figure this out?
