### ISSUE TITLE
Error Domain=NSPOSIXErrorDomain Code=32 "Broken pipe"

### ISSUE THREAD

**Issue by springlo** [robbiehanson/CocoaAsyncSocket#302]
if I send big data to server,I get the Error in  
- (void)socketDidDisconnect:(GCDAsyncSocket *)sock withError:(NSError *)err {
        NSLog(@"error:%@", err);
}

Error Domain=NSPOSIXErrorDomain Code=32 "Broken pipe" UserInfo=0x174267040 {NSLocalizedDescription=Broken pipe, NSLocalizedFailureReason=Error in write() function}

my code:
       self.asyncSocket = [[GCDAsyncSocket alloc] initWithDelegate:self     delegateQueue:dispatch_get_main_queue()];
      NSError *err = nil;
      if (![self.asyncSocket connectToHost:SERVER_IP onPort:SERVER_PORT  withTimeout:-1 error:&err]) {
              NSLog(@"I goofed: %@", err);
    }

- (void)socket:(GCDAsyncSocket *)sender didConnectToHost:(NSString *)host port:(UInt16)port {
    [self.asyncSocket readDataWithTimeout:-1 tag:100];
    NSLog(@"Cool, connect success.");
}
- (void)socketDidDisconnect:(GCDAsyncSocket *)sock withError:(NSError *)err {
    NSLog(@"%@", err);
}
- (void)socket:(GCDAsyncSocket *)sock didWriteDataWithTag:(long)tag {
    NSLog(@"success");
}

and there is send code:

        NSString *saveName = @"AA.mp3";
        NSString *path = [FolderHelper getPathOnDocuments:@"song" fileName:saveName];
        NSData *data = [[NSData alloc] initWithContentsOfFile:path];
        [self.asyncSocket writeData:data withTimeout:-1 tag:100];

**Comment by yasiriqbal** [comment]
Did you find any solution? same problem here!

**Comment by ceceYax** [comment]
Any solution??? Same problem also for me!

**Comment by HF-IOS** [comment]
it will help you solution the problem.

- (void)applicationDidEnterBackground:(UIApplication *)application
{
    //close UDP Socket here
}
and then turning it back on when it comes back to foreground.

- (void)applicationWillEnterForeground:(UIApplication *)application
{
    //open UDP Socket again and continue tasks
}

**Comment by rainedAllNight** [comment]
> * and then turning it back on when it comes back to foreground.
We need write data in background so we can't close tcp socket , do you have any solution?
