### ISSUE TITLE
CGDAsyncSocket delegate method NOT called

### ISSUE THREAD

**Issue by hanshuaigithub** [robbiehanson/CocoaAsyncSocket#303]
call CGDAsyncSocket in UIViewController,delegate method works fine.
- (void)viewDidLoad {
  [super viewDidLoad];
  // Do any additional setup after loading the view, typically from a nib.
  
  dispatch_queue_t mainQueue = dispatch_get_main_queue();
  
  _asyncSocket = [[GCDAsyncSocket alloc] initWithDelegate:self delegateQueue:mainQueue];
  NSError *error = nil;
  if (![_asyncSocket connectToHost:@"127.0.0.1" onPort:8080 error:&error])
  {
      NSLog(@"err");
  }
  }
  //....the delegate method

But when call CGDAsyncSocket in NSObject,the delegate method NOT call in the NSObject Type object.Anyone can help,and tell me why Thanks.
- (id)init
  {
  if (self = [super init]) {
      dispatch_queue_t mainQueue = dispatch_get_main_queue();
      asyncSocket = [[GCDAsyncSocket alloc] initWithDelegate:self delegateQueue:mainQueue];
  
  ```
  NSError *error = nil;
  if (![asyncSocket connectToHost:@"127.0.0.1" onPort:8080 error:&error])
  {
      NSLog(@"connect to server err:%@",error);
  }
  ```
  
  }
  return self;
  }

//....the delegate method

this code works make the delegate method works fine.
@property (nonatomic, strong) DWAPNSSocket *mySelf;
- (id)init
  {
  if (self = [super init]) {
      dispatch_queue_t mainQueue = dispatch_get_main_queue();
  
  ```
  self.mySelf = self;
  asyncSocket = [[GCDAsyncSocket alloc] initWithDelegate:self.mySelf delegateQueue:mainQueue];
  
  NSError *error = nil;
  if (![asyncSocket connectToHost:@"127.0.0.1" onPort:8080 error:&error])
  {
      NSLog(@"connect to server err:%@",error);
  }
  ```
  
  }
  return self;
  }

**Comment by lvandyk** [comment]
Anyone also facing this issue? I'm trying to create my own API Client class and inherits from NSObject which also has the same issue. I also used the solution above to fix the problem.
