### ISSUE TITLE
Socket server creation with CocoaAsyncSocket

### ISSUE THREAD

**Issue by souvickcse** [robbiehanson/CocoaAsyncSocket#308]
Hi,
I want to create a peer2peer connection between two iOS device. With CocoaAsyncSocket we can connect to a host. But can we make a host with CocoaAsyncSocket in a iOS device, so that it will give the host ip and port and from another device I can connect to that host and port. Is there any documentation?

**Comment by joeljfischer** [comment]
See the wiki: https://github.com/robbiehanson/CocoaAsyncSocket/wiki/Intro_GCDAsyncSocket under "Writing a Server"

**Comment by souvickcse** [comment]
Hi,
Thank You for your response. I am able to connect to another device when both are under same nat. But when they are under different nat, i am not able to connect it. Is that possible to connect two device via tcp when they are under different nat?

**Comment by souvickcse** [comment]
Closing this issue. I am able to do p2p connection even on under different nat with the help of external server. But it is not always possible to create p2p connection. If anyone need any help regarding this ping me, I will try my best to help. Thank You.
