### ISSUE TITLE
No route to host error

### ISSUE THREAD

**Issue by anomaly2104** [robbiehanson/CocoaAsyncSocket#312]
I am debugging a error in which while connecting socket, I am getting following error:
`[error = Error Domain=NSPOSIXErrorDomain Code=65 "The operation couldn’t be completed. No route to host"]`

One possible problem might be this:
http://stackoverflow.com/a/4710512/1541873

As per above SO post, it happens more often in `BSD sockets` and not in `CFStreamSocket`. Can somebody please confirm whether `CocoaAsyncSocket` uses former or later?

**Comment by JJLewis** [comment]
I'm having a similar issue.
For some reason, it is happy to connect to a TCP Socket (not local) from the iPhone Simulator, but not from an iPhone.
Any suggestions on why this might be happening? (I understand that this is very little information to make use of).
Thanks in advance.

**Comment by zjz2020** [comment]
How to solve this problem At last, I also met the same problem

**Comment by lexin** [comment]
Have the same issue. Both - simulator and device.
