### ISSUE TITLE
TCP connection broken on lock screen

### ISSUE THREAD

**Issue by atanupal22** [robbiehanson/CocoaAsyncSocket#316]
I am using xmppframework in my application, which internally uses CocoaAsyncSocket. The library I am using is one year old.

When I lock screen on my iPhone 5c on 3G network the TCP pipe breaks, I don't know why but it doesn't happen on WiFi.

Does anyone facing this issue with GCDAsyncSocket? 

Should I consider upgrading the libraries? Will that fix the issue?

**Comment by chrisballinger** [comment]
Unless you have VoIP background privileges, and have applied the VoIP flag to the socket, iOS will close your socket in the background.

**Comment by atanupal22** [comment]
Fortunately our application is VOIP application, and it is added in plist also.

The TCP connection used for VOIP calls are unaffected but the TCP from GCD gets disconnected.

One more weird/interesting fact I came across while testing is that it happens only once after first launch of application, when I unlock the screen again our foreground application logic recreates the connection, then if I lock screen again this issue is not happening.

Hence I tried reconnecting in resignActive method, where I am intentionally closing and recreating the connection, after which the TCP does persists without issue.

Now since recreating connection is bit costly for me with XMPP protocol, since it will exchange a lot of data in this process, I would like to know why exactly it is happening & how to fix it.

Old days we used CFStream for plain TCP connection & we never faced this issue, GCD being a wrapper of CFStream, I wonder why is this issue there.

**Comment by arunkumariitkgp** [comment]
I am also facing the same issue. But I am using AsyncSocket (not GCDAsyncSocket) in my application. 
When I tap on power button of the device, the connection is broken.
This is happening only for iOS 7.x devices. And successfully running on iOS 8.x one's. 
Mine is also voip app and added the respective flag in the plist and socket delegate method onSocket:didConnectToHost:port as below.
    CFReadStreamSetProperty([sock getCFReadStream], kCFStreamNetworkServiceType, kCFStreamNetworkServiceTypeVoIP);
    CFWriteStreamSetProperty([sock getCFWriteStream], kCFStreamNetworkServiceType, kCFStreamNetworkServiceTypeVoIP);
Please suggest the fix.

**Comment by atanupal22** [comment]
@Arun thanks buddy, i was hoping for that, let me try with 8.x devices will update the result soon.

**Comment by atanupal22** [comment]
@Arun thanks buddy, i was hoping for that, let me try with 8.x devices will update the result soon.

**Comment by atanupal22** [comment]
@Arunkumariitkgp thanks buddy, i was hoping for that, let me try with 8.x devices will update the result soon.

**Comment by atanupal22** [comment]
Arunkumariitkgp thanks buddy, i was hoping for that, let me try with 8.x devices will update the result soon.

**Comment by atanupal22** [comment]
Coding mistake, the Boolean which makes the background logic in XMPPframework was turned to YES after connection establishes, we just have to this before making the connection.
