### ISSUE TITLE
Is it ok to mark my app to be VoIP even it is not really a VoIP app?

### ISSUE THREAD

**Issue by purpleblues** [robbiehanson/CocoaAsyncSocket#317]
I'm using CocoaAsyncSocket, but as you know, socket disconnects in a short time when the app is in background.

I heard if it is VoIP app, socket connection is maintained. However, My app has no relation with VoIP. It is a game.

If I mark and use socket connection as a VoIP, will it be rejected by App Store review?

**Comment by chrisballinger** [comment]
Yes, you will be rejected.
