### ISSUE TITLE
AsyncSocket couldn't determine IP version of socket

### ISSUE THREAD

**Issue by nameghino** [robbiehanson/CocoaAsyncSocket#32]
I'm trying to use the library in an iPad application and whenever I try to use an AsyncSocket, I get the following error:

2012-03-02 17:21:40.407 Sucursales2[11862:707] AsyncSocket 0x4464dc0 couldn't get socket from streams, Error Domain=AsyncSocketErrorDomain Code=-1 "General CFSocket error" UserInfo=0x595590 {NSLocalizedDescription=General CFSocket error}. Disconnecting.
Error: : No such file or directory

I'm running an iPad 2 3G+WiFi with 5.0.1 

The weird thing is that I copied both the AsyncSocket classes and a client class to my new app from a previous project in which AsyncSocket worked perfectly without any issues.

I thought that it would be a matter of the new app being compiled with SDK 5.0, so I downloaded the latest archive from github, but still experiencing the problem.

Any ideas on what it might be?

PS; I'm NOT using ARC for this project.

**Comment by xiaolinyeyi** [comment]
How did you solve it? Can you show the detail? I feel sorry that my English is so so...

**Comment by nature19862001** [comment]
意思就是：之前从旧的项目拷贝过来了AsyncSocket和一些代码，结果报错了。后来发现是ip的问题，于是把ip设置对了，就好了。
