### ISSUE TITLE
Question: Support for DTLS in GCDAsyncUDPSocket?

### ISSUE THREAD

**Issue by billybobbain** [robbiehanson/CocoaAsyncSocket#320]
Are there any plans to support DTLS in GCDAsyncSocket?

**Comment by chrisballinger** [comment]
@billybobbain I like this idea. According to the [DTLS Wiki page](https://en.wikipedia.org/wiki/Datagram_Transport_Layer_Security) only DTLS 1.0 is supported in Secure Transport, and is available OS X 10.8-10.10 / iOS 5-8.
