### ISSUE TITLE
New Socket Connection is immediately closed

### ISSUE THREAD

**Issue by DeRedBaron** [robbiehanson/CocoaAsyncSocket#323]
Hi guys,

```
   I'm writing a server in Swift and connecting to it using telnet. Here's my code so far:
```

var server = Server.sharedInstance

class Server: GCDAsyncSocketDelegate
{
    static var sharedInstance = Server(boundHost: "192.168.103.105", port: 6667)

```
let boundHost : String
let port : UInt16
var socket:GCDAsyncSocket?

init(boundHost: String?, port: UInt16)
{
    self.boundHost = boundHost!
    self.port = port

    println("Server created with host: \(self.boundHost) and port: \(self.port).")
}

convenience init(port:UInt16)
{
    self.init(boundHost: nil, port: port)
}

func startServer() -> Bool
{
    if !(socket != nil)
    {
        socket = GCDAsyncSocket(delegate: server, delegateQueue: dispatch_get_main_queue())
    }

    var error:NSError?

    if !socket!.acceptOnInterface(boundHost, port: port, error: &error)
    {
        println("Couldn't start socket: \(error)")
        return false
    }
    else
    {
        println("Listening on \(port).")
        return true
    }
}

func stopServer() -> Bool
{
    if (socket != nil)
    {
        socket!.disconnect()
        return true
    }
    return false
}

func socket(sock:GCDAsyncSocket!, didAcceptNewSocket newSocket:GCDAsyncSocket!)
{
    println("New socket received: \(newSocket)")
}
```

}

However, whenever I connect to this server using telnet, I immediately get disconnected. Why is this happening?

**Comment by Zyphrax** [comment]
I'm having the same problem.
Did you find a solution?

**Comment by ChaosCoder** [comment]
I know, it's been a while, but this issue is still open and not marked as closed, so here:

Documentation for `socket:didAcceptNewSocket:` says:
>You must retain the newSocket if you wish to handle the connection. Otherwise the newSocket instance will be released and the spawned connection will be closed.

As you are not storing (thus retaining) the `newSocket` anywhere, the exactly described behaviour happens.

**Comment by gbread** [comment]
I am storing it and it didnt help
