### ISSUE TITLE
Error coming after sending an image to server using GCDAsyncUdpSocket in iOS

### ISSUE THREAD

**Issue by KarthikMandava** [robbiehanson/CocoaAsyncSocket#324]
Error Domain=GCDAsyncUdpSocketErrorDomain Code=1 "Cannot specify destination of packet for connected socket" UserInfo=0x79158000 {NSLocalizedDescription=Cannot specify destination of packet for connected socket}"

**Comment by Nihility-Ming** [comment]
May be parameters error.

**Comment by KarthikMandava** [comment]
NSString *str=[NSString stringWithFormat:@"1:55:%@:IPhone:2097184:Hello\0 0:down-arrow.png:219:14de76bd790:1:\a",deviceInfo.name]; //Format for sending image. 2097184 is command number
