### ISSUE TITLE
QUESTION:HOW CAN I SET "TCP_NODELAY" TO SEND THE SMALL PACKET IMMEDIATELY?

### ISSUE THREAD

**Issue by Might-M** [robbiehanson/CocoaAsyncSocket#325]
in this function
- (BOOL)connectWithAddress4:(NSData _)address4 address6:(NSData *)address6 error:(NSError *_)errPtr;

i found this 
 "setsockopt(socketFD, SOL_SOCKET, SO_REUSEADDR, &reuseOn, sizeof(reuseOn));"

but there is no "TCP_NODELAY" defined to replace "SO_REUSEADDR"
SO,i think maybe i should define "TCP_NODELAY" a hex number,  does anybody know what number i should set?
OR the other way to set TCP_NODELAY?
THX!!

/*
- Option flags per-socket.
  _/
  #define SO_DEBUG    0x0001      /_ turn on debugging info recording */
# define SO_ACCEPTCONN   0x0002      /\* socket has had listen() */
# define SO_REUSEADDR    0x0004      /\* allow local address reuse */
# define SO_KEEPALIVE    0x0008      /\* keep connections alive */
# define SO_DONTROUTE    0x0010      /\* just use interface addresses */
# define SO_BROADCAST    0x0020      /\* permit sending of broadcast msgs */
# if !defined(_POSIX_C_SOURCE) || defined(_DARWIN_C_SOURCE)
# define SO_USELOOPBACK  0x0040      /\* bypass hardware when possible */
# define SO_LINGER   0x0080          /\* linger on close if data present (in ticks) */
# else
# define SO_LINGER   0x1080          /\* linger on close if data present (in seconds) */
# endif  /\* (!_POSIX_C_SOURCE || _DARWIN_C_SOURCE) */
# define SO_OOBINLINE    0x0100      /\* leave received OOB data in line */
# if !defined(_POSIX_C_SOURCE) || defined(_DARWIN_C_SOURCE)
# define SO_REUSEPORT    0x0200      /\* allow local address & port reuse */
# define SO_TIMESTAMP    0x0400      /\* timestamp received dgram traffic */
# define SO_TIMESTAMP_MONOTONIC  0x0800  /\* Monotonically increasing timestamp on rcvd dgram */
# ifndef **APPLE**
# define SO_ACCEPTFILTER 0x1000      /\* there is an accept filter */
# else
# define SO_DONTTRUNC    0x2000      /\* APPLE: Retain unread data */

/\*  (ATOMIC proto) */
# define SO_WANTMORE 0x4000      /\* APPLE: Give hint when more data ready */
# define SO_WANTOOBFLAG  0x8000      /\* APPLE: Want OOB in MSG_FLAG on receive */

**Comment by RVijay007** [comment]
All you need to do is #include <netinet/tcp.h> to see the definition of TCP_NODELAY.
