### ISSUE TITLE
Malloc: Double free error

### ISSUE THREAD

**Issue by vineeth89** [robbiehanson/CocoaAsyncSocket#328]
Hello Devs,

I am using GCDAsyncUdpSockets to send and receive udp data. I am making a copy of the received data and forming a tuple along with the timestamp. Each tuple is being added to another array. However while doing so, sometimes I get a double free error pointing to one of the autoreleasepool in doReceive method. Here is the code: 
- (void)udpSocket:(GCDAsyncUdpSocket *)sock didReceiveData:(NSData *)data fromAddress:(NSData *)address withFilterContext:(id)filterContext
  {
  dispatch_queue_t bg_queue = dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_HIGH, 0);
  NSString *msg = [[NSString alloc] initWithData:data encoding:NSASCIIStringEncoding];
  NSTimeInterval t = [self getTime];
  if (msg)
  {
      [self.activityQueue.activityQueue enqueue:@"1"];
      dispatch_async(bg_queue, ^{
          NSData \* d = [data copy];
              [self addRecvJitter:t withData:d];
          d= nil;
      });
  }
  }
- (void)addRecvJitter:(NSTimeInterval)t withData:(NSData *)data
  {
  
  NSString \* add = [NSString  stringWithFormat:@"%f",( t - self.jitterOrigin)];
  NSArray \* addToList = [[NSArray alloc] initWithObjects:add,data, nil];
  [_rcvdJitter addObject:addToList];
  }

Can I get some help regarding this?

Thanks

**Comment by seanm** [comment]
Have you tried guard malloc, address sanitizer, and/or valgrind?

**Comment by hegde5** [comment]
Hello Sean,

I am from the same team @vineeth89 . We have tried using guard malloc but it did not help us. The thing which worries us is that, we have not used any autoreleasepool blocks in our code. Two kinds of malloc error occurs:
1)Double free
2)Pointer being freed is not allocated
Both of them occur while adding the "addToList" tuple to the _rcvdJitter in the posted code. The stacktrace points to the autoreleasepool in the doReceive method. What might possibly be wrong?

**Comment by seanm** [comment]
Lots could be wrong.  Try ASan, it catches much that guard malloc doesn't.

**Comment by hegde5** [comment]
We were not able to fix the bug, instead we restructured(removed gcdasyncudpsocket) the part of our application by writing our own classes for udp sender and receiver. We do not get that error now. 

Our bug was similar to that of : https://github.com/robbiehanson/CocoaAsyncSocket/issues/9. You might want to check it again.

Thank you
