### ISSUE TITLE
Module 'CocoaAsyncSocket' not found after succesful pod install

### ISSUE THREAD

**Issue by royherma** [robbiehanson/CocoaAsyncSocket#333]
Installed library using Cocoapods,  then tried 

    @import CocoaAsyncSocket 

but getting the error

    Module 'CocoaAsyncSocket' not found after succesful pod install

Am i missing something here?

Thanks

**Comment by chrisballinger** [comment]
Ah, you need `use_frameworks!` in your Podfile. I'll update the README.

**Comment by chrisballinger** [comment]
Should be fixed, let me know if you have any other problems

**Comment by astrokin** [comment]
for those who do not want to `use_frameworks!` just add this into your Podfile 

`pod 'CocoaAsyncSocket', :modular_headers => true, :configurations => ['Debug']`
`pod 'Bagel', :configurations => ['Debug']`

`:configurations => ['Debug']` is optional for sure. that's was just in my case

**Comment by Viswanadh-277** [comment]
Is there any solution for this? none of the above not working in Xcode 16.
