### ISSUE TITLE
Deprecate RunLoop in 7.5?

### ISSUE THREAD

**Issue by chrisballinger** [robbiehanson/CocoaAsyncSocket#334]
Are there any compelling reasons to keep the RunLoop version going forward? We can keep around a separate `7.4-runloop` branch for security hotfixes for people including it in legacy code bases.

**Comment by robbiehanson** [comment]
> Are there any compelling reasons to keep the RunLoop version going forward?

I cannot think of any off the top of my head. And I would strongly encourage anyone to use the modern GCD version in new codebases. So I'd be fine with deprecating it.
