### ISSUE TITLE
create socket in swift v2.0

### ISSUE THREAD

**Issue by nahumOs** [robbiehanson/CocoaAsyncSocket#342]
hello,

i am trying to create socket and connect to host in swift 2.0 with no succsess.
some one can post example?

thx

**Comment by robinmacharg** [comment]
I'm having issues with low port numbers (ICMP Echo on 7) but for HTTP the following in my `application:didFinishLaunchingWithOptions:` app delegate connects successfully:

    self.socket = GCDAsyncSocket(delegate: self, delegateQueue:dispatch_get_main_queue())
    do {
        try self.socket!.connectToHost("google.com", onPort: 80, withTimeout: 5)
    }
    catch {
        print("oops")
    }

And the associated delegate method to check success:

    func socket(_: GCDAsyncSocket, didConnectToHost: String, port: UInt16) {
        print("connected")
    }

HTH.
