### ISSUE TITLE
socket:didAcceptNewSocket: not called when in Background

### ISSUE THREAD

**Issue by tounaobun** [robbiehanson/CocoaAsyncSocket#343]
I'm using CocoaAsyncSocket to make connection between Safari app and my server app.But when I push my server app into background and open Safari to connect to the app server.The callback socket:didAcceptNewSocket: is not being called.When I reopen the server app,the callback finally get called.

**Comment by wujiangwei** [comment]
How did you fix this issue? I need some help!

**Comment by wujiangwei** [comment]
@tounaobun

**Comment by tounaobun** [comment]
This issue has been sinked.@wujiangwe
