### ISSUE TITLE
Carthage is missing a Mac target

### ISSUE THREAD

**Issue by jeeftor** [robbiehanson/CocoaAsyncSocket#347]
The carthage setup does not include a mac target.

**Comment by jeeftor** [comment]
Submitted pull request #346

**Comment by petrmifek** [comment]
Had some issues with workspace/source code builds within XCode and had to make small changes here: #352 . Do those changes work for you? It's definitely better here, but I'm quite OS X biased right now and didn't do much real world testing at iOS. Thanks!

**Comment by Danappelxx** [comment]
Any updates? It seems to build only iOS for me
