### ISSUE TITLE
Using CocoaAsyncSocket as a server to communicate with WebSocket

### ISSUE THREAD

**Issue by tounaobun** [robbiehanson/CocoaAsyncSocket#348]
I'm using CocoaAsyncSocket as a server in my iOS app,and I use WebSocket in js to communicate with  the server.But the issue is that webSocket did not connect to it.

**Comment by lovehjun** [comment]
WebSocket is a protocol upper layer of TCP/IP. RFC6455 defines its specification. http://tools.ietf.org/html/rfc6455

**Comment by tounaobun** [comment]
Using https://github.com/zwopple/PocketSocket solves my problem.
