### ISSUE TITLE
10.11 and dispatch_async issue - Swift 2

### ISSUE THREAD

**Issue by Joebayld** [robbiehanson/CocoaAsyncSocket#349]
I have a app on 10.10 and it runs smoothly. It creates data and streams it pretty fast on a UDP Multicast group. 

Here's the issue... 
On 10.11 (GM Release), there is a memory leak issue. As the socket sends data, the memory used rises rapidly. Roughly 2mb a second, continuously. 

I've done work in instruments to track it, and the issue pinpoints to whenever dispatch_async is called. I even found that sometimes when I call dispatch_async in my code it will cause memory issues. Could this just be a 10.11 issue? Any ideas for a fix? 

I'll attach a couple screenshots. 

![1](https://cloud.githubusercontent.com/assets/9399317/9785223/a82ecc4a-577e-11e5-817e-a2db1c178099.jpg)

![2](https://cloud.githubusercontent.com/assets/9399317/9785262/0b02b55c-577f-11e5-9910-0ae68ed5bee4.jpg)

**Comment by ibuprofane** [comment]
I'm seeing a similar leak with Swift 2 and iOS 9.

**Comment by Joebayld** [comment]
Any idea on a fix? @ibuprofane

**Comment by jeanregisser** [comment]
Observed the same on iOS 9 with a swift 2 app, but only on the simulator. On a device it looks fine.
To me it looks like the problem is GCD not running the queued blocks fast enough. Even with a delegate that does nothing when it receives the data, the problem persists.

**Comment by jeanregisser** [comment]
More details: for me I see this problem only when Xcode is debugging the app on the iOS 9 simulator. If I run the app manually on the simulator, memory usage remains stable.
So it might be some kind of Xcode instrumentation that causes this problem.

**Comment by ibuprofane** [comment]
For me the issue is happening both in the simulator and on the device (with and without Instruments); app crashes after about 20 minutes (observed via crash reports as well).

**Comment by Joebayld** [comment]
This is kind of unfortunate. I believe the issue falls on Apple. Seems like a dispatch_queue problem. What's the next step to fixing this? Contacting apple?
