### ISSUE TITLE
GCDAsyncUdpSocket corrupt data in multiple thread mode

### ISSUE THREAD

**Issue by zhaoxiaokai520** [robbiehanson/CocoaAsyncSocket#351]
NSMutableArray *addresses  and sendQueue is not locked and corrupted in multiple thread mode. 
with this bug, using dispatch_async is just a joke!!

another one, GCDAsyncUdpSendPacket's member variable buffer and resolvedAddresses will be autoreleased and cause BAD_ACCESS, we should retain in init and release in dealloc.

**Comment by averello** [comment]
I have the same problem even not in multiple threads.

I'm sending many messages very fast, in 200ms intervals, through main thread. 
My messages either do not arrive at all to the receiver or arrive corrupted!
