### ISSUE TITLE
Carthage fails

### ISSUE THREAD

**Issue by joeljfischer** [robbiehanson/CocoaAsyncSocket#354]
Using Carthage 0.9.1
When trying to pull in "master" (06653f3f9951584ade03ac8bbdaaf5c3f14abc18 as of right now), carthage fails with error:

```
error: strip /Users/.../CocoaAsyncSocket.framework.dSYM/Contents/Resources/DWARF/CocoaAsyncSocket: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip
exited with 1
```
where the `...` is the long path to my project's carthage checkout.

**Comment by chrisballinger** [comment]
Did it work in earlier versions of Carthage or an earlier commit? There has been some Carthage stuff merged recently, but I don't use it myself so I'm just relying on the Travis results.

**Comment by joeljfischer** [comment]
I'm actually seeing this bug elsewhere now so it's probably my problem somehow.
