### ISSUE TITLE
Buffer Overrun in getInterfaceAddressFromUrl

### ISSUE THREAD

**Issue by swt2c** [robbiehanson/CocoaAsyncSocket#357]
In the recently merged UNIX domain socket code, I've recently noticed that there's a potential buffer overrun in getInterfaceAddressFromUrl:

```
NSString *path = url.path;
if (path.length == 0) {
    return nil;
}

struct sockaddr_un nativeAddr;
nativeAddr.sun_family = AF_UNIX;
strcpy(nativeAddr.sun_path, path.fileSystemRepresentation);
```

The function calls strcpy() without checking the string length of path.fileSystemRepresentation.  If path has a rather long filename, this will overrun the char sun_path[104].

Additionally, I have been running into this file length limitation when using files in shared group containers, e.g., /Users/<user>/Library/Group Containers/<group>/<socketfile>.  Thus it would be helpful to support a filename longer than 104 characters.  Allocating a larger buffer and passing it to OSX seems to work fine.

**Comment by chrisballinger** [comment]
Would you like to submit a PR?

**Comment by swt2c** [comment]
Yep, will do.

**Comment by chrisballinger** [comment]
Thanks!

**Comment by seanm** [comment]
I improved that here: https://github.com/robbiehanson/CocoaAsyncSocket/pull/341/

by using strlcpy().

**Comment by swt2c** [comment]
Ah, great.  I'll send a PR once that gets merged to just increase the buffer size.

**Comment by chrisballinger** [comment]
@seanm @swt2c #341 Merged!

**Comment by seanm** [comment]
This can be closed I think.
