### ISSUE TITLE
Carthage/Cocoapods tvOS support

### ISSUE THREAD

**Issue by ChaosCoder** [robbiehanson/CocoaAsyncSocket#362]
I tried to use CocoaAsyncSocket with Cocoapods and Carthage and it seems, CocoaAsyncSocket has no support for these yet.

Please add support for the platform tvOS.

`carthage update --platform tvos` gives me:
>*** Cloning CocoaAsyncSocket
>*** Checking out CocoaAsyncSocket at "fe716222f72811e66de02809eae8db77dacb6a83"
>*** xcodebuild output can be found in /var/folders/px/xbchvngs2db1r26d_kwxdjzh0000gn/T/carthage-xcodebuild.CQavbe.log
>*** Skipped building CocoaAsyncSocket due to the error:
Dependency "CocoaAsyncSocket" has no shared framework schemes for any of the platforms: tvOS

>If you believe this to be an error, please file an issue with the maintainers at https://github.com/robbiehanson/CocoaAsyncSocket/issues/new

**Comment by chrisballinger** [comment]
This should be resolved, let me know if you're having any other issues
