### ISSUE TITLE
Feature Request: Always notify the client or server when the other disappears

### ISSUE THREAD

**Issue by taberrr** [robbiehanson/CocoaAsyncSocket#364]
I know this is probably "just how TCP/IP works" etc. (eg: http://www.scriptscoop.net/t/d5ab9ed1e385/ios-cocoaasyncsocket-not-giving-socket-disconnected-when-other-party-disco.html) but it looks like there is a fair amount of interest/confusion w/ how this works:

https://github.com/robbiehanson/CocoaAsyncSocket/issues/131, https://github.com/robbiehanson/CocoaAsyncSocket/issues/171, https://github.com/robbiehanson/CocoaAsyncSocket/issues/233, https://github.com/robbiehanson/CocoaAsyncSocket/issues/268

The basic issue is: your client is connected to your server and both are idle. If you force-close the server (or wi-fi dies, or anything else happens where the server goes away... or actually if the client disconnects too) the client (or server) gets stuck thinking it's still connected.

Apparently if you perform a read (or write?) the client will get notified via `socketDidDisconnect:withError:` but I tried sending a -1 timeout write to the socket as soon as it was connected, and never saw that delegate method called after queuing up a bunch of other messages. :(

So it looks like the general consensus is that we need to implement some sort of heartbeat packet that gets written every x seconds? (On the client _and_ server?)

**But** I think a major draw to using CocoaAsyncSocket, at least for me, because I'm super `lazy`, is that the framework makes everything easy for us. I would therefore like to suggest/plead that some sort of heartbeat implementation ships with the framework, behind the scenes (possibly through a reserved tag). 

I was using NSNetStreams before trying out CocoaAsyncSocket and that's how they seem to behave. If a connection—client or server— is dropped, the delegate is notified so they can react accordingly.
Thanks for listening, and thanks for CocoaAsyncSocket!

**Comment by janapejic** [comment]
Is there any chance this will even be implemented?

**Comment by scottcc** [comment]
Whelp, given that we're all up in 2018 now, this issue might not get the attention hoped for. Still looking into `XMPPPing` and `XMPPAutoPing` as a part of XEP-0199 which seems to ship with the framework.
