### ISSUE TITLE
How can I disable queue function 

### ISSUE THREAD

**Issue by wangbourne** [robbiehanson/CocoaAsyncSocket#366]
In my case
1. The server keep updating its status
2. The app send request every 2 seconds.

Current result is:
The app get response one by one. Old result comes first since its request is sent earliest.

My question is:
Is it possible to disable queuing? That is to say: once my app sends a request, it throws away all other old requests?

Thanks

**Comment by BigBlueMan19911109** [comment]
I haven't meet the question as you said.If your describe is a faction,i can't understand too.So expect you can get the answer early.
