### ISSUE TITLE
What are the licensing terms?

### ISSUE THREAD

**Issue by aryatr** [robbiehanson/CocoaAsyncSocket#368]
Good wrapper implementation for doing socket based functions. We would like to integrate with one of our commercial product and have searched about licensing terms in all the files but could not find any piece of information. Please clarify us.

**Comment by manavgabhawala** [comment]
It is in the public domain: https://en.wikipedia.org/wiki/Public_domain

**Comment by michaelklishin** [comment]
Not all jurisdictions recognise public domain IP. @robbiehanson please pick a reasonable license instead, e.g. Apache 2.0 or MIT.

**Comment by michaelklishin** [comment]
IANAL but if this repo doesn't provide a license, the terms [are the following](https://help.github.com/articles/open-source-licensing/#what-happens-if-i-dont-choose-a-license), which means nobody can redistribute it, or at least that's my reading of GitHub Help.

**Comment by albertodebortoli** [comment]
+1 Would be great to have a license file. Could you please pick one and update the repo @robbiehanson ?
