### ISSUE TITLE
Frameworks/CocoaAsyncSocket.framework/CocoaAsyncSocket' does not contain bitcode

### ISSUE THREAD

**Issue by mwharrison** [robbiehanson/CocoaAsyncSocket#370]
iTunes Connect is rejecting my app because CocoaAsyncSoccket does not contain bitcode. I've tried to compile it with Bitcode based on multiple stackexchange.com issues to no avail. Is there any solution to this?

**Comment by praveensharma** [comment]
Hi! Seconding this here. Tried to set the BITCODE_GENERATION flag and rebuild as per this issue on Carthage: https://github.com/Carthage/Carthage/issues/535 to no avail. Maybe there is an additional step?

**Comment by mwharrison** [comment]
I did finally get this to build with bitcode support, but now it doesn't work with the simulator. I think it's something about ARM7 vs x86-64, but I haven't quite figured it out. You can check out what I changed on my fork of the repo at https://github.com/mwharrison/CocoaAsyncSocket - and when I get it working I will submit a PR here.
Unfortunately, I was messing with settings so much I'm not sure which one actually worked - but I can currently run my project on the AppleTV, it just won't work in the simulator.

**Comment by praveensharma** [comment]
So apparently Carthage is supposed to fix this automatically but it still gives me errors on submission to Test Flight. I'm going to switch to cocoapods - apparently that fixes this issue.

**Comment by mwharrison** [comment]
Ay. I don't like how Cocoapods changes my project so much, but I guess that's my only option. Thanks.
