### ISSUE TITLE
How do I run the examples project?

### ISSUE THREAD

**Issue by takanashi-positive** [robbiehanson/CocoaAsyncSocket#375]
I openend "UdpEchoServer.xcodeproj", but a lot of files are missed . How do I run it? Did I opened wrong file or missed something?
Thank you very much!

**Comment by ExoticObjects** [comment]
Would love to know this as well.

**Comment by ExoticObjects** [comment]
In fact, almost none of the examples actually run out of the box. This project could use some maintenance!

**Comment by halmueller** [comment]
Pull requests are the sincerest form of flattery.

**Comment by ExoticObjects** [comment]
There's an awful lot of stuff to fix here.
