### ISSUE TITLE
ios9 CFSocketSetAddress listen failure: 102

### ISSUE THREAD

**Issue by allentofight** [robbiehanson/CocoaAsyncSocket#376]
when use AsyncUdpSocket,iOS 8 works well,but ios9 report the above 102 error

**Comment by janderberg** [comment]
I noticed this too. Comes from the CFSocketSetAddress call:
```objectivec
CFSocketError error = CFSocketSetAddress(theSocket4, (__bridge CFDataRef)address4);
```
But when I expect the return from this, error is 0. It looks like this isn't an actual error.

**Comment by Objc0** [comment]
When display this warning, we can still receive the UDP data.  
CFSocketSetAddress listen failure: 102
CFSocketError error = CFSocketSetAddress(theSocket4, (__bridge CFDataRef)address4);
and
error == kCFSocketSuccess

I did not find more information about this error : (

**Comment by dspw** [comment]
Using commit from Aug 12, 2015

I see this 102 warning also.  Only happens on iOS9.

Possibly related, also with iOS9 am getting - CFSocketSetAddress bind failure: 48 - when sending UDP message.  

The messages are still being sent and received ok.

**Comment by chenkaige** [comment]
Use Command Line Tool to create a server on Mac, I see this 102 warning, too.

**Comment by willonboy** [comment]
me too. somebody know why?
