### ISSUE TITLE
podspec repo is behind

### ISSUE THREAD

**Issue by rubyredrick** [robbiehanson/CocoaAsyncSocket#377]
I tried installing this for twos, and despite the fact that the podpec does indeed say twos is supported, when you try to install it you get:

Updating local specs repositories
Analyzing dependencies
[!] The platform of the target `Pods` (tvOS 9.0) is not compatible with `CocoaAsyncSocket (7.4.2)`, which does not support `tvos`.

I see that several have commented on this on the closed pull request which merged the tvos changes to the podspec.  I noticed that the platform badge on the main page for this repo only has iOS | OS X

I had the idea to change my podfile, and add the git tag:

pod 'CocoaAsyncSocket', :git => 'https://github.com/robbiehanson/CocoaAsyncSocket.git'

After doing this pod install works.

So it looks like the new podspec contents never got to the podspec repo, perhaps a variant on the forgot to git add before git commit?

**Comment by larsblumberg** [comment]
The latest release 7.4.2 does not support tvOS. It is made from commit @1685d1c8bb82ce2a42c551be4f2a7588b9590a38 (see https://github.com/robbiehanson/CocoaAsyncSocket/releases/tag/7.4.2).

Only _after_ that commit support for tvOS has been added, namely in commit @2b7990b4e8e4b81c893672a88e63fcb3ed6f006b

So we need to wait for the maintainers to release a new version of this pod and until then use @rubyredrick's workaround.

@chrisballinger can you please update us on when you plan the next release?
