### ISSUE TITLE
There are no Swift 2 examples

### ISSUE THREAD

**Issue by niekberenschot** [robbiehanson/CocoaAsyncSocket#378]
Can someone please make an swift example from: https://github.com/robbiehanson/CocoaAsyncSocket/blob/master/Examples/GCD/EchoServer/EchoServerAppDelegate.m

**Comment by indrajitsinh** [comment]
hey m also find example of swift 

if u find then let me know

**Comment by nickyhuyskens** [comment]
It's not the echo server example, but I made a cocoaasyncsocket tutorial combined with the bonjour service and sending objects instead of just strings.

http://swift2tutorials.blogspot.be/p/swift-2-cocoaasyncsocket-bonjour.html

I hope this will help
