### ISSUE TITLE
I can only connect host once

### ISSUE THREAD

**Issue by PeterHan1981** [robbiehanson/CocoaAsyncSocket#380]
Dear friends:
    As  title, When I connect the host once , it works perfect.  it can read , write,and so . But when I disconnect it , and reconnect it the second time, it disconnect automatic. my disconnect code is:
(void)myDisconnect
 {
     [self.mSocket setDelegate:nil delegateQueue:NULL]; 
     [self.mSocket disconnect]; 
     self.mSocket = nil;
 } 
When the second time I connect the same host, The GCDAsyncSocket's function named setupReadAndWriteSourcesForNewlyConnectedSocket in to socketFDBytesAvailable=0, so it calls [strongSelf doReadEOF]; and then automatic disconnect. So I can't connect the host.What happens?

**Comment by ryanstout** [comment]
@PeterHan1981 did you track this issue down?

**Comment by PeterHan1981** [comment]
Yeah, The issue is mine project. not GCDAsyncSocket.

**Comment by PeterHan1981** [comment]
@ryanstout  Yeah, The issue is mine project. not GCDAsyncSocket.
