### ISSUE TITLE
getaddrinfo() behavior under iOS9

### ISSUE THREAD

**Issue by esad** [robbiehanson/CocoaAsyncSocket#382]
It seems that `getaddrinfo()` behavior has changed in iOS9 in the way that the first call for an address fails immediately if it's not in the cache. This results in first connection attempt failing with an `kCFStreamErrorDomainNetDB` (code 8) error.

**Comment by deckikwok** [comment]
This isn't fix?

1. I have the same issue when I am establishing connection over p2p wifi and bt. wifi infra is working fine.

2. To validate that the second call works, I had to store the NSNetService I intend to connect to and reconnect on disconnection. On the second attempt, it does work.

3. On the first attempt, the didDisconnect delegate call returns a (null) socket. Not sure why this is the case.

Can someone advise on how I should proceed?
