### ISSUE TITLE
Cannot connect to IPV6 Socket

### ISSUE THREAD

**Issue by praveensharma** [robbiehanson/CocoaAsyncSocket#383]
Hey everyone! I successfully had GCDUDPAsyncSocket working but realized TCP was more appropriate for my use case. 

Unfortunately - I can never successfully connect with a bonjour published and discovered NSNetService. The service is discovered and the address is discovered as well. A connection attempt without failure happens but the connection is never secured. 

I can connect using "connectWithHost" and passing in the IP address assigned to my mac but this the only way i can get that ip is by hard coding it. Is there a way to obtain this IP through NSNetService?

I'm using swift, Xcode 7.1.1 and iOS 9.1. I am connecting between an iPhone and a Mac running an Apple TV Simulator. This works fine with UDP.

No matter what - the connection attempt times out even though an appropriate address is supplied!

    Socket is Disconnecting - Error Domain=NSPOSIXErrorDomain Code=60 "Operation timed out" UserInfo={NSLocalizedDescription=Operation timed out, NSLocalizedFailureReason=Error in connect() function}

Anyone run into this before? Here is my connection code:

    func connectToAddress(sender: NSNetService) {
        if let addresses = sender.addresses {
            for address in addresses {
                print(address)
            }
            
            self.serverAddresses = addresses
            var done = false
            
            while !done && (self.serverAddresses.count > 0) {
                let address = self.serverAddresses[0]
                self.socket = GCDAsyncSocket(delegate: self, delegateQueue: dispatch_get_main_queue())
                do {
                    try self.socket.connectToAddress(address)
                    done = true
                } catch {
                    print("Unable to Connect")
                }
            }
            
            if !done {
                print("Could Not Connect To Address")
            }
        }
    }

**Comment by Smeegol** [comment]
Why close this issue? What the answer?
