### ISSUE TITLE
GCDAsyncSocket - EXC_BAD_ACCESS crash

### ISSUE THREAD

**Issue by Rantaki** [robbiehanson/CocoaAsyncSocket#384]
Hi,

I've now been struggling with this for months and just cannot figure out what is going on. Can anyone help me? Even hearing that I'm not alone with this issue would be great because I have spend a lot of time to confirm that the crash is not due to my app using the lib incorrectly.

I couldn't figure out how to get the crash log out of the Xcode navigation pane so here is a screenshot of it. Thanks in advance!

![crash](https://cloud.githubusercontent.com/assets/16162066/11606268/f8df160c-9b23-11e5-9e25-0564997b193d.jpg)

Edit. 
At the time of crash (completeCurrentRead) it seems that all variables are null for some reason (these were cropped out of the pic by mistake).

self    GCDAsyncSocket \*    nil 
theRead GCDAsyncReadPacket \*    nil 
theDelegate id  0x0 
currentRead GCDAsyncReadPacket \*    nil 
delegateQueue   NSObject \*  nil 
delegate    id  0x0 

Edit2.
This is where the crash happens in completeCurrentRead:

```
if (delegateQueue && [theDelegate respondsToSelector:@selector(socket:didReadData:withTag:)])
    {
        GCDAsyncReadPacket *theRead = currentRead; // Ensure currentRead retained since result may not own buffer

        dispatch_async(delegateQueue, ^{ @autoreleasepool {

            [theDelegate socket:self didReadData:result withTag:theRead->tag];  // <<-- Crash line
        }});
    }
```

Does this mean that at the time delegateQueue executes the crash line pointed above, theDelegate variable is nill for some reason? Actually delegateQueue itself is nill too?

My app used to operate through a wrapper class to GCDAsyncSocket, but now I have removed it to make things even more simple but it still keeps crashing for the same issue. I also have GCDAsyncSocket object defined as strong and atomic. Just to rule out issue in my app, am I still missing something that could cause crash like this?

Edit3.

At the time crash happens, the last trace I can get is from the receive function ( (void)socket:(GCDAsyncSocket *)sender didReadData:(NSData *)data withTag:(long)tag ) and it shows that the length of the received data is way too long. The data should be 119-120 bytes always and when the crash happened it was 238. So it seems that two packets are received at once. What could cause this?

**Comment by Rantaki** [comment]
Workaround for the issue was to ignore the double size data instead of trying to process it. It's not optimal, and the root cause is still a mystery, but it does not crash anymore. There's a short gap in the received and processed data though.

As said, the data is always 119-120 bytes and it comes once per 3 seconds. At the time crash happened, there were nothing abnormal in timings i.e. the previous data was received 3 seconds ago, but suddenly the received data was double sized and in unexpected format. I have implemented the server side (sender) by myself and have double checked that it is not possible that it would send double size data.

Still would like to know where the additional data comes from.

**Comment by seanm** [comment]
Did you try using address sanitizer or valgrind or guard malloc?  They are all good for catching memory bugs.

**Comment by dharm1994** [comment]
@Rantaki did you find any solution for this issue?

**Comment by dharm1994** [comment]
@Rantaki did you find any solution for this issue?

**Comment by Rantaki** [comment]
No, sorry. Haven’t worked on this since.

**Comment by huolong1237** [comment]
Hello, have you solved this problem? I have the same problem. If it is solved, can you tell me how to solve it? Thank you

**Comment by Rantaki** [comment]
No, sorry! Haven’t worked with this for a while.

**Comment by qasimsqm** [comment]
I am also getting this Issue please suggest a solution
GCDAsyncSocket-CFStream (16): EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)


[currentRunLoop runMode:NSDefaultRunLoopMode beforeDate:[NSDate date]]

**Comment by dikshit38** [comment]
Hello,
I am facing the same issue. let me know if anyone have a solution for that.

Thanks in advance!
