### ISSUE TITLE
GCDAsyncSocket does not conform to a NSCopying protocol

### ISSUE THREAD

**Issue by pomozoff** [robbiehanson/CocoaAsyncSocket#387]
And It is a huge problem.
There are many places where a **socket** is an identificator for the most processes in the framework.
For example I have to know which socket did fail to connect, and since the framework uses delegate oriented paradigm only, I have to store a completion block somewhere in my subclass.
But I can't use **socket** from a delegate method as a key in a dictionary. I have to generate a string from the socket and use it.
I think it should be a default feature of the framework, doesn't it?

**Comment by mattcomi** [comment]
If storing it in a dictionary is the issue, why not wrap it in an `NSValue`:

    NSValue* key = [NSValue valueWithNonretainedObject:yourSocket];

**Comment by pomozoff** [comment]
I'll try it later, thanks.
