### ISSUE TITLE
kCFStreamNetworkServiceTypeVoIP is deprecated in iOS 9 warning

### ISSUE THREAD

**Issue by md0u80c9** [robbiehanson/CocoaAsyncSocket#402]
Hi,

I notice when compiling this in my code that I'm getting a warning that the above constant is deprecated in iOS 9. Would anyone happen to have code which uses PushKit in place of this, as the warning suggests?

**Comment by imiko** [comment]
Hello,

Solved by @pengyanb [https://github.com/robbiehanson/CocoaAsyncSocket/issues/361](url)

> Add **#import** to GCDAsyncSocket.m
`#import <PushKit/PushKit.h>`

> Replace in **enableBackgroundingOnSocketWithCaveat**
`r1 = CFReadStreamSetProperty(readStream, kCFStreamNetworkServiceType, PKPushTypeVoIP);
r2 = CFWriteStreamSetProperty(writeStream, kCFStreamNetworkServiceType, PKPushTypeVoIP);`
