### ISSUE TITLE
CocoaAsyncSocket.h not found

### ISSUE THREAD

**Issue by soleilpqd** [robbiehanson/CocoaAsyncSocket#406]
I just re 'pod install' and CocoaAsyncSocket is upgraded from 7.4.2 to 7.4.3. But when build my project, it failed by "CocoaAsyncSocket.h not found.". I can't find CocoaAsyncSocket.h in Pods project too.

**Comment by aicpp** [comment]
I have same issue.
I fix it by replace
`#import "CocoaAsyncSocket.h"`
on
`#import "GCDAsyncSocket.h"`

**Comment by davidchiles** [comment]
Or use `@import CocoaAsyncSocket;` to import the module.

**Comment by yuan8787** [comment]
@aicpp 's workaround worked for me. You just have to import the individual modules:

```
#import "GCDAsyncSocket.h"
#import "GCDAsyncUdpSocket.h"
... etc.
```

**Comment by chrisballinger** [comment]
The change was made because the umbrella header should never have been included in the first place because it causes a problem when it's included as a framework module. Apologies for breaking your build on a non-major version bump.

I'll update the README.

See this issue: https://github.com/CocoaPods/CocoaPods/issues/4903

**Comment by startry** [comment]
Have you tried to solve [CocoaPods/CocoaPods#4903](https://github.com/CocoaPods/CocoaPods/issues/4903) by any other way to keep umbrella header? 
e.g. Specified a custom module map

**Comment by chrisballinger** [comment]
That could be an option but I haven't gotten around to it yet. We'd need to also remove the GCD/RunLoop subspecs that were just added.

**Comment by soleilpqd** [comment]
Thank everyone,

I use CocoaAsyncSocket in my private Pod lib, so for now I use 7.4.2 & update my Pod later.
