### ISSUE TITLE
Swift test doesn't seem to work

### ISSUE THREAD

**Issue by iain17** [robbiehanson/CocoaAsyncSocket#415]
The code below is the recently added swift test. After trying to implement this library in my swift project I found this swift test but when ran it just doesn't seem to function either.
# https://github.com/robbiehanson/CocoaAsyncSocket/blob/master/Tests/Shared/SwiftTests.swift
Never log for example doesn't seem: to be called.
print("didAcceptNewSocket %@ %@", sock, newSocket)

import Foundation
import CocoaAsyncSocket

class Server: NSObject, GCDAsyncSocketDelegate {
    
    let kTestPort: UInt16 = 30301
    
    var clientSocket: GCDAsyncSocket?
    var serverSocket: GCDAsyncSocket?
    var acceptedServerSocket: GCDAsyncSocket?
    
    func setUp() {
        // Put setup code here. This method is called before the invocation of each test method in the class.
        clientSocket = GCDAsyncSocket(delegate: self, delegateQueue: dispatch_get_main_queue())
        serverSocket = GCDAsyncSocket(delegate: self, delegateQueue: dispatch_get_main_queue())
        print("Set up!")
    }
    
    func tearDown() {
        // Put teardown code here. This method is called after the invocation of each test method in the class.
        clientSocket?.disconnect()
        serverSocket?.disconnect()
        acceptedServerSocket?.disconnect()
        clientSocket = nil
        serverSocket = nil
        acceptedServerSocket = nil
    }
    
    func testFullConnection() {
        // This is an example of a functional test case.
        // Use XCTAssert and related functions to verify your tests produce the correct results.
        do {
            try serverSocket?.acceptOnPort(kTestPort)
        } catch {
            print("\(error)")
        }
        do {
            try clientSocket?.connectToHost("127.0.0.1", onPort: kTestPort)
        } catch {
            print("\(error)")
        }
        print("Done")
    }
    
    
    //MARK:- GCDAsyncSocketDelegate
    @objc func socket(sock: GCDAsyncSocket!, didAcceptNewSocket newSocket: GCDAsyncSocket!) {
        print("didAcceptNewSocket %@ %@", sock, newSocket)
        acceptedServerSocket = newSocket
    }
    
    @objc func socket(sock: GCDAsyncSocket!, didConnectToHost host: String!, port: UInt16) {
        print("didConnectToHost %@ %@ %d", sock, host, port);
    }
    
    
}

Does the swift implementation even work with both a server and client instance?
I even tried adding a reference to NSObject seeing many do so, however the original written test doesn't do this. I'd love to hear any hints on how to get this working.

**Comment by iain17** [comment]
Figured it out. Problem probably was me initializing the class in the appDelegate. The moment I moved it into a viewController it worked.

**Comment by houqinghui** [comment]
ok

在 2016-04-16 20:41:30，"iain17" <notifications@github.com> 写道：


Closed #415.
