### ISSUE TITLE
data received in 2 parts : first 8 chars of string then rest of data string

### ISSUE THREAD

**Issue by stan69b** [robbiehanson/CocoaAsyncSocket#419]
When sending a message to a bonjour client using GCDAsyncSocket, the client's didReadData function is triggered twice, first one with 8 first chars of the message, then a second one with the rest of the message.

**Comment by jrwm** [comment]
Learn more about it in [Wiki ](https://github.com/robbiehanson/CocoaAsyncSocket/wiki/CommonPitfalls)

**Comment by RegisStGelais** [comment]
If your packets end with a unic separator you can use readDataToData
