### ISSUE TITLE
Address already in use

### ISSUE THREAD

**Issue by SYLing** [robbiehanson/CocoaAsyncSocket#422]
binding Error Domain=NSPOSIXErrorDomain Code=48 "Address already in use"

**Comment by iShawnWang** [comment]
Same issue here, I close udpSocket when app enter background, and set it to nil; Reopen it when app enter foreground ~ And I got above error

**Comment by mattbornski** [comment]
@iShawnWang @SYLing have you tried `enableReusePort` before `bind` ?

**Comment by quhaoran007** [comment]
Hi mattbornski, please follow up this. This issue happens very often to my app when another app is also using UDP and being kill by OS in the background(you can see from the multi-task screen). I think somehow OS wakes up the other app and that app binds the port, so my app using this library can't bind the port.  Have used "enableReusePort", but it didn't help.

**Comment by mvnrc** [comment]
The problem is that you are trying to call **accept()** while the server is being disconnected! One workaround for this issue is to use a **DispatchSemaphore** and _wait_ until the server is disconnected. Then you _signal_ the semaphore and let the server to recall the accept() method. 

Let me know if you need more info or a piece of code or something...

**Comment by mvnrc** [comment]
The reason is that you are trying to call accept() while either the port is already open or the server is being disconnected. One workaround is to use a **DispatchSemaphore**, then _wait()_ and try to disconnect before each accept() and then _signal()_ as soon as the server is disconnected.

**Comment by mangeshsambare** [comment]
I have same issue

**Comment by mvnrc** [comment]
I managed to fix it by making sure that there is only one instance of the server. The fastest workaround is to make your tcp server Singleton.
