### ISSUE TITLE
Had to move subdirectories around for Examples to compile

### ISSUE THREAD

**Issue by slcott** [robbiehanson/CocoaAsyncSocket#424]
I am just testing out the library now. I had to move `Vendor` up a directory and `Source/GCD/` contents to the `Examples/` directory to get BonjourClient to compile. Can you check that each of the examples in `Examples/` compile "out of the box" after doing a simple git clone of your project?

**Comment by chrisballinger** [comment]
Feel free to submit a pull request and including a build check to the
.travis.yml
