### ISSUE TITLE
hello i need help

### ISSUE THREAD

**Issue by am1993421** [robbiehanson/CocoaAsyncSocket#427]
when my app into the background after a certain period of time,Into the front desk again,app have crash,this is log:
Application received signal SIGSEGV
(null) -[AsyncSocket doStreamOpen] + 248
How can I solve this problem? thx

**Comment by jeeftor** [comment]
You cant keep sockets open in the background easily.  You need to do some funky stuff as registering as a VOIP app - and then i've been unable since ios7 to keep my UPD sockets open.

**Comment by am1993421** [comment]
yeah, VOIP is  a solution.but use VOIP must have a function in the app.Otherwise the apple audit not through.so into the background disconnect the socket,into foreground reconnect the socket
