### ISSUE TITLE
IPv4 as a default transport fails without IPv4

### ISSUE THREAD

**Issue by sdstrowes** [robbiehanson/CocoaAsyncSocket#431]
These lines describe a bug:
https://github.com/robbiehanson/CocoaAsyncSocket/blob/562bae6af6dbd7e1891293dae20b9f79a2fd7228/Source/GCD/GCDAsyncSocket.h#L114-L118

If both IPv6 and IPv4 addresses are returned by DNS, IPv6 should be chosen first. [rfc3484](https://tools.ietf.org/html/rfc3484) says more.

We bumped into this bug when testing apps for [Apple's IPv6 compliance](https://developer.apple.com/news/?id=05042016a). Apps were receiving IPv6 addresses, but the default meant this code attempted to use the IPv4 results instead.

Obviously the workaround is clear, but the most reliable solution will be to correct the connection logic in here.

**Comment by chrisballinger** [comment]
This may help but it needs to be improved further for raw IPv4 addresses: https://github.com/robbiehanson/CocoaAsyncSocket/pull/430

**Comment by sdstrowes** [comment]
Couple of quick comments:
- Does this fix the default from v4 to v6? [rfc3484](https://tools.ietf.org/html/rfc3484) should guide the address selection.
- I think you've set the failover pace to 500ms. You can probably shoot for something lower, perhaps 100ms-200ms.
- To meet that delay, this should only have to handle the situation where a connect() is attempted and packets are blackholed somewhere, which is rare. In the case that v4 or v6 fails fast at the device, do these changes still help protocol selection? Without v4 connectivity, the current default is to retry a v4 address forever even if a v6 address is available.

**Comment by chrisballinger** [comment]
It looks like it should if you also set preferIPv6. I haven't tested the PR myself, so I'm not sure about the other stuff.

**Comment by keab42** [comment]
Any update on this as Apple is now enforcing the v6 compliance?
