### ISSUE TITLE
Udp socket can not broadcast message in some cases.

### ISSUE THREAD

**Issue by hxbtec** [robbiehanson/CocoaAsyncSocket#436]
I found that the udpasyncsocket can't broadcast message (the dst host is 255.255.255.255) when the phone's personal hotspot had been connected by someone else. And then the delegate method udpSocketDidClose: withError: would be called back.And the error description that : Error Domain=NSPOSIXErrorDomain Code=49 "Can't assign requested address" UserInfo={NSLocalizedDescription=Can't assign requested address, NSLocalizedFailureReason=Error in send() function.}.Any one can give some advice?Big thanks.

**Comment by hxbtec** [comment]
I also found this problem in a NAT64 network (ipv6-only)environment.In a NAT64 network ,this problem will happened when the phone's mobile data was on.If I turn off mobile data it works well.I was very confused about it.How can I solve this problem?

**Comment by newacct** [comment]
The error 49 is caused by getaddrinfo() incorrectly returning ports of 0, and you cannot send to port 0 (see #429). You said in your comment on that issue that after you fix that problem the error does not occur anymore and you have another problem. So the error is not your real problem. Please describe what your problem is after fixing the error. Also please show your code.

**Comment by hxbtec** [comment]
@newacct Thank you for your answer，Unfortunately this error still happened when the phone's mobile data was on with a NAT64 network environment or the phone's personal hotspot had been connected by someone else.
My code:
init method:
<img width="724" alt="2016-05-31 9 12 38" src="https://cloud.githubusercontent.com/assets/19263507/15660496/e2a3ec8c-270f-11e6-9c71-f7ca0b2bca7c.png">
broadcast method:
<img width="728" alt="2016-05-31 9 09 12" src="https://cloud.githubusercontent.com/assets/19263507/15660463/7225cdb8-270f-11e6-9ab2-226ae87c3bda.png">
delegate method:
<img width="718" alt="2016-05-31 9 06 01" src="https://cloud.githubusercontent.com/assets/19263507/15660429/020bef58-270f-11e6-8fda-ccd4d80446cf.png">

When I broadcast online message ,the delegate method in the picture 3 never be called In the above two cases.
I know that the ipv6 do not support broadcast,so I tried the multi broadcast.In this case(multi broadcast) this error didn't occurred ,but the delegate method still got nothing. 
I am not sure if there are some wrong with my code.
Wish you can give me some advice.
Thanks.
