### ISSUE TITLE
It's not possible for me to use it for broadcast

### ISSUE THREAD

**Issue by horhe17** [robbiehanson/CocoaAsyncSocket#44]
Hi Robbie!!
<b>Updated:</b>  My speciefic task, i don't know my custom device IP, so i need to send both broadast and normal request to one port, so i can't open 2 of them as i understand, how to deal with it?

I've tried to make 2 sockets - 1 for broadcast and other for communication but it also fails, i don't know why but broadcast works only when i initialize it once with  this code, then I'm closing socket and only after another initialization it works. How to deal with this? How to send broadcast? Do i need to use 2 sockets or 1? Thank u very much, i can't do this for 3 days ...
Everything else works perfectly i can send and receive with no problem.

udpSocket = [[GCDAsyncUdpSocket alloc] initWithDelegate:self delegateQueue:dispatch_get_main_queue()];

```
NSError *error = nil;

[udpSocket setIPv4Enabled:YES];
[udpSocket setIPv6Enabled:NO];
  [udpSocket enableBroadcast:YES error:&error];

   if (![udpSocket  bindToPort:30303 error:&error])  { NSLog(@"Error starting server (bind): %@", error); return;    }

if (![udpSocket beginReceiving:&error])
{ [udpSocket close];
    NSLog(@"Error starting server (recv): %@", error);  return;
}

NSLog(@"Udp Echo server started on port %hu", [udpSocket localPort]);
isRunning = YES;
// --------------------

NSData* datatosend=[UDPString dataUsingEncoding:NSUTF8StringEncoding];
NSString* mysubnet= [[NSString alloc] initWithFormat: @"%i.%i.%i.255", myip1,myip2,myip3];

[udpSocket sendData:datatosend toHost:mysubnet port:port withTimeout:-1 tag:0];
```

**Comment by stevek4444** [comment]
Hi fstanley,

I am having a problem.  When I try to use GCDAsyncUdpSocket via the simple code you provided above on April 11, 2012 to broadcast I keep getting a socket close error indicating that the network can't be reached.

Am I missing some setup code not shown?

**Comment by kingctan** [comment]
Error in send() function.   when use multicast in ios version higher than 12.3.
