### ISSUE TITLE
How to get all data from socketServer?

### ISSUE THREAD

**Issue by WangYuren** [robbiehanson/CocoaAsyncSocket#441]
today,I use the GCDAysyncSocket in my project,but i met question. i want get all data by delegate method didReadData:.
for example, the server feedback data bytes 19947, first 4 bytes is flag, another data i need. but i get the data bytes 1448, don't get another data. I find the get all data need some time and some method get data in memory.please give me some suggests,thanks.

**Comment by quarktimes** [comment]
do you solve it？

**Comment by WangYuren** [comment]
never solve it. I'm crazy....
