### ISSUE TITLE
I'm writing a basic command line (UDP) server/listener in swift using Xcode. #GCDAsyncUdpSocket doesnt call any of my delegates. Also I believe beginReceiving is suupose to be recursive but it doesnt seem to call itself.

### ISSUE THREAD

**Issue by nihalpasham** [robbiehanson/CocoaAsyncSocket#442]
This is my very first program in Swift. I'm writing a basic command line (UDP) server/listener in swift using Xcode. I'm able to send data i.e. a string with characters 'testing' via the "sendData" call (verified through wireshark). However I can't seem to invoke any of the delegate callbacks. For "sendData", I've checked the implementation within #GCDAsyncUdpSocket's main file and I see that none of the delegates are called unless we see a particular error (resolve error) - in which case the "didNOTSendDataWithTag" is called.

But if "beginReceiving" is called, it does NOT invoke "didReceiveData" callback. I cant seem to figure out why. Also "beginReceiving is suppose to be recursive (Calls itself forever I assume) according to its implementation. But my program exits quickly without any errors. Any help will be really appreciated.

     import Cocoa
     import CocoaAsyncSocket

    class udpListener : GCDAsyncUdpSocketDelegate {

    var udpSock : GCDAsyncUdpSocket!
    let listenPort : UInt16 = 14000
    let data = "testing".dataUsingEncoding(NSUTF8StringEncoding)
    let toAddress = "127.0.0.1"
    let connectPort : UInt16 = 14001

    init () {

              udpSock = GCDAsyncUdpSocket(delegate: self, delegateQueue: dispatch_get_main_queue())

              do {

                          try udpSock!.bindToPort(listenPort, interface: "lo0")  // Swift automatically translates Objective-C methods that produce
                                                  // errors into methods that throw an error according to Swift’s native error  handling functionality.
               }
                   catch _ as NSError {
                   print("Issue with binding to Port")
                   return }
              }

             func sendData() {

             udpSock!.sendData(data, toHost: toAddress, port: connectPort, withTimeout: -1, tag: 0)
             }

             func readData() {

             do {

                       try udpSock!.beginReceiving()
             }

                        catch _ as NSError {
                               print("Issue with receciving data")
                               return }
             }

            //    Delegate CallBacks

           @objc  func udpSocket(sock: GCDAsyncUdpSocket!, didReceiveData data: NSData!, fromAddress address: NSData!, withFilterContext filterContext: AnyObject!) {

            let str = NSString(data: data!, encoding: NSUTF8StringEncoding)
            print(str)
           }

           @objc  func udpSocket(sock: GCDAsyncUdpSocket!, didSendDataWithTag tag: Int) {

           print("didSendDataWithTag")
           }

          @objc  func udpSocket(sock: GCDAsyncUdpSocket!, didNotSendDataWithTag tag: Int, dueToError  error: NSError!) {

          print("didNOTSendDataWithTag")
          }

          @objc  func udpSocket(sock: GCDAsyncUdpSocket!, didNotConnect error: NSError!) {

          print("didNOTConnect")
          }

         @objc  func udpSocketDidClose(sock: GCDAsyncUdpSocket!, withError error: NSError!) {
          print("DidCloseSocket")
          }

         @objc  func udpSocket(sock: GCDAsyncUdpSocket!, didConnectToAddress address: NSData!) {

          print("didConnectToAddress")

          }

**Comment by nihalpasham** [comment]
I'm instantiating an instance of the class from the main swift file and calling its methods in this order. Is this correct or am I missing something here

import Foundation

          var dnsListener = udpListener()
                  
                  for index in 1...5 { dnsListener.sendData() }
                  dnsListener.readData()

**Comment by chrisballinger** [comment]
You need to retain the object, it is likely being deallocated once it is no longer in scope. Make dnsListener an ivar in your class to retain it.
