### ISSUE TITLE
Why I always receive socketDidDisconnect after didAcceptNewSocket

### ISSUE THREAD

**Issue by oyljerry** [robbiehanson/CocoaAsyncSocket#444]
Hi All:
I have using CocoaAsyncSocket with swift in iOS, I implemented below functions. 

```
var socket: GCDAsyncSocket!
func socket(sock: GCDAsyncSocket!, didAcceptNewSocket newSocket: GCDAsyncSocket!) {

        print("Did accept new socket")
        self.socket = newSocket
        self.socket.readDataToLength(UInt(sizeof(UInt64)), withTimeout: -1.0, tag: 0)
        self.delegate.connectedTo(newSocket)
    }

    func socketDidDisconnect(sock: GCDAsyncSocket!, withError err: NSError!) {
        print("socket did disconnect: error \(err)")
        if self.socket == socket {
            self.delegate.disconnected()
        }
    }

```

I running another App on Mac, which will connect to iOS App, when connect to it. **didAcceptNewSocket** will be triggered, I will use variable socket to save newSocket, but after I run out of didAcceptNewSocket, I will receive **socketDidDisconnect** immediately (print **"socket did disconnect: error nil"**), and I trace it. socketDidDisconnect is called by dealloc in GCDAsyncSocket.m

```
- (void)dealloc
{
    LogInfo(@"%@ - %@ (start)", THIS_METHOD, self);

    // Set dealloc flag.
    // This is used by closeWithError to ensure we don't accidentally retain ourself.
    flags |= kDealloc;

    if (dispatch_get_specific(IsOnSocketQueueOrTargetQueueKey))
    {
        [self closeWithError:nil];
    }
    else
    {
        dispatch_sync(socketQueue, ^{
            [self closeWithError:nil];
        });
    }
    .....
}
```

Why dealloc is called, I use variable socket, it is strong reference in swift and it should not be released. If any comments, Please tell me. Thanks~

**Comment by leebeet** [comment]
save situation here

**Comment by slashlos** [comment]
Same situation here; was following along Bonjour game tutorial: https://code.tutsplus.com/tutorials/creating-a-game-with-bonjour-client-and-server-setup--mobile-16233; it's a few years old(?) but appears it should work (xcode 8.1, iPhone 5 sim) in Sierra

**Comment by ajaysinghthakur** [comment]
same problem here.
would like to see full working tcp example

**Comment by emreExtendas** [comment]
Same problem still here... Anyone found a solution for this..?

**Comment by vitovalov** [comment]
same :(

**Comment by Guru7373** [comment]
Did someone find solution for this ?
