### ISSUE TITLE
Exception Type:  SIGSEGV  in [GCDAsyncUdpSocket  resumeReceive6Source]

### ISSUE THREAD

**Issue by gemilar** [robbiehanson/CocoaAsyncSocket#447]
- (void)applicationWillEnterForeground:(NSNotification *)notification
  {
  LogTrace();
  
  // If the application was backgrounded, then iOS may have shut down our sockets.
  // So we take a quick look to see if any of them received an EOF.
  
  dispatch_block_t block = ^{ @autoreleasepool {
  
  ```
  [self resumeReceive4Source];
  [self resumeReceive6Source];
  ```
  
  }};
  
  if (dispatch_get_specific(IsOnSocketQueueOrTargetQueueKey))
      block();
  else
      dispatch_async(socketQueue, block);
  }
  app crash at    [self resumeReceive6Source];

device: iPhone6/6plus  OS:8.3 /8.4

**Comment by wwy19841007** [comment]
I also encountered this problem. Help!!!
