### ISSUE TITLE
IPv6 tcp socket connect issue

### ISSUE THREAD

**Issue by raistlin969** [robbiehanson/CocoaAsyncSocket#448]
I have pulled the latest code and so far I have been able to do everything with ipv6 except a connect to. When stepping through the code it is the connect method that is declared in the system file socket.h that fails. Line 2631 in GCDAsyncSocket.m.  I have gotten error code 1, 2, and 3 so far
. 
If I do a connect to localhost, or to ::1, things will work. But if I put my actual ip address in, it does not.  I can open up a socket on ipv6 only and someone running our java client can connect on ipv6. 
So it seems that putting in an actual ipv6 address in the connectToHost:onPort: is the only thing that I have not been able to get to work. 
I have set the sockets to preferIpv6, and also actually turned ipv4 off on them.
Any thoughts?

**Comment by raistlin969** [comment]
After a little more testing I was able to get the connect to work. I had to append the interface, %en0, to the end of the ipv6 address. Using the alternate method connectToHost:onPort:viaIntertface by itself with out appending the interface to the address string does not seem to work.

**Comment by shoon** [comment]
Great find! We were having the same issue this past week

Very odd that it works on localhost without the interface

**Comment by chrisballinger** [comment]
Is this new as of the latest build? Perhaps there is a regression...

**Comment by raistlin969** [comment]
I do not know if it is new or not. I pulled from master on Monday as we had a need to move all of our UDP and TCP to IPv6.

**Comment by shoon** [comment]
We're on master as well

**Comment by chrisballinger** [comment]
@shoon Is this a regression for you? There were some changes regarding IPv6 but I don't see how they could have caused this. To track this down we'll need to figure out the last commit where it worked and then go from there.

**Comment by ashishgupta301** [comment]
IPV6 problem resolved but code not work for IPV4.

I'm betting that the DNS lookup is returning IPv4 and IPv6 and the system tries to connect to IPv6 first and fails.
solution?
