### ISSUE TITLE
CocoaAsyncSocket/AsyncSocket.h file not found

### ISSUE THREAD

**Issue by Bjqrn88** [robbiehanson/CocoaAsyncSocket#450]
I have just re "pod install". 

and now i get the this error: "CocoaAsyncSocket/AsyncSocket.h file not found" in CocoaAsyncSocket.h

please help
![screen shot 2016-07-14 at 16 15 01](https://cloud.githubusercontent.com/assets/3627070/16842581/3f502996-49de-11e6-960b-cb339ae801b9.png)

Best regards

**Comment by chrisballinger** [comment]
The RunLoop version is deprecated. Please migrate to the GCD version.
