### ISSUE TITLE
Crash on jailbreaken device (work in previous versions)

### ISSUE THREAD

**Issue by sarsonj** [robbiehanson/CocoaAsyncSocket#460]
Hi,

we just put newest CocoaAsyncSocket to our app to support NAT64 requirement. Everything works for normal customers, however those with jailbreaken devices have problems, app crashes on CocoaAsyncCode.

It happens when calling `didConnect` method of delegate in `- (BOOL)connectWithAddress4:(NSData *)address4 address6:(NSData *)address6 error:(NSError **)errPtr` method:

``` objective-c
dispatch_queue_t globalConcurrentQueue = dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0);
dispatch_async(globalConcurrentQueue, ^{
#pragma clang diagnostic push
#pragma clang diagnostic warning "-Wimplicit-retain-self"

int result = connect(socketFD, (const struct sockaddr *)[address bytes], (socklen_t)[address length]);

__strong GCDAsyncSocket *strongSelf = weakSelf;
if (strongSelf == nil) return_from_block;

if (result == 0)
{
    dispatch_async(strongSelf->socketQueue, ^{ @autoreleasepool {

        [strongSelf didConnect:aStateIndex]; // CRASHES HERE
    }});
}
else
{
    NSError *error = [strongSelf errnoErrorWithReason:@"Error in connect() function"];

    dispatch_async(strongSelf->socketQueue, ^{ @autoreleasepool {

        [strongSelf didNotConnect:aStateIndex error:error];
    }});
}
```

I also attaching screenshot from crashlytics.
<img width="755" alt="crashjb" src="https://cloud.githubusercontent.com/assets/925756/17358606/163eed3c-5963-11e6-9ca1-7cceb93e2ebc.png">

Although this is not top priority to support JB customers, I would like to fix this, because it worked them before. Any ideas where the problem is?

**Comment by zhangdan** [comment]
yes, my app also meet this problem !!

**Comment by zhangdan** [comment]
Crashed: com.apple.root.default-qos
0  xCon.dylib                     0x10124bc38 fF8FCFBFD3DF9468292CD5E259A927B3B(bool, int, sockaddr const*, unsigned int) + 52
1  xCon.dylib                     0x10124bbf8 P131D7C4B7C0944DDB410F21F051B8A3A(int, sockaddr const*, unsigned int) + 52
2  X1                             0x1002baa94 __51-[GCDAsyncSocket connectSocket:address:stateIndex:]_block_invoke (GCDAsyncSocket.m:2631)
3  libdispatch.dylib              0x183a314bc _dispatch_call_block_and_release + 24
4  libdispatch.dylib              0x183a3147c _dispatch_client_callout + 16
5  libdispatch.dylib              0x183a3f914 _dispatch_root_queue_drain + 2140
6  libdispatch.dylib              0x183a3f0b0 _dispatch_worker_thread3 + 112
7  libsystem_pthread.dylib        0x183c49470 _pthread_wqthread + 1092
8  libsystem_pthread.dylib        0x183c49020 start_wqthread + 4

**Comment by tomjoy1947** [comment]
Same problem! [crashes](http://crashes.to/s/8ebeec94ee5)

**Comment by vox-humana** [comment]
It breaks somewhere inside anti-jailbreak detection tool called [xCon](https://www.theiphonewiki.com/wiki/XCon). Its code is closed, so if someone has access to it or has ideas about what is going on here, you are welcome.
