### ISSUE TITLE
The solution for issue #147 is NOT in version 7.4.3 and 7.5.0

### ISSUE THREAD

**Issue by funnel20** [robbiehanson/CocoaAsyncSocket#464]
Can you please incorporate the fix for #147 again, so Xcode Analyzer won't show a warning?

**Comment by chrisballinger** [comment]
Please submit PR

**Comment by funnel20** [comment]
It's already solved in commit 446, which is not released yet.
See: https://github.com/robbiehanson/CocoaAsyncSocket/commit/071109901100334ad54ae704b4c644b6bb89ad21

**Comment by funnel20** [comment]
This is now released as version 7.5.1. 
The Xcode Analyser warning is not shown anymore.
Item can be closed.
