### ISSUE TITLE
Can't work on my iphone4 device.

### ISSUE THREAD

**Issue by yoriWang** [robbiehanson/CocoaAsyncSocket#465]
I was used the AsyncSocket and GDCAsyncSocket in my project, but when I sending message to server and can't get feedback from server. the delegate through write method `- (void)onSocket:(AsyncSocket *)sock didWriteDataWithTag:(long)tag`，but never through read method`- (void)onSocket:(AsyncSocket *)sock didReadData:(NSData *)data withTag:(long)tag`. I was used `[_socket readDataWithTimeout:-1 tag:tag];` in write method, I couldn't found any issues, please help me, thanks so much. @robbiehanson  @chrisballinger

**Comment by jellychen** [comment]
me too!!!!
