### ISSUE TITLE
what is the reason that dispatch_get_specific function obtain socketQueue?

### ISSUE THREAD

**Issue by holyhan** [robbiehanson/CocoaAsyncSocket#471]
Hi, I read this source code which 'IsOnSocketQueueOrTargetQueueKey' marked the socketQueue. I want to know what is the significance of this design.

**Comment by chrisballinger** [comment]
Operations are performed on a single queue to maintain thread safety. When invoking certain methods they will check if we're on the current queue, and if so just do the regular function call, if not it will dispatch_sync onto the socket queue.
