### ISSUE TITLE
Error Domain=NSPOSIXErrorDomain Code=53

### ISSUE THREAD

**Issue by Sunny-hao** [robbiehanson/CocoaAsyncSocket#472]
Error Domain=NSPOSIXErrorDomain Code=53 "Software caused connection abort" UserInfo={NSLocalizedDescription=Software caused connection abort, NSLocalizedFailureReason=Error in connect() function}   

****I need your help , thank you in advance****

**Comment by systemid12** [comment]
Hi @Sunny-hao,

Did you figure this out? I'm having the same issue when connected on an IPv6 network.

**Comment by msanilkumar2020** [comment]
Any update on this issue, even i am facing same issue. unable to connect to IPV6 network via interface.

**Comment by codeslubber** [comment]
me too
