### ISSUE TITLE
Some bugs

### ISSUE THREAD

**Issue by SweatingEgg** [robbiehanson/CocoaAsyncSocket#473]
1. Line 1953-1958 in GCDAsyncSocket.m
   `int result = fcntl(childSocketFD, F_SETFL, O_NONBLOCK);
   if (result == -1)
   {
       LogWarn(@"Error enabling non-blocking IO on accepted socket (fcntl)");
       return NO;
   }`
   should be
   `int result = fcntl(childSocketFD, F_SETFL, O_NONBLOCK);
   if (result == -1)
   {
       LogWarn(@"Error enabling non-blocking IO on accepted socket (fcntl)");
       close(childSocketFD);
       return NO;
   }`
2. Line 2020-2023 in GCDAsyncSocket.m
   `   }
   
   return YES;
   }`
   should be
   `       return YES;
   }
   
   LogWarn(@"Delegate queue is not set");
   close(childSocketFD);
   return NO;
   }`
3. Line 2598-2603 in GCDAsyncSocket.m
   `    if (![self bindSocket:socketFD toInterface:connectInterface error:errPtr])
   {
       [self closeSocket:socketFD];
   
   ```
   return SOCKET_NULL;
   ```
   
   }`
   should be
   `    if (![self bindSocket:socketFD toInterface:connectInterface error:errPtr])
   {
       close(socketFD);
   
   ```
   return SOCKET_NULL;
   ```
   
   }`
4. In some methods implementations, method prototype ends with ';'. It would be good to match coding style. For example,
   `- (BOOL)acceptOnUrl:(NSURL *)url error:(NSError **)errPtr**;**
   {
   LogTrace();`

**Comment by SweatingEgg** [comment]
Regarding about the #4 issue, you can find those methods with VI(M) by find pattern with "^-.*;".

**Comment by SweatingEgg** [comment]
5. Line 1562-1566 in GCDAsyncSocket.m
`				if (socket4FD != SOCKET_NULL)
				{
					LogVerbose(@"close(socket4FD)");
					close(socket4FD);
}`
should be
`				if (socket4FD != SOCKET_NULL)
				{
					LogVerbose(@"close(socket4FD)");
					close(socket4FD);
					socket4FD = SOCKET_NULL;
}`

**Comment by chrisballinger** [comment]
It's hard to tell what's going on because of the formatting, but I believe you're incorrect for at least # 3

**Comment by SweatingEgg** [comment]
socket4FD or socket6FD is SOCKET_NULL during execution of createSocket:connectInterface:errPtr, but socketFD have a value rather than SOCKET_NULL. Then the following code in closeSocket: does nothing for socketFD.

    if (socketFD != SOCKET_NULL &&
        (socketFD == socket6FD || socketFD == socket4FD))
    {
        close(socketFD);
        
        if (socketFD == socket4FD)
        {
            LogVerbose(@"close(socket4FD)");
            socket4FD = SOCKET_NULL;
        }
        else if (socketFD == socket6FD)
        {
            LogVerbose(@"close(socket6FD)");
            socket6FD = SOCKET_NULL;
        }
    }

**Comment by SweatingEgg** [comment]
Regarding #4, I have found some had filed a pull request: https://github.com/robbiehanson/CocoaAsyncSocket/pull/369. Then forget about it.

**Comment by JosephPecoraro** [comment]
The # 1 issue still exists. The file descriptor may be leaked in the early return. I'll separate this out into its own issue.
