### ISSUE TITLE
Why have no "RunLoop" file ?

### ISSUE THREAD

**Issue by xuchuandong** [robbiehanson/CocoaAsyncSocket#475]
today I had download the cocoasyncsocket with cocoapods,but it hasn't the 'runloop' file ,is it deprecated or some wrong with my project?

**Comment by xuchuandong** [comment]
the version of download is 7.5.0, but I use 7.4.3 is ok!

**Comment by Ewg777** [comment]
https://github.com/robbiehanson/CocoaAsyncSocket/issues/454
