### ISSUE TITLE
GCDAsyncSocket and Wi-Fi Direct

### ISSUE THREAD

**Issue by bunuelcubosoto** [robbiehanson/CocoaAsyncSocket#484]
Hi,

I'm currently testing GCDAsyncSocket for a new project. Does GCDAsyncSoket work with Wi-Fi Direct?

Everything works fine with Wi-Fi and Bluetooth, but not on Wi-Fi Direct.

Here's my setup:
1. Device discovery is done using the Bonjour service

```
 serviceBrowser = NetServiceBrowser()
 serviceBrowser.delegate = self
 serviceBrowser.includesPeerToPeer = true
 serviceBrowser.searchForServices(ofType: "_sample._tcp.", inDomain: "local.")
```
1. Connect to the address

```
socket.connect(toAddress: address)
```
1. x seconds later, I get this error

```
Error Domain=NSPOSIXErrorDomain Code=0 "Undefined error: 0" UserInfo={NSLocalizedDescription=Undefined error: 0, NSLocalizedFailureReason=Error in connect() function}
```

Thank you.

**Comment by RunsCode** [comment]
So. I hava the same problem and sometimes

**Comment by MarkAMcCorkle** [comment]
Any resolution to this? I get this with any attempt to connect using the latest GCDAsyncSocket.

**Comment by BhaveshTiwari** [comment]
I am using the latest code and i am also getting this error?

**Comment by FrankSwift** [comment]
I had met same problem, some devices work well,but some other devices work error.

**Comment by Lidalu** [comment]
I hava the same problem and sometimes

**Comment by Himatheja** [comment]
same issue...here
