### ISSUE TITLE
Listen in Background

### ISSUE THREAD

**Issue by nitrag** [robbiehanson/CocoaAsyncSocket#485]
I'm creating a VOIP app so I will have background privileges.

I can't see for sure but would this library allow me to listen for an incoming connection on a port and allow my app to wake-up? Essentially emulating push notification type emulation but on a LAN only (no internet) wifi network?

I found [this](http://stackoverflow.com/questions/8748874/gcdasyncsocket-background-voip), not sure if this is still relevant?

**Comment by chrisballinger** [comment]
VoIP background sockets are deprecated. You need to use PushKit VoIP push
now.
