### ISSUE TITLE
On iOS 10 UDP sockets closing prematurely with errors

### ISSUE THREAD

**Issue by Oblique-Design** [robbiehanson/CocoaAsyncSocket#486]
Under iOS 10 I'm seeing udpSocketDidClose() being called with errors of 64 and 65.  I think these map to EHOSTDOWN and EHOSTUNREACH based on errno.h.  Closing and re-opening the socket does not fix the problem but, sometimes, restarting the app and putting the device in and out of airplane mode does.

This app connects to a dedicated WiFi device that does not support DNS so I'm wondering if something in iOS 10 is failing due to not having a host name to resolve.

This problem did not occur on iOS 9.  Here is code that did work previously.

`        var udpHost                 = "169.254.1.1"
        var udpPort:UInt16          = 43211

```
    udpSocket = GCDAsyncUdpSocket(delegate: self, delegateQueue: DispatchQueue.main)
    udpSocket.setIPv6Enabled(false)
    udpSocket.setPreferIPv4()

    do {
        try udpSocket.bind(toPort: udpPort)
        try udpSocket.beginReceiving()
        NSLog("UDP Socket created and bound to 43211")
    } catch {
        NSLog("UDP Failed to bind")
    }

    udpSocket.send(Data(bytes: UnsafePointer<UInt8>(msgArray), count: msgArray.count), toHost:host, port:port, withTimeout: -1, tag: 1)
```

`
I have tried increasing the timeouts, adding a TCP connection to keep the radios on, and even re-opening the connection when I get an error 64 or 65 (always fails to bind).

So far, nothing consistently allows the app to reestablish a UDP connection.

**Comment by ccimage** [comment]
do you fix this?   what's the description of error 65?

**Comment by Oblique-Design** [comment]
The problem is with the subnet of 169.254.x.x and iOS 10 and up.  Previously, this subnet was accepted by iOS but with 10.x Apple must have decided it was not a valid subnet and rejects it.  Changing to a 192.168.x.x based network works fine.

**Comment by ccimage** [comment]
We found that later than 10.3 have this subnet.  My solution is jump out and find next ipaddress on ios while detected ipaddress is 169.254.x.x
