### ISSUE TITLE
cannot access for iOS10 on Device that made in china

### ISSUE THREAD

**Issue by sixleaves** [robbiehanson/CocoaAsyncSocket#491]
there is a bug, cannot access for iOS10 on Device that made in china, beacause the china's TD-LTE.help me!

**Comment by abredo** [comment]
All iphones are made in Henan province, China.

**Comment by houqinghui** [comment]
is it true ?

At 2017-01-18 13:58:13, "abredo" <notifications@github.com> wrote:


All iphones are made in Henan province, China.
