### ISSUE TITLE
[iOS 10] connectToHost with hardcoded ip does not work anymore 

### ISSUE THREAD

**Issue by JeromeBouvard** [robbiehanson/CocoaAsyncSocket#492]
Hi , 
I have an app on the AppStore for almost 2 years and it was working perfectly until iOS 10 release.

I have a hardware module, generating its own wifi network , and I set up the iPhone to connect to it manually with static address.

Phone : 192.168.1.11
Wifi Module : 192.168.1.10

**iOS 9** : `mySocket connectToHost:@"192.168.1.10" onPort:80` works **OK**
**iOS10** : `mySocket connectToHost:@"192.168.1.10" onPort:80` is **KO**
No error in the logs ..

Anything related to IPv6 or new wifi protection ?
Thanks for your help.

**Comment by JeromeBouvard** [comment]
any info on that ?
Seems this might be an iOS problem : 
https://discussions.apple.com/thread/7705927

**Comment by thejeff77** [comment]
+1

**Comment by thejeff77** [comment]
This is working for me now with the latest iOS devices.

**Comment by JeromeBouvard** [comment]
really ? still have the issue on my side

**Comment by Stu-JuLiaoY** [comment]
I met the same problem, did you solve it?
