### ISSUE TITLE
only UIViewController can receive GCDAsyncUDPSocket delegate method

### ISSUE THREAD

**Issue by ruixingchen** [robbiehanson/CocoaAsyncSocket#494]
1. I write a Parent class that has a  GCDAsyncUdpSocket and send data to a local device in a Child class, I can not get response.
2. I present Parent class directly, I have a response.
3. I write a Manager class, and send data, no response

**Comment by rauberdaniel** [comment]
Confirm this. The didReceive method is only called as method of a UIViewController. There are not errors otherwise, the method is simply not called.

**Comment by ruixingchen** [comment]
in fact I use a Manager class can receive response sometimes, yes most time I can't get it, and I don't think send UDP or TCP in a UIViewController is good , it looks bad and hard to manage the life of socket.
CocoaAsyncSocket is great, I google for "ios udp", every link target to it, you are a great engineer and hope CocoaAsyncSocket can be better, such as delegate in a NSObject class.

**Comment by rauberdaniel** [comment]
@ruixingchen my fix for now is to use a manager class which is a subclass of UIViewController (doesn’t have to control any views though). Works for me but happy to see this fixed.

**Comment by ruixingchen** [comment]
@rauberdaniel  I present a subclass of (a subclass of UIViewController which has the delegate code), no response. now I write all UDP and delegate code in my ViewController, that is awkward.

**Comment by tonick80** [comment]
robbiehanson ?

**Comment by chrisballinger** [comment]
I really doubt this isn't an issue with the library itself. Any NSObject conforming to the protocol should work. Verify your delegates and weak references.
