### ISSUE TITLE
GCDAsynecUdpSocket.m line 1351， NSAssert(!(preferIPv4 && preferIPv6), @"Invalid config state"); statistics shows lots of users will crash at this place. Could pls help me explain this issue

### ISSUE THREAD

**Issue by wenyhooo** [robbiehanson/CocoaAsyncSocket#496]
GCDAsynecUdpSocket.m line 1351， NSAssert(!(preferIPv4 && preferIPv6), @"Invalid config state"); statistics shows lots of users will crash at this place. Could pls help me explain this issue

**Comment by chrisballinger** [comment]
NSAsserts shouldn't be included in production builds.. how are you seeing this?
