### ISSUE TITLE
Why Not detected Network state？

### ISSUE THREAD

**Issue by tangbing** [robbiehanson/CocoaAsyncSocket#507]
[I try to invalid address and connected network ,but result show success,Actually connect is failure,`  NSError *err = nil;
    if (![self.m_socket connectToHost:PRICE_IP onPort:PRICE_PORT withTimeout:-1 error:&err]) {
        TbLog(@"TaskPriceSocket Error: %@", err);
        return NO;
        
    } else {
        TbLog(@"💪🏾TaskPriceSocket 连接成功，");
    }
`
I don't get the network state
,Can you help me?,I hope get your help!

**Comment by wanghanfeng** [comment]
I'm in the same boat as you......
