### ISSUE TITLE
IPV6 testing: Error Domain=NSPOSIXErrorDomain Code=57 "Socket is not connected"

### ISSUE THREAD

**Issue by rdoddi123** [robbiehanson/CocoaAsyncSocket#513]
Hello,
We are testing apps for IPV6 compatibility in both IPV6 (nat64 network) only and IPV4 only networks. We had been using the GCDAsyncSocket network library to make socket connections for our app to send and receive data over it. 

**1.** When we test our iOS app (using the old GCDAsyncSocket code that we had downloaded in 2014) connecting to IPV6 only (nat-64) network as per Apple's guides [here](https://developer.apple.com/library/content/documentation/NetworkingInternetWeb/Conceptual/NetworkingOverview/UnderstandingandPreparingfortheIPv6Transition/UnderstandingandPreparingfortheIPv6Transition.html), the socket connection gets established successfully as soon as we log into the app, but within a few seconds (probably 20-30seconds , sometimes in a couple of mins), the -(void)socketDidDisconnect:(GCDAsyncSocket *)sock withError:(NSError *)err gets called disconnecting the socket.
This happens only once every time we log out and log in to our app. As soon as we login, socket gets established, then suddenly gets disconnected throwing the below error:

> _2016-12-17 09:11:10.650437 atCommand Enterprise[288:13780] LOG: Socket disconnect
> 2016-12-17 09:11:11.979232 atCommand Enterprise[288:13780] LOG: -[MLAPIControl socketDidDisconnect:withError:] -> 175
> Printing description of err:
> Error Domain=NSPOSIXErrorDomain Code=57 "Socket is not connected" 
> UserInfo={_kCFStreamErrorCodeKey=57, _kCFStreamErrorDomainKey=1}
> 
> Printing description of ((__NSCFDictionary *)0x0000000170470880):
> {
>  "_kCFStreamErrorCodeKey" = 57;
>  "_kCFStreamErrorDomainKey" = 1;
> }
> Printing description of sock:
> <GCDAsyncSocket: 0x101737d70>
> 
> 2016-12-17 09:11:55.853540 atCommand Enterprise[288:13780] LOG: Error Domain=NSPOSIXErrorDomain Code=57 "Socket is not connected" UserInfo={_kCFStreamErrorCodeKey=57, _kCFStreamErrorDomainKey=1}
> 
> 2016-12-17 09:11:55.858775 atCommand Enterprise[288:13780] LOG: -[MLAPIControl socketDidDisconnect:withError:] :_  

**2.** The exactly same issue of socket disconnection, after initial successful connection, happens even when i downloaded the latest (Latest commit 8ce941d 25 days ago) GCDAsyncSocket library code. 

I'm attaching the stack trace screen shot from my Xcode editor for reference. This is when i was using the latest download of GCDAsyncSocket network library in my code for socket connections.

<img width="1399" alt="screen shot 2016-12-17 at 8 49 07 am" src="https://cloud.githubusercontent.com/assets/13783963/21288899/e563d940-c454-11e6-953a-be18d61b782d.png">

Any help is greatly appreciated.
Thank You.

**Comment by msanilkumar2020** [comment]
Even i am also facing same issue, not able to connect to IPV6 address using via interface code.

**Comment by msanilkumar2020** [comment]
@rdoddi123 , are you able to solve this issue?

**Comment by rdoddi123** [comment]
msanilkumar2020, no i could not!

**Comment by ryanstout** [comment]
@rdoddi123 @msanilkumar2020 any luck on this one, I'm still seeing it with a fairly new GDCAsyncSocket.  We're connecting via an ipv4 address.  (But we have ipv6 compiled into our kernel for the box we're connected to, if that matters) Thanks!
