### ISSUE TITLE
Incorrect source address on ipv6 udp multicast packet (Tmobile related?)

### ISSUE THREAD

**Issue by raistlin969** [robbiehanson/CocoaAsyncSocket#519]
We're seeing an issue with iOS (10.0 and 10.2) phones where ipv6 UDP multicast packets have the wrong source address but go out on the expected interface to the expected multicast group. The source address is the Tmobile LTE ipsec interface but we are specifying en0 as the interface to use.

First, here the interfaces on this iPhones with Tmobile (some info redacted with XXXX)

    "awdl0/ipv6" = "fe80::ac2d:c9ff:fedb:b2c1";
    "en0/ipv4" = "192.168.XXX.XXX";
    "en0/ipv6" = "fe80::442:XXXX:XXXX:XXXX";
    "ipsec1/ipv6" = "fe80::e2b5:XXXX:XXXX:XXXX";
    "ipsec3/ipv6" = "2607:fb90:25ba:b183:8e0:XXXX:XXXX:XXXX";
    "ipsec4/ipv6" = "2607:fb90:25ba:b183:8e0:XXXX:XXXX:XXXX";
    "lo0/ipv4" = "127.0.0.1";
    "lo0/ipv6" = "fe80::1";
    "pdp_ip0/ipv6" = "2607:fb90:250f:34bc:d459:XXXX:XXXX:XXXX";
    "pdp_ip1/ipv6" = "2607:fb90:25ba:b183:8579:XXXX:XXXX:XXXX";
    "utun0/ipv6" = "fe80::4ffd:XXXX:XXXX:XXXX";

When we bind to the port we specify

    port = 1900
    interface = en0
    [self.udpSocket bindToPort:1900 interface:@"en0" error:&error]

When we join the multicast group we specify

    host = ff05::c
    interface = en0
    [self.udpSocket joinMulticastGroup:@"FF05::C" onInterface:@"en0" error:&error]

When we send the data we specify

    host = ff05::c
    port = 1900
    [self.udpSocket sendData:data toHost:@"FF05::C" port:1900 withTimeout:60 tag:1]

We see (via wireshark and other listeners of that multicast group) the packet go out on the correct multicast group, correct port, but it has the Tmobile ipsec address (2607:fb90:25ba:b183:8e0:XXXX:XXXX:XXXX) as the source port and not en0 as we expect.

We have tried to append %en0 to the host but we get the same result.

**Comment by raistlin969** [comment]
We are still seeing this issue with the latest iOS, is any one else?

**Comment by waitforsomeone** [comment]
I have the same problem，did you reslove it ?

**Comment by waitforsomeone** [comment]
this Library can not be Used  in America ,because  Tmobile  can't be connected,please resolve it

**Comment by raistlin969** [comment]
No we have not figured out anything yet. But we did learn one thing. It seems iPhone 6/6+ has an issue with massively dropping multicast packets. We have submitted a bug with Apple about it.

**Comment by ryanstout** [comment]
We're seeing GCDAsyncSocket (TCP) failing to connect only on TMobile.  Could that be related?  (Looks like this issue is probably udp multicast specific right?)
