### ISSUE TITLE
Socket server IP address?

### ISSUE THREAD

**Issue by vahids** [robbiehanson/CocoaAsyncSocket#521]
Hi, Is there any way to determine Socket server IP address ?
I config server socket:
`self.socket = GCDAsyncSocket(delegate: self, delegateQueue: dispatch_get_main_queue())
do {
    try socket!.acceptOnPort(port)
} catch {
    print("Port access failed")
}
`

I used this delegate for establish connection:
`func socket(sock: GCDAsyncSocket, didAcceptNewSocket newSocket: GCDAsyncSocket)`

Client will connect the my socket server and everything working well. Thanks for this awesome library.
I just want to know Is there any way to determine Server IP in server side?

**Comment by aaronvizzini** [comment]
Hi, I was wondering if you ever found a way of handling this? I was wanting to do something similar.
