### ISSUE TITLE
Potential file descriptor leak in -[GCDAsyncSocket doAccept:]

### ISSUE THREAD

**Issue by JosephPecoraro** [robbiehanson/CocoaAsyncSocket#522]
This was raised in https://github.com/robbiehanson/CocoaAsyncSocket/issues/473 and still exists in trunk https://github.com/robbiehanson/CocoaAsyncSocket/commit/8ce941d5d3df4b9c4e8034f50c1e0d49d786a221.

At [GCDAsyncSocket.m:1953](https://github.com/robbiehanson/CocoaAsyncSocket/blob/master/Source/GCD/GCDAsyncSocket.m#L1953) there is a return, that may not have cleaned up after the `childSocketFD` file descriptor that was opened in this method.

Currently:

```objc
// ... childSocketFD is created above and is valid ...
int result = fcntl(childSocketFD, F_SETFL, O_NONBLOCK);
if (result == -1)
{
    LogWarn(@"Error enabling non-blocking IO on accepted socket (fcntl)");
    return NO;
}
```

The file descriptor should be closed before returning, otherwise it will be leaked. Something like:

```objc
// ... childSocketFD is created above and is valid ...
int result = fcntl(childSocketFD, F_SETFL, O_NONBLOCK);
if (result == -1)
{
    LogWarn(@"Error enabling non-blocking IO on accepted socket (fcntl)");
    close(childSocketFD);
    return NO;
}
```

**Comment by chrisballinger** [comment]
Thanks! Would you mind submitting a PR?
