### ISSUE TITLE
Missing files within the examples

### ISSUE THREAD

**Issue by tommy7600** [robbiehanson/CocoaAsyncSocket#533]
Hi,
some files are missing within the examples so we cannot build examples.
<img width="273" alt="zrzut ekranu 2017-03-20 o 11 21 57" src="https://cloud.githubusercontent.com/assets/572378/24096001/f2bbecdc-0d5f-11e7-83ec-c5790e081b70.png">

**Comment by AniOSDeveloper** [comment]
Same here!  Is there any solution?

**Comment by DarknessChen** [comment]
Same here

**Comment by JanC** [comment]
Same here, you need to fix the file paths in Xcode:

![screen_shot_2018-01-12_at_11_12_25](https://user-images.githubusercontent.com/707703/34871390-c5ce6290-f78d-11e7-84ec-d2e3a0aa264f.png)
