### ISSUE TITLE
5 second delay for DNS lookup

### ISSUE THREAD

**Issue by bennibau** [robbiehanson/CocoaAsyncSocket#539]
I have written a custom http client based on CocoaAsyncSocket and everything works fine BUT I sometimes have a delay of exactly 5000ms when looking up a DNS. I guessed that it has something to do with IPv6 so I tried to disable via:

    [socket setIPv4PreferredOverIPv6:YES];
    [socket setIPv6Enabled:NO];

But no luck. It is like every 10th or 20th request that takes so during DNS lookup.

EDIT: I could narrow it down to this call:
`int gai_error = getaddrinfo([host UTF8String], [portStr UTF8String], &hints, &res0);`
which takes 5010ms sometimes.

**Comment by sisishiliu** [comment]
nobody?
