### ISSUE TITLE
No route to host

### ISSUE THREAD

**Issue by zjz2020** [robbiehanson/CocoaAsyncSocket#540]
iOS,   I use UDP send radio ,Run on the simulator is OK ,but at my testing photo is error,"No route to host",how to solve thise problem...

**Comment by MyOnlyOnlySunshine** [comment]
I have the same as yours

**Comment by MauriceArikoglu** [comment]
@zjz2020 please post your code where you setup the sockets and send / receive

**Comment by MyOnlyOnlySunshine** [comment]
I have solved the problem, it's because  the setting of our ESP 8266  WIFI  module. Thanks

**Comment by MauriceArikoglu** [comment]
@myOnlyOnlySunshine could you post your connection/broadcast code please? I have a similar problem. And for people having similar issues, it would be helpful to have a working code snippet here.

**Comment by MyOnlyOnlySunshine** [comment]
You mean screenshots of my code  or just upload the demo ?

**Comment by MauriceArikoglu** [comment]
Upload the demo please :)

**Comment by MyOnlyOnlySunshine** [comment]
I am  just coding like you demo... The "No route to host"  or "connection refused " or "time out " problem  i've met  is  just because the hardware of wifi module. Not the code.

**Comment by MyOnlyOnlySunshine** [comment]
like the demo of   original  coder support

**Comment by zjz2020** [comment]
yes, this problem is  cause of wifi ,not because of our code

**Comment by MyOnlyOnlySunshine** [comment]
hah
