### ISSUE TITLE
Example for verifying self signed cert?

### ISSUE THREAD

**Issue by tethridge** [robbiehanson/CocoaAsyncSocket#542]
I'm trying to manually verify a self signed cert when starting TLS.

`sock.startTLS([GCDAsyncSocketManuallyEvaluateTrust: true as NSObject])`

I'm trying to verify the self signed cert by shipping the server cert as a ".der" file with the app.  Then load that .der file and set it as the anchor cert.  This doesn't work and I'm not sure how to proceed.  

    public func socket(_ sock: GCDAsyncSocket, didReceive trust: SecTrust, completionHandler: @escaping (Bool) -> Swift.Void) {
        
        //
        // This code below always returns .recoverableTrustFailure. How should we verify the self signed cert?
        //
        
        var acceptTrust = false

        let url = Bundle.main.bundleURL.appendingPathComponent("cert.der")
        if let data = NSData(contentsOf: url) {
            let anchorCert = SecCertificateCreateWithData(kCFAllocatorDefault, data)

            // Add our cert as an anchor
            SecTrustSetAnchorCertificates(trust, [anchorCert] as CFArray)
            SecTrustSetAnchorCertificatesOnly(trust, false)

            // Validate cert
            var secresult = SecTrustResultType.invalid
            if SecTrustEvaluate(trust, &secresult) != errSecSuccess {
                Log.e("SecTrustEvaluate failed.")
            }

            switch secresult {
            case .invalid:
                Log.d("Trust result invalid")
            case .deny:
                Log.d("Trust result deny")
            case .fatalTrustFailure:
                Log.d("Trust result fatal trust failure")
            case .otherError:
                Log.d("Trust result other error")
            case .recoverableTrustFailure:
                Log.d("Trust result recoverable trust failure")
            case .unspecified: // The OS trusts this certificate implicitly
                Log.d("Trust result unspecified")
            case .proceed: // The user explicitly told the OS to trust it
                Log.d("Trust result proceed")
                acceptTrust = true
            default:
                Log.d("Trust default case (\(secresult))")
            }
        } else {
            Log.e("Unable to find cert.der to authenticate server cert")
        }
        
        completionHandler(acceptTrust)
    }

I looked through the examples in the documentation, but deprecated params like kCFStreamSSLAllowsAnyRoot aren't available in Swift.

**Comment by meer1992** [comment]
I am also having the same issue, but for now I am trying to disable the "kCFStreamSSLValidatesCertificateChain" which is bad but since I am using it in my local server, I think it should be fine:
https://stackoverflow.com/questions/26864785/kcfstreamsslallowsexpiredcertificates-and-kcfstreamsslallowsanyroot-is-depre
