### ISSUE TITLE
Delegates do not work when in a differente class

### ISSUE THREAD

**Issue by caynan** [robbiehanson/CocoaAsyncSocket#543]
I created a wrapper class that uses `GCDAsyncUdpSocket` to make broadcast calls on the network.

it basically have a method `makeBroadcastSearch(completion: @escaping (_ result: Result<[BroadcastAnswer], UDPSocketError>) -> Void)`

So the ideia, it for my wrapperClass to be the delegate, and when it receives an answer from the network to pass it to the completion closure, but this don't work. 

If I set my calling class as the delegate it do receive the method calls, but I really didn't want to solve the problem like this, any tips on how to solve this?

Thanks!

**Comment by guicolares** [comment]
Same problem!! : (

**Comment by Rishikeshpange** [comment]
same issue .any update on this one.
