### ISSUE TITLE
EXC_BAD_ACCESS, GCDAsyncUDPSocket

### ISSUE THREAD

**Issue by shaviraghu** [robbiehanson/CocoaAsyncSocket#546]
I perform a very high throughput upload continuously and at some point in time i get this exception 
![screen shot 2017-05-02 at 19 53 05](https://cloud.githubusercontent.com/assets/1257362/25633154/79bb2896-2f76-11e7-8c59-b2e49a15af2a.png)

As i have enabled zombies i could Po in the console with the zombie address and it returns integer value
![screen shot 2017-05-02 at 19 53 24](https://cloud.githubusercontent.com/assets/1257362/25633173/932ede8a-2f76-11e7-86de-5f0b58ec70c3.png)

Any clues please.

**Comment by shaviraghu** [comment]
I tried using Instruments but this does not help because while using instruments the expected high throughput is not achieved and thus the exception never occurs. And on simulator too the exception never occurs.

**Comment by chrisballinger** [comment]
Interesting... Can you create a failing unit test for this?

**Comment by shaviraghu** [comment]
I used the address sanitiser and the memory address is different now.

![screen shot 2017-05-05 at 11 01 44](https://cloud.githubusercontent.com/assets/1257362/25739466/46da1384-3182-11e7-94b0-f617898ff506.png)

Sorry for my ignorance, but now i know how to po hex address

![screen shot 2017-05-05 at 11 03 18](https://cloud.githubusercontent.com/assets/1257362/25739526/8c936d8a-3182-11e7-9c13-73db8d2c1003.png)

And it says error: Trying to put the stack in unreadable memory at: 0x16f193d30.

Trying with image command outputs nothing

![screen shot 2017-05-05 at 11 03 30](https://cloud.githubusercontent.com/assets/1257362/25739578/c2ec7836-3182-11e7-9747-e11434cbe4b3.png)

Here is the Thread stack trace 

![screen shot 2017-05-05 at 10 56 50](https://cloud.githubusercontent.com/assets/1257362/25739373/e866ebec-3181-11e7-9800-29725b5e19de.png)

And Ends with

![screen shot 2017-05-05 at 10 59 50](https://cloud.githubusercontent.com/assets/1257362/25739394/ff12c848-3181-11e7-99e6-696e7e391f5f.png)

To create a failing unit test i need guidance, I have the following setup, 
A custom server capable of UDP throughput operations against which an upload of around 33 Mbps is performed for a period of 1 minute, it succeeds most of the times but fails too. I am not sure how to unit test this.

**Comment by chrisballinger** [comment]
If you look at the current unit tests for GCDAsyncSocket, it creates both a server and client socket within setup, and then runs a number of tests. You could copy that template for the GCDAsyncUDPSocket version and make one of the tests attempt max throughput to trigger a crash. Either way having some basic UDP test scaffolding would be nice, so even if you can't reproduce it please submit a PR. :)

Based on your trace I wonder if it's recursing too deep and overflowing the stack.

**Comment by shaviraghu** [comment]
I tried with this template. Used the custom server instead of localhost server and tested with good mobile network hotspot. Apart from getting "No buffer space available" I cannot recreate the crash.

[UDP_UnitTest_HighThroughputUpload.zip](https://github.com/robbiehanson/CocoaAsyncSocket/files/989561/UDP_UnitTest_HighThroughputUpload.zip)

**Comment by caofutao** [comment]
hey,I met the same  problem, my scene is sent a udp per 0.5s ,and more then ten minutes app crash！so how to solve it ，TKS！

**Comment by caofutao** [comment]
@shaviraghu ,my problem is solved, because i create many threads lead to my app crash.
