### ISSUE TITLE
Create GCDAsyncSocket from already connected BSD socket

### ISSUE THREAD

**Issue by mrvincenzo** [robbiehanson/CocoaAsyncSocket#548]
Is it possible to create GCDAsyncSocket from already connected BSD socket? I know that there is no such API so I guess the answer is NO. But, after inspecting the code I think it is possible with light to moderate modifications. I wonder if that's sound correct?

**Comment by mrvincenzo** [comment]
I was able to create a GCDAsyncSocket from already connected BSD socket with below code

      + (GCDAsyncSocket *)GCDAsyncSocketFromSocketFD:(int)socketFD delegate:(id<GCDAsyncSocketDelegate>)delegate delegateQueue:(nullable dispatch_queue_t)delegateQueue {
        GCDAsyncSocket *socket = [[GCDAsyncSocket alloc] initWithDelegate:delegate delegateQueue:delegateQueue];
  
        // dispatch_sync intentionally
        dispatch_sync(socket->socketQueue, ^{ @autoreleasepool {
          socket->socket4FD = socketFD; // the socket is already connected thus it doesn't matter if it is 4FD or 6FD
          socket->flags = kSocketStarted;
          [socket didConnect:socket->stateIndex];
        }});
  
        return socket;
      }

**Comment by chrisballinger** [comment]
That's interesting and probably useful for others. Perhaps this could be cleaned up and merged, and support IPv6 and UDP as well.

**Comment by mrvincenzo** [comment]
@chrisballinger I've updated the code to support both IPv4 and IPv6. I will check regarding UDP.

**Comment by chrisballinger** [comment]
Awesome! If you want to make a pull request, it would be great if you could also add a small self-contained unit test to the existing test suite.

I'd also recommend changing the exceptions an error parameter, for a method signature like this:

```objc
+(nullable instancetype)socketFromSocketFD:(int)socketFD delegate:(id<GCDAsyncSocketDelegate>)delegate delegateQueue:(nullable dispatch_queue_t)delegateQueue error:(NSError**)error;
```

**Comment by mrvincenzo** [comment]
@chrisballinger I will add a unit test and update the code as per your recommendation

**Comment by mrvincenzo** [comment]
@chrisballinger Pull request created #550

**Comment by chrisballinger** [comment]
Merged, thanks!
