### ISSUE TITLE
error type with bind(toPort:)

### ISSUE THREAD

**Issue by AniOSDeveloper** [robbiehanson/CocoaAsyncSocket#551]
I got type '()' when tried udpClient.bind(toPort: myport) with swift3 in Xcode 8.3.2 through cocoapods, and I got that it should be boolen  in GCDAsyncUdpSocket declaration file. You can see the details in the screenshot below, and my question is:  What's the matter?

**Comment by AniOSDeveloper** [comment]
I'm sorry, the screenshot cannot be uploaded. And code is:
`let udpClient = GCDAsyncUdpSocket(delegate: self, delegateQueue: DispatchQueue.main)
        
        do{
            let isBindSuccess = try udpClient.bind(toPort: 12) //constant 'isBindSuccess'inferred to have type '()', which may be unexpected
        }catch{
            
        }`

**Comment by chrisballinger** [comment]
There is no return value, the error and BOOL return get translated to a Swift `throws`. If it doesn't work you'll know inside the `catch` block.
