### ISSUE TITLE
GCDAsyncSocketDelegate doesn't need to implement NSObject

### ISSUE THREAD

**Issue by karlvr** [robbiehanson/CocoaAsyncSocket#556]
`GCDAsyncSocketDelegate` currently implements the `NSObject` protocol, but it doesn't appear to need to for the `GCDAsyncSocket` functionality. I'd prefer not to have to extend `NSObject` when I use the protocol from Swift. What do you think about removing `NSObject` from the definition of `GCDAsyncSocketDelegate`?

**Comment by chrisballinger** [comment]
Originally it didn't conform to `NSObject` but I think it was added at some point before Swift was released. Changing it back may be a breaking change for some people, but I can see the benefits if you are going heavy into Swift.

If you create a pull request with these changes (and the same for UDP) and a pure-Swift test I think it could be merged, especially if it doesn't break any existing tests or cause warnings/errors. I guess you'd need to make a pure-Swift class to use within XCTest. Even so, if this doesnt break anything in our suite, it may be a breaking API change for other people.
