### ISSUE TITLE
Is there a way to use SNI (Server Name Indication)

### ISSUE THREAD

**Issue by tethridge** [robbiehanson/CocoaAsyncSocket#557]
I've tried connecting to a server that uses SNI, but it failed to connect.  I received this error.

 The operation couldn’t be completed. (kCFStreamErrorDomainSSL error -9807.)

Is there a way to use SNI?

Thanks!

**Comment by HJianBo** [comment]
Any update on this?

**Comment by ftp27** [comment]
Try to put extra data to the TLS settings dictionary in `GCDAsyncSocketDelegate`
```swift
fsocket(_ socket: GCDAsyncSocket, didConnectToHost host: String, port p: UInt16) {
    var settings: [String: NSObject] =  [String: NSObject]()
    settings["kCFStreamSSLPeerName"] = "ADDRESS" as NSObject?
    socket.startTLS(settings)
} 
```
The key also should be available from `GCDAsyncSocketSSLPeerName` constant but it's not. Probably it will work in Obj-C
