### ISSUE TITLE
Error Domain=GCDAsyncSocketErrorDomain Code=1 "Attempting to connect while connected or accepting connections. Disconnect first." UserInfo={NSLocalizedDescription=Attempting to connect while connected or accepting

### ISSUE THREAD

**Issue by OneWang** [robbiehanson/CocoaAsyncSocket#558]
Error Domain=GCDAsyncSocketErrorDomain Code=1 "Attempting to connect while connected or accepting connections. Disconnect first." UserInfo={NSLocalizedDescription=Attempting to connect while connected or accepting；connected some time;after a while it is disconnected; why?

**Comment by IvanGao0217** [comment]
Have you retain the newSocket form delegate: 「didAcceptNewSocket」?

**Comment by IvanGao0217** [comment]
there is a delegate 「socketDidDisconnect」 you can see your Socket disconnectError 
 I have face the same problem and detect error is 「Domain=GCDAsyncSocketErrorDomain Code=7 "Socket closed by remote peer" UserInfo={NSLocalizedDescription=Socket closed by remote peer}」 my connectHost is "google.com" :(

**Comment by OneWang** [comment]
your problem is server disconnect your connection;but my issue is I have connected socket,after a while; it is automatic disconnect; I do not why?

**Comment by IvanGao0217** [comment]
Did this automatic disconnect called socketDidDisconnect delegate? if Yes, you can figure it out with ErrorCode, please post it. if Not, sorry I can't help you~

**Comment by OneWang** [comment]
The error is Error Domain=GCDAsyncSocketErrorDomain Code=1 "Attempting to connect while connected or accepting connections. Disconnect first." UserInfo={NSLocalizedDescription=Attempting to connect while connected or accepting；

**Comment by IvanGao0217** [comment]
your errorCode is `connect(toHost host: String, onPort port: UInt16)` catched error, not socketDidDisconnect Delegate error
![asdf](https://user-images.githubusercontent.com/18186467/27861267-ae811fd6-61b2-11e7-91e9-a6db699fb57f.png)
see this ErrorEnum, your ErrorCode  = 1, is a config error, means your connection is connecting, you shouldn't call   `connect(toHost host: String, onPort port: UInt16)` again

**Comment by OneWang** [comment]
OK，thank you！
