### ISSUE TITLE
Attempting to connect while connected or accepting connections. Disconnect first

### ISSUE THREAD

**Issue by premBlaze** [robbiehanson/CocoaAsyncSocket#559]
While trying to establish multiple TCP connections am getting "Attempting to connect while connected or accepting connections. Disconnect first" error, 
Please suggest me how to establish 2 or more live TCP connections using CocoaAsyncSocket.

**Comment by premBlaze** [comment]
Create and use another GCDAsyncSocket instance if you are using GCDAsyncSocket library(if you are using NSStream also same process), you can differentiate TCP connection messages with connectedHost.

**Comment by teksunios** [comment]
Hey @premBlaze , I am facing the same issue for creating connection for multiple ports. 

- I have same Host but 2 different ports.
- I need to read data from Multiple Ports and I am trying to create 2 instances for GCDAsyncSocket.
- I am trying to connect with 2 different instances.
- I can successfully connect with Port 1 but when it tries to connect with 2nd port, Both the socket disconnects.

It calls this method 2 times, 

func socketDidDisconnect(_ sock: GCDAsyncSocket, withError err: Error?) {
        print("didDisconnect!")
    }

Can you please share your steps that how did you created 2 instances of socket and successfully connected with both?

Here is my approach:

`class SocketManagerTCP: NSObject, GCDAsyncSocketDelegate {
    
    static let shared = SocketManagerTCP()
    var socket1 : GCDAsyncSocket!
    var socket2 : GCDAsyncSocket!

override init(){
        super.init()
        setupConnection()
    }
    func setupConnection() {
        socket1 = GCDAsyncSocket(delegate: self, delegateQueue: DispatchQueue.main)
        socket2 = GCDAsyncSocket(delegate: self, delegateQueue: DispatchQueue.main)
        attemptConnection(socket: socket1, port: SocketNetwork.port1)
        attemptConnection(socket: socket2, port: SocketNetwork.port2)
}

func attemptConnection(socket:GCDAsyncSocket, port:Int) {
        do {
            print("Connecting to socket server on port \(port)...")
            try socket.connect(toHost: SocketNetwork.host, onPort: UInt16(port), withTimeout: 5.0)
        } catch let error {
            print("Cannot open socket to \(SocketNetwork.host):\(port): \(error)")
        }
    }
}
`
