### ISSUE TITLE
Error in bind() function when using with Carthage

### ISSUE THREAD

**Issue by gavinwilliams** [robbiehanson/CocoaAsyncSocket#570]
I can't bind to a port on macOS 10.12 when using Carthage. I get the following Posix error.
`Error in bind() function`
Using CocoaPods I have issues with the same code. Is anyone else experiencing this issue? I have code signed the framework too.

```
class ViewController: NSViewController {

    var server: GCDAsyncUdpSocket!
    let queue = DispatchQueue(label: "com.quander.socket")

    override func viewDidLoad() {
        super.viewDidLoad()

        // Do any additional setup after loading the view.
        server = GCDAsyncUdpSocket(delegate: self, delegateQueue: DispatchQueue.main)

        do {
            try server.bind(toPort: 8080)
            try server.beginReceiving()
        } catch let error {
            print("Error! \(error)")
        }

    }

    override var representedObject: Any? {
        didSet {
        // Update the view, if already loaded.
        }
    }

}

extension ViewController: GCDAsyncUdpSocketDelegate {

    func udpSocket(_ sock: GCDAsyncUdpSocket, didReceive data: Data, fromAddress address: Data, withFilterContext filterContext: Any?) {
        let message = String(data: data, encoding: .utf8)?.trimmingCharacters(in: CharacterSet.whitespacesAndNewlines)
        print(message!)

    }

}
```

**Comment by chrisballinger** [comment]
Is anything else already running on that port?

**Comment by gavinwilliams** [comment]
@chrisballinger nothing else is bound to that port. I can change it to anything I like and get that error.

I'm using CocoaPods now and everything is working fine. I can only assume that when run as a Framework from Carthage there is some issue with getting permission to bind to a port on macOS.

**Comment by fanxiangyang** [comment]
i use  xcode9.3  mac 10.13.4   create Server Socket ,also error ,use  drag code in my project

`Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted" UserInfo={NSLocalizedDescription=Operation not permitted, NSLocalizedFailureReason=Error in bind() function}`

**Comment by jianh1986** [comment]
I met same problem, I believe it's the generated Xcode entitlements that prevent from binding. I changed those values to false and now the bind works.

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>com.apple.security.app-sandbox</key>
    <false/>
    <key>com.apple.security.files.user-selected.read-only</key>
    <false/>
</dict>
</plist>
```

**Comment by deckyfx** [comment]
encounter this issue too. 

so is the only way to solve this is to add sandbox network capabilities?

**Comment by nimishbansal-bs** [comment]
How can I edit sandbox entitlements for SafariDriver ?
As I am getting 
`Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted" UserInfo={NSLocalizedDescription=Operation not permitted, NSLocalizedFailureReason=Error in bind() function} `
while running `/usr/bin/safaridriver -p0` after `sudo /usr/bin/safaridriver -p0 --enable`
