### ISSUE TITLE
GCDAsyncSocket + NSNetService doesn’t work anymore on iOS 11 over Bluetooth

### ISSUE THREAD

**Issue by thomasdorey** [robbiehanson/CocoaAsyncSocket#571]
Hi,

I am using GCDAsyncSocket + NSNetService in an iOs app for local multiplayer games over Wifi and/or Bluetooth.
I have noticed that it does not work anymore on iOs 11 when the two devices are trying to connect through Bluetooth (Only Bluetooth is activated, Wifi is turned off on the 2 devices). It still works great for Wifi.

It seems that the `connect()` call in `- (BOOL)connectWithAddress4:(NSData *)address4 address6:(NSData *)address6 error:(NSError **)errPtr` results to a `-1` return and an `errno 53`.
The only difference I can see between iOs 11 and lower versions is that in iOs 11 it tries to connect with an Ipv6 addresses, wheres it uses an Ipv4 on lower iOs versions.

I am using a code very similar to the BonjourServer / BonjourClient examples, I just set to `YES` the `includesPeerToPeer` property of the `NSNetService` and `NSNetServiceBrowser` objects to enable Bluetooth detection.

Do you have any idea of what can the problem be with iOs 11 ?

**Comment by chrisballinger** [comment]
Please submit a radar to Apple: http://bugreport.apple.com/

**Comment by virl** [comment]
If submitting issue to Apple bug report, please include rdar://34615975 in it — it is my bug report about the same issue.
