### ISSUE TITLE
EXC_BAC_ACCESS crash on iOS 11

### ISSUE THREAD

**Issue by Jonathan331** [robbiehanson/CocoaAsyncSocket#574]
I use GCDAsyncSocket for communication between two apps and it works well on iOS 10 and earlier version.Recently i update it to iOS 11 beta 4 and crash happens accidentally.

<img width="883" alt="wx20170807-140652 2x" src="https://user-images.githubusercontent.com/8294820/29014051-a9b3e048-7b79-11e7-8306-2c048ef4d08d.png">

it seems that the method [theDelegate socket:self didAcceptNewSocket:acceptedSocket] is called twice and it returns Thread 8: EXC_BAD_ACCESS (code=1, address=0x30) on second call.

i print the method and it return below:
(lldb) po [theDelegate socket:self didAcceptNewSocket:acceptedSocket]
error: warning: couldn't get cmd pointer (substituting NULL): no variable named '_cmd' found in this frame
error: Execution was interrupted, reason: EXC_BAD_ACCESS (code=1, address=0x30).
The process has been returned to the state before expression evaluation.

**Comment by zhangshijian** [comment]
这个问题你解决了没有？

**Comment by VisualEcho** [comment]
I have the same question. I use iOS 11 and use Swift 4.0. I've no idea how to fix it
