### ISSUE TITLE
EXC_BAD_ACCESS KERN_INVALID_ADDRESS on 7.6.1

### ISSUE THREAD

**Issue by yvbeek** [robbiehanson/CocoaAsyncSocket#579]
With the latest version (7.6.1) I see a lot of crashes with our app.
Does anyone have a clue what's going wrong here?

It looks like it is happening when the socket is closed.
The crash suggests that a block in GCDAsyncSocket is being over-released.

Thread 5:
```objc
0 | libsystem_kernel.dylib | mach_msg_trap + 8
1 | libsystem_kernel.dylib | mach_msg + 72
2 | CoreFoundation | __CFRunLoopServiceMachPort + 192
3 | CoreFoundation | __CFRunLoopRun + 1060
4 | CoreFoundation | CFRunLoopRunSpecific + 424
5 | Foundation | -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 304
6 | AsyncSocket | GCDAsyncSocket.m line 7596+[GCDAsyncSocket cfstreamThread]
7 | Foundation | __NSThread__start__ + 996
8 | libsystem_pthread.dylib | _pthread_body + 240
9 | libsystem_pthread.dylib | _pthread_body + 282
10 | libsystem_pthread.dylib | thread_start + 4
```

Thread 8:
```objc
1 | AsyncSocket | GCDAsyncSocket.m line 7550+[GCDAsyncSocket stopCFStreamThreadIfNeeded]
2 | AsyncSocket | GCDAsyncSocket.m line 7905-[GCDAsyncSocket removeStreamsFromRunLoop]
3 | AsyncSocket | GCDAsyncSocket.m line 3175-[GCDAsyncSocket closeWithError:]
4 | AsyncSocket | GCDAsyncSocket.m line 7691__CFReadStreamCallback_block_invoke.1212
5 | libdispatch.dylib | _dispatch_call_block_and_release + 24
6 | libdispatch.dylib | _dispatch_client_callout + 16
7 | libdispatch.dylib | _dispatch_queue_serial_drain + 928
8 | libdispatch.dylib | _dispatch_queue_invoke + 884
9 | libdispatch.dylib | _dispatch_root_queue_drain + 540
10 | libdispatch.dylib | _dispatch_worker_thread3 + 124
11 | libsystem_pthread.dylib | _pthread_wqthread + 1096
12 | libsystem_pthread.dylib | start_wqthread + 4
```

Thread 11: **EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000020**
```objc
0 | libobjc.A.dylib | objc_object::release() + 8
1 | AsyncSocket | GCDAsyncSocket.m line 0__destroy_helper_block_.1215
2 | libsystem_blocks.dylib | _Block_release + 160
3 | libdispatch.dylib | _dispatch_client_callout + 16
4 | libdispatch.dylib | _dispatch_queue_serial_drain + 928
5 | libdispatch.dylib | _dispatch_queue_invoke + 884
6 | libdispatch.dylib | _dispatch_root_queue_drain + 540
7 | libdispatch.dylib | _dispatch_worker_thread3 + 124
8 | libsystem_pthread.dylib | _pthread_wqthread + 1096
9 | libsystem_pthread.dylib | start_wqthread + 4
```
(I've shortened CocoaAsyncSocket to AsyncSocket to prevent scrolling)

**Comment by Zyphrax** [comment]
@chrisballinger Could this be caused by commit https://github.com/robbiehanson/CocoaAsyncSocket/commit/6b124ba3511f976f64ed3b35e5d4493e862b4c40 / issue https://github.com/robbiehanson/CocoaAsyncSocket/issues/541?

**Comment by shihhung** [comment]
I have this issue too, Does anyone have a solution ?

**Comment by Zyphrax** [comment]
Unfortunately this is now the number 1 crash in our app.
GCDAsyncSocket is not reliable for iOS 10+ 🙁 

![image](https://user-images.githubusercontent.com/966500/33505636-2ecbf39c-d6ba-11e7-87bc-c0a17e49bed2.png)

**Comment by chrisballinger** [comment]
havent seen this myself. can you reproduce?

**Comment by Zyphrax** [comment]
I haven't been able to reproduce it yet. We use a lot of iPads 2 and 3, because that is the minimum hardware that we support. Unfortunately those iPads can't run iOS 10 / 11.

Our app runs often for hours in the foreground. It could be a race condition or user transitioning between foreground / background. Those scenarios are difficult to reproduce.

It happens quite often though. For our latest version:

![image](https://user-images.githubusercontent.com/966500/33511024-0ae6f4ea-d6e2-11e7-99af-dd2f01716d9e.png)

**Comment by chrisballinger** [comment]
this only happens on ios 9 and below?

**Comment by Zyphrax** [comment]
The issue occurs only on iOS 10 and higher.

**Comment by zhuzijiang123456** [comment]
Is there somebody known how to use GCSAsyncSocket to send many message on many viewcontrollers but just create 1 socket connect?  
![default](https://user-images.githubusercontent.com/16201523/33536952-77712578-d8f3-11e7-936c-81d675b835f4.png) my god ,i just touch a little btn ,it create 7 connect! please help me !

**Comment by Zyphrax** [comment]
@zhuzijiang123456 could you please remove your post and open a new issue for this? This doesn't seem to be related to this issue.

**Comment by zhuzijiang123456** [comment]
oh  i am sorry , i just use git less , i dont known so much , thank you .
