### ISSUE TITLE
NSString *host = [inHost copy];  

### ISSUE THREAD

**Issue by hellowlf** [robbiehanson/CocoaAsyncSocket#581]
- (BOOL)connectToHost:(NSString *)inHost
               onPort:(uint16_t)port
         viaInterface:(NSString *)inInterface
          withTimeout:(NSTimeInterval)timeout
                error:(NSError **)errPtr
{
	NSString *host = [inHost copy];
    NSString *interface = [inInterface copy];
...
}
if I write like this,what will happen？

    NSString *host = inHost;
    NSString *interface = inInterface;

**Comment by saulogatti** [comment]
Copy is a new memory address used for that object, if you change the value of the first one does not change from the second.
Without the copy, you use the same memory address, if you change the value of the first, it changes from the second.

**Comment by chrisballinger** [comment]
It actually just increases the retain count for immutable strings, and will only copy if its mutable.
