### ISSUE TITLE
Compiler Warning on XCode9/10.13 SDK

### ISSUE THREAD

**Issue by ionescu007** [robbiehanson/CocoaAsyncSocket#584]
https://github.com/robbiehanson/CocoaAsyncSocket/blob/b6f98791995ab7c7ef6faee4726102a711431f58/Source/GCD/GCDAsyncUdpSocket.m#L1966

This should have __autoreleasing added in the NSError parameter definition.

**Comment by corymayer** [comment]
Looks like this was already fixed by https://github.com/robbiehanson/CocoaAsyncSocket/commit/0372a386fe350319106bc260dfd5b98d5f6ef52f. Can we get a release that includes this?

**Comment by tealshift** [comment]
Looks to be another warning on line# 1982 in the UPDSocket class. (I've got master branch)
