### ISSUE TITLE
How to get the address with "getHost(host:, port:, address:)" in swift?

### ISSUE THREAD

**Issue by ATI-Wuhan** [robbiehanson/CocoaAsyncSocket#588]
GCDAsyncUdpSocket.getHost(<#T##hostPtr: AutoreleasingUnsafeMutablePointer<NSString?>?##AutoreleasingUnsafeMutablePointer<NSString?>?#>, port: <#T##UnsafeMutablePointer<UInt16>?#>, fromAddress: <#T##Data#>)

OC like this:
- (void)udpSocket:(GCDAsyncUdpSocket *)sock didReceiveData:(NSData *)data
                                               fromAddress:(NSData *)address
                                         withFilterContext:(id)filterContext
{
    NSString *host = nil;
    uint16_t port = 0;
    [GCDAsyncUdpSocket getHost:&host port:&port fromAddress:address];
}

But, how to get this in swift? thank you!

**Comment by 5Nyck** [comment]
Hi, 
I think this SO thread will help you: 
https://stackoverflow.com/questions/31126029/what-data-types-for-gcdasyncudpsocket-gethost-in-swift
