### ISSUE TITLE
Can I set buffer size larger when read data?

### ISSUE THREAD

**Issue by huoyi2000** [robbiehanson/CocoaAsyncSocket#592]
A page of My App contains a request, which returns a large size of data, about 130000 bytes, so the method "socket: didReadData:" was called 10 times,each time returns 1000 bytes,so  it takes 15-30s to receive the whole data. when i show it to our customers, they cannot stand it.Our Android App takes just 4-5s to load the same request.I want to change the buffer size,so it would receive more bytes each time,but I cannot find the way。

**Comment by 15620946376** [comment]
Hi, Have you solved the problem？I'm in the same situation as you

**Comment by nohmw** [comment]
If you want to some of data, call this function.
[socket readDataToLength:P2P_SOCK_BUFF_SIZE withTimeout:-1 tag:tag];
 - P2P_SOCK_BUFF_SIZE : your defined size of buffer.

And then you can read data with your buffer length.
- (void)socket:(GCDAsyncSocket *)sock didReadData:(NSData *)data withTag:(long)tag
(NSData *)data length == P2P_SOCK_BUFF_SIZE.

Have you another problem?

**Comment by 15620946376** [comment]
For example, for example, I use readDataLength to read the image data. But it's not getting any faster. Actually, I want to speed up.

**Comment by 15620946376** [comment]
假如接收一张图片，android只需1s就可以接收完毕。但是我这边大概需要5s才能收到数据读取成功的回调方法。socket didread.我尝试用您的方法来接收，但是接收的速度没有感觉到变快。

**Comment by 15620946376** [comment]
If you receive a picture, android can receive it in 1s. But I need the 5s to get the data to read the successful callback method. Socket didread. I try to receive it with your method, but the speed of reception does not feel fast.

**Comment by nohmw** [comment]
I set the buffer size to around 65k,
Often used for file transfer of more than 10GB.
This shows a good enough performance.
Sorry, I did not do a comparison test in other environments.

**Comment by 15620946376** [comment]
Thank you. The default Buffer size is 4kb and how to set it to 64kb?

**Comment by nohmw** [comment]
I do not change the default buffer size.
It only calls the readDataToLength function at a certain point in time.
I also do not know how to change the default buffer size.
I call readDataToLength when I need to receive data.
I hope it helps ...

**Comment by 15620946376** [comment]
In fact, my operation is the same as you describe, but I actually receive data much slower than android, and I can't tell which is the problem. thank you
