### ISSUE TITLE
There are too many Block implicitly retains 'self' Warnings

### ISSUE THREAD

**Issue by Johnne25** [robbiehanson/CocoaAsyncSocket#597]
I have a brand new project, added your POD and got 147 warning.
Although they don't effect execution (I hope), could you remove them?

Block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behaviour.

The bulk of them are in GCDAsyncUdpSocket.m.

**Comment by RamblinWreck77** [comment]
+1 this is bothering me as well. Specifically there's a typo in the OP. Should say "Block" instead of lock.

**Comment by kdavydenko** [comment]
Same issue, we have 284 issues(warnings) in:
GCDAsyncSocket.m
GCDAsyncUdpSocket.m

**Comment by Teglgaard** [comment]
@Johnne25 @RamblinWreck77 @kdavydenko 
Any succes in solving this?

**Comment by maxencecornu** [comment]
Same for me ! Please update your pod

**Comment by Teglgaard** [comment]
@maxencecornu I have version 7.6.2 of cocoaasyncsocket and pods version 1.4.0 so everything is up to date

**Comment by maxencecornu** [comment]
@Teglgaard I meant i have 200+ warnings too because of this pod, and I asked the author to update it ;)

**Comment by chrisballinger** [comment]
Apologies for the snark, but instead of demanding someone else do work for
you for free, how about you take initiative and submit a pull request?

**Comment by RamblinWreck77** [comment]
@chrisballinger  I think he was more or less trying to bring it to bring it to a collaborator's attention, not "demand" it's fixed. 

Besides, we all have things that keep us busy and have to choose what to contribute to. Sometimes that choice is to find a project that doesn't ship with almost 200 warnings.

**Comment by seanm** [comment]
Besides, pull requests seem to be mostly ignored, ex: this one liner unmerged for almost 2 years:

https://github.com/robbiehanson/CocoaAsyncSocket/pull/417

**Comment by chrisballinger** [comment]
Sometimes PRs will fall through the cracks. As of right now I am the only active maintainer and would welcome any volunteers to apply, especially if your company relies on this software in production. 

CocoaPods stats show this library is used in ~76,500 apps, and is downloaded ~385,000 times per month... not counting those who use Carthage or integrate it directly. It really would be nice if some of those who depend on this software would be willing to step forward and help maintain the it.

**Comment by Dirk-** [comment]
@chrisballinger I am using CocoaAsyncSocket in one of my apps too. For me it just works, so (currently) I have no idea what to contribute other than that: Thank you!

**Comment by Teglgaard** [comment]
@chrisballinger I have made a pull request solving this. It is my first so bare with me.

**Comment by Johnne25** [comment]
I have updated my project and there are no longer any warnings.  Awesome work!!
