### ISSUE TITLE
func socket(_ socket : GCDAsyncSocket, didRead data:Data, withTag tag:Int) not firing

### ISSUE THREAD

**Issue by Johnne25** [robbiehanson/CocoaAsyncSocket#598]
I have been stuck on this forever it seems.
I have written a Windows VS2008 TCP server which gets socket connection.  You can then type a message and send it to the connection.

In iOS, it connects and the connection callback is fired.
However, when I send a message from Windows the didRead call back is not called.

Data is reaching iOS and a break point in - (void)doReadData shows it gets somethings.
However, the code goes down to 
			if (socketFDBytesAvailable > 0)
			{
				[self suspendReadSource];
			}
Which seems to suspend any further incoming messages and does not trigger the didRead callback.

**Comment by Johnne25** [comment]
You can close this issue as it seems it was a packet header issue on my end.  Once I combed through the code and implemented the correct headers on both sides everything started work.

**Comment by L1onKing** [comment]
@Johnne25 Can you please explain a little bit more about your header issue? It seems like I'm struggling with the same problem and can't figure out why. Thanks in advance!
