### ISSUE TITLE
Unable to receive UDP broadcast from other clients

### ISSUE THREAD

**Issue by EvePhil** [robbiehanson/CocoaAsyncSocket#609]
Hi guys!
Currently I come into a problem where I can only receive packet sent by the socket itself.When a broadcast is performed by another client in the same network nothing happens,no received packet displayed in Xcode and no didReceiveData callback is called.Though I'm pretty sure there is nothing wrong with the broadcast.
Below is the codes to receive packets,simple as the examples:
`    
    self.myGcdUdpSocket = [[GCDAsyncUdpSocket alloc] initWithDelegate:self delegateQueue:dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0)];

    NSError* err = nil;
    [self.myGcdUdpSocket enableBroadcast:true error:&err];
    [self.myGcdUdpSocket bindToPort:9999 error:&err];
    [self.myGcdUdpSocket beginReceiving:&err];
`

Is there any suggestions that might get it work?

**Comment by DavidTower** [comment]
hi EvePhil!
Have you solved your problem?
