### ISSUE TITLE
Unable to receive more than 1 packet

### ISSUE THREAD

**Issue by Johnne25** [robbiehanson/CocoaAsyncSocket#613]
I had a iOS 11 project working pretty good using another socket library.  However it didn't hand multiple sends in quick succession very well so I decided to go with this solution instead.

It was pretty easy update as I only changed my wrapper class to point to these methods instead.

The issue I am having is the sockets connect, the server sends the authentication packet to the device which is received and the events trigger.

However, after that no other data can be received by the device (iOS).  It can send data, just nothing is received.  The only changes I made were to the iOS app, server code remains the same.  I have put break points all over an none of them seem to be caught. 

Since this issue is pretty much a show stopper for everyone I can't believe I would be the 1st one to find it.  Which leads me to be believe its something with my environment.  

I am currently trimming down the code to the bare minimum required to reproduce it.

**Comment by acb** [comment]
@Johnne25 Interestingly enough I'm running into this same issue using a React Native library that wraps this library.  A server connection can send exactly 1 packet and all subsequent writes just seem to disappear, no errors thrown and no data received on the connected client.  The client can send data to the server just fine, but the server is unable to write back.

Please let me know if you find a solution!
