### ISSUE TITLE
DDLog.h not found when enabling logging

### ISSUE THREAD

**Issue by Johnne25** [robbiehanson/CocoaAsyncSocket#614]
I have added the CocoaLumberjack pod to my project.

When I enable logging for CocoaAsyncSocket I get a DDLog.h file not found error on line 50 of DCDAsyncSocket.m.  Any idea how go get past this error.

I need logging to try and resolve an issue.

Also if someone has some instructions on how to enable logging without changing line 39 to:
#define GCDAsyncSocketLoggingEnabled 1
I would appreciate it.  I haven't been successful in finding Swift 4 instructions on how to accomplish this.

**Comment by N1nomiya** [comment]
Same question!!
