### ISSUE TITLE
Local didConnect in "connect" method

### ISSUE THREAD

**Issue by Mahan3340** [robbiehanson/CocoaAsyncSocket#615]
Hi , can i achieve something like below currently ? 

socket.connect(toHost: "localhost", onPort: 5050, withTimeout: 15,completion { connected in 
  // do something right here 
})
I know this doesn't exit on the Lib but wanted to know that if there is another way to do this or not , the reason i need this is like I want to check if socket is connected or not to do some action and if its not connected , connect  and then get back here and retry this specific action , delegate methods are not helping for this specific need and I kinda dont wanna save my actions on something like a queue and call them again on Didconnect delegate method

**Comment by Johnne25** [comment]
Not sure if I understand the issue you are having.  The didConnection should fire as soon as a connection is made.  The socket.Connect(toHost) runs Async so I don't think you can have it waiting and returning only after a connection is made.

**Comment by Mahan3340** [comment]
@Johnne25 i dont want to do it async its just ok the way it is but connect method doesn't have something like tag so that I know who wanted socket to be connected and who called the "connect" method so that i can get back there and continue what I wanted to do , like : 
if(socket.IsConnected)
{
do the job
} else
{
connect socket and get back up there and try it again .
}
