### ISSUE TITLE
Attempting to connect while connected or accepting connections. Disconnect first.

### ISSUE THREAD

**Issue by quoctc** [robbiehanson/CocoaAsyncSocket#624]
this is full error.
cannot connect Error Domain=GCDAsyncSocketErrorDomain Code=1 "Attempting to connect `while connected or accepting connections. Disconnect first." UserInfo={NSLocalizedDescription=Attempting to connect while connected or accepting connections. Disconnect first.}`

After this error, I was restart async socket again like this:
```
self.asyncSocket?.setDelegate(nil, delegateQueue: nil)
self.asyncSocket = nil
self.queue = DispatchQueue(label: "SocketQueue")
 self.asyncSocket = GCDAsyncSocket(delegate: self, delegateQueue: queue)
```

But the error still happen.

Note: this happens when I disable and re-enable wifi, after wifi connected to my wifi socket server. I trying to create a connection to the socket but It through the error. 
Then, I terminated the app and open the app again, I still cannot connect to socket server till I go to setting disconnect wifi and re-connect again.

**Comment by jackyshan** [comment]
if _mSocket?.isDisconnected == false {
                _mSocket?.disconnect()
            }

disconnect first，and restart socket
