### ISSUE TITLE
socket connect timeout when using T-Mobile

### ISSUE THREAD

**Issue by zcinclude** [robbiehanson/CocoaAsyncSocket#626]
我在使用这个框架的时候遇到了一个谜一样的问题，至今没有解决思路。
I encountered a mystery problem when using this framework, and I haven’t resolved the idea so far.

问题是这样的：我使用这个框架通过WiFi与智能设备构建socket连接，在正常情况下都是可以正常使用的，但是当用户使用T-Mobile运营商的的时候socket就连接超时，使用美国其他的运营商和中国的运营商的都可以正常连接，我们甚至把T-Mobile的卡拿到中国来使用（此时中国移动提供漫游服务）也可以正常连接。更让人不解的是同一台手机关闭蜂窝数据按钮或者开启飞行模式后又都可以正常连接。
The problem is this: I use this framework to build socket connections via WiFi and smart devices, which are normally available under normal conditions, but when the user uses the T-Mobile operator, the socket connection times out, using the US other Operators and operators in China can all connect normally. We even take T-Mobile's cards to China to use (when China Mobile provides roaming services). What is even more puzzling is that the same mobile phone can close the cellular data button or turn on the airplane mode.

另外我们使用CFSocket写了个demo运行在上述连接不上的手机环境下可以连接成功。
In addition, we use CFSocket to write a demo to run in the above connection can not be connected to the phone environment can be successfully connected.

请帮助我解决这个问题。
Please help me to solve this problem.

**Comment by ryanstout** [comment]
@zcinclude I think we're seeing the same issue on tmobile, were you able to resolve this?

**Comment by zcinclude** [comment]
@ryanstout 是的，问题就是由于T-Mobile不支持解析IPV6触发的。
问题的关键在于 + (NSMutableArray *)lookupHost:(NSString *)host port:(uint16_t)port error:(NSError **)errPtr;这个方法。

请使用下面的分类来临时解决这个问题。记得替换IP地址。

`//
//  GCDAsyncSocket+Override.h
//  AsyncSocketTest
//
//  Created by ZC on 2018/5/31.
//  Copyright © 2018年 Hikvision Automotive Technology Co., Ltd. All rights reserved.
//

#import "GCDAsyncSocket.h"

@interface GCDAsyncSocket (Override)
/*
 此分类方法用于解决某些不支持IPV4的运营商解析IP地址时无法返回IPV4地址而导致设备连接失败的问题，目前设备只支持IPV4的访问
 */
/**
 * The address lookup utility used by the class.
 * This method is synchronous, so it's recommended you use it on a background thread/queue.
 *
 * The special strings "localhost" and "loopback" return the loopback address for IPv4 and IPv6.
 *
 * @returns
 *   A mutable array with all IPv4 and IPv6 addresses returned by getaddrinfo.
 *   The addresses are specifically for TCP connections.
 *   You can filter the addresses, if needed, using the other utility methods provided by the class.
 **/
+ (nullable NSMutableArray *)lookupHost:(NSString *)host port:(uint16_t)port error:(NSError **)errPtr;

@end
`
`
//
//  GCDAsyncSocket+Override.m
//  AsyncSocketTest
//
//  Created by ZC on 2018/5/31.
//  Copyright © 2018年 Hikvision Automotive Technology Co., Ltd. All rights reserved.
//


#import "GCDAsyncSocket+Override.h"
#import <netinet/in.h>
#import <netdb.h>
#import <sys/socket.h>
#import <arpa/inet.h>

@implementation GCDAsyncSocket (Override)

+ (NSMutableArray *)lookupHost:(NSString *)host port:(uint16_t)port error:(NSError **)errPtr
{
//    LogTrace();
    
    NSMutableArray *addresses = nil;
    NSError *error = nil;
    
    //**********************
    // 通过你需要连接的IP地址来构建IPV4的addresses
    if ([host containsString:@"192.168.22.1"]) {
        struct sockaddr_in nativeAddr4;
        nativeAddr4.sin_len         = sizeof(struct sockaddr_in);
        nativeAddr4.sin_family      = AF_INET;
        nativeAddr4.sin_port        = htons(port);
        nativeAddr4.sin_addr.s_addr = inet_addr([host UTF8String]);
        memset(&(nativeAddr4.sin_zero), 0, sizeof(nativeAddr4.sin_zero));
        
        NSData *address4 = [NSData dataWithBytes:&nativeAddr4 length:sizeof(nativeAddr4)];
        
        addresses = [NSMutableArray arrayWithCapacity:1];
        [addresses addObject:address4];
        return addresses;
    }
    //**********************
    
    if ([host isEqualToString:@"localhost"] || [host isEqualToString:@"loopback"])
    {
        // Use LOOPBACK address
        struct sockaddr_in nativeAddr4;
        nativeAddr4.sin_len         = sizeof(struct sockaddr_in);
        nativeAddr4.sin_family      = AF_INET;
        nativeAddr4.sin_port        = htons(port);
        nativeAddr4.sin_addr.s_addr = htonl(INADDR_LOOPBACK);
        memset(&(nativeAddr4.sin_zero), 0, sizeof(nativeAddr4.sin_zero));
        
        struct sockaddr_in6 nativeAddr6;
        nativeAddr6.sin6_len        = sizeof(struct sockaddr_in6);
        nativeAddr6.sin6_family     = AF_INET6;
        nativeAddr6.sin6_port       = htons(port);
        nativeAddr6.sin6_flowinfo   = 0;
        nativeAddr6.sin6_addr       = in6addr_loopback;
        nativeAddr6.sin6_scope_id   = 0;
        
        // Wrap the native address structures
        
        NSData *address4 = [NSData dataWithBytes:&nativeAddr4 length:sizeof(nativeAddr4)];
        NSData *address6 = [NSData dataWithBytes:&nativeAddr6 length:sizeof(nativeAddr6)];
        
        addresses = [NSMutableArray arrayWithCapacity:2];
        [addresses addObject:address4];
        [addresses addObject:address6];
    }
    else
    {
        NSString *portStr = [NSString stringWithFormat:@"%hu", port];
        
        struct addrinfo hints, *res, *res0;
        
        memset(&hints, 0, sizeof(hints));
        hints.ai_family   = PF_UNSPEC;
        hints.ai_socktype = SOCK_STREAM;
        hints.ai_protocol = IPPROTO_TCP;
        
        int gai_error = getaddrinfo([host UTF8String], [portStr UTF8String], &hints, &res0);
        
        if (gai_error)
        {
            error = [self gaiError:gai_error];
        }
        else
        {
            NSUInteger capacity = 0;
            for (res = res0; res; res = res->ai_next)
            {
                if (res->ai_family == AF_INET || res->ai_family == AF_INET6) {
                    capacity++;
                }
            }
            
            addresses = [NSMutableArray arrayWithCapacity:capacity];
            
            for (res = res0; res; res = res->ai_next)
            {
                if (res->ai_family == AF_INET)
                {
                    // Found IPv4 address.
                    // Wrap the native address structure, and add to results.
                    
                    NSData *address4 = [NSData dataWithBytes:res->ai_addr length:res->ai_addrlen];
                    [addresses addObject:address4];
                }
                else if (res->ai_family == AF_INET6)
                {
                    // Fixes connection issues with IPv6
                    // https://github.com/robbiehanson/CocoaAsyncSocket/issues/429#issuecomment-222477158
                    
                    // Found IPv6 address.
                    // Wrap the native address structure, and add to results.
                    
                    struct sockaddr_in6 *sockaddr = (struct sockaddr_in6 *)res->ai_addr;
                    in_port_t *portPtr = &sockaddr->sin6_port;
                    if ((portPtr != NULL) && (*portPtr == 0)) {
                        *portPtr = htons(port);
                    }
                    
                    NSData *address6 = [NSData dataWithBytes:res->ai_addr length:res->ai_addrlen];
                    [addresses addObject:address6];
                }
            }
            freeaddrinfo(res0);
            
            if ([addresses count] == 0)
            {
                error = [self gaiError:EAI_FAIL];
            }
        }
    }
    
    if (errPtr) *errPtr = error;
    return addresses;
}

+ (NSError *)gaiError:(int)gai_error
{
    NSString *errMsg = [NSString stringWithCString:gai_strerror(gai_error) encoding:NSASCIIStringEncoding];
    NSDictionary *userInfo = [NSDictionary dictionaryWithObject:errMsg forKey:NSLocalizedDescriptionKey];
    
    return [NSError errorWithDomain:@"kCFStreamErrorDomainNetDB" code:gai_error userInfo:userInfo];
}

@end
`

**Comment by zcinclude** [comment]
@ryanstout 是的，问题就是由于T-Mobile不支持解析IPV6触发的。
问题的关键在于 + (NSMutableArray *)lookupHost:(NSString *)host port:(uint16_t)port error:(NSError **)errPtr;这个方法。

请使用下面的分类来临时解决这个问题。记得替换IP地址。


//
//  GCDAsyncSocket+Override.h
//  AsyncSocketTest
//
//  Created by ZC on 2018/5/31.
//  Copyright © 2018年 Hikvision Automotive Technology Co., Ltd. All rights reserved.
//

#import "GCDAsyncSocket.h"

@interface GCDAsyncSocket (Override)
/*
 此分类方法用于解决某些不支持IPV4的运营商解析IP地址时无法返回IPV4地址而导致设备连接失败的问题，目前设备只支持IPV4的访问
 */
/**
 * The address lookup utility used by the class.
 * This method is synchronous, so it's recommended you use it on a background thread/queue.
 *
 * The special strings "localhost" and "loopback" return the loopback address for IPv4 and IPv6.
 *
 * @returns
 *   A mutable array with all IPv4 and IPv6 addresses returned by getaddrinfo.
 *   The addresses are specifically for TCP connections.
 *   You can filter the addresses, if needed, using the other utility methods provided by the class.
 **/
+ (nullable NSMutableArray *)lookupHost:(NSString *)host port:(uint16_t)port error:(NSError **)errPtr;

@end










//
//  GCDAsyncSocket+Override.m
//  AsyncSocketTest
//
//  Created by ZC on 2018/5/31.
//  Copyright © 2018年 Hikvision Automotive Technology Co., Ltd. All rights reserved.
//


#import "GCDAsyncSocket+Override.h"
#import <netinet/in.h>
#import <netdb.h>
#import <sys/socket.h>
#import <arpa/inet.h>

@implementation GCDAsyncSocket (Override)

+ (NSMutableArray *)lookupHost:(NSString *)host port:(uint16_t)port error:(NSError **)errPtr
{
//    LogTrace();
    
    NSMutableArray *addresses = nil;
    NSError *error = nil;
    
    //**********************
    // 通过你需要连接的IP地址来构建IPV4的addresses
    if ([host containsString:@"192.168.22.1"]) {
        struct sockaddr_in nativeAddr4;
        nativeAddr4.sin_len         = sizeof(struct sockaddr_in);
        nativeAddr4.sin_family      = AF_INET;
        nativeAddr4.sin_port        = htons(port);
        nativeAddr4.sin_addr.s_addr = inet_addr([host UTF8String]);
        memset(&(nativeAddr4.sin_zero), 0, sizeof(nativeAddr4.sin_zero));
        
        NSData *address4 = [NSData dataWithBytes:&nativeAddr4 length:sizeof(nativeAddr4)];
        
        addresses = [NSMutableArray arrayWithCapacity:1];
        [addresses addObject:address4];
        return addresses;
    }
    //**********************
    
    if ([host isEqualToString:@"localhost"] || [host isEqualToString:@"loopback"])
    {
        // Use LOOPBACK address
        struct sockaddr_in nativeAddr4;
        nativeAddr4.sin_len         = sizeof(struct sockaddr_in);
        nativeAddr4.sin_family      = AF_INET;
        nativeAddr4.sin_port        = htons(port);
        nativeAddr4.sin_addr.s_addr = htonl(INADDR_LOOPBACK);
        memset(&(nativeAddr4.sin_zero), 0, sizeof(nativeAddr4.sin_zero));
        
        struct sockaddr_in6 nativeAddr6;
        nativeAddr6.sin6_len        = sizeof(struct sockaddr_in6);
        nativeAddr6.sin6_family     = AF_INET6;
        nativeAddr6.sin6_port       = htons(port);
        nativeAddr6.sin6_flowinfo   = 0;
        nativeAddr6.sin6_addr       = in6addr_loopback;
        nativeAddr6.sin6_scope_id   = 0;
        
        // Wrap the native address structures
        
        NSData *address4 = [NSData dataWithBytes:&nativeAddr4 length:sizeof(nativeAddr4)];
        NSData *address6 = [NSData dataWithBytes:&nativeAddr6 length:sizeof(nativeAddr6)];
        
        addresses = [NSMutableArray arrayWithCapacity:2];
        [addresses addObject:address4];
        [addresses addObject:address6];
    }
    else
    {
        NSString *portStr = [NSString stringWithFormat:@"%hu", port];
        
        struct addrinfo hints, *res, *res0;
        
        memset(&hints, 0, sizeof(hints));
        hints.ai_family   = PF_UNSPEC;
        hints.ai_socktype = SOCK_STREAM;
        hints.ai_protocol = IPPROTO_TCP;
        
        int gai_error = getaddrinfo([host UTF8String], [portStr UTF8String], &hints, &res0);
        
        if (gai_error)
        {
            error = [self gaiError:gai_error];
        }
        else
        {
            NSUInteger capacity = 0;
            for (res = res0; res; res = res->ai_next)
            {
                if (res->ai_family == AF_INET || res->ai_family == AF_INET6) {
                    capacity++;
                }
            }
            
            addresses = [NSMutableArray arrayWithCapacity:capacity];
            
            for (res = res0; res; res = res->ai_next)
            {
                if (res->ai_family == AF_INET)
                {
                    // Found IPv4 address.
                    // Wrap the native address structure, and add to results.
                    
                    NSData *address4 = [NSData dataWithBytes:res->ai_addr length:res->ai_addrlen];
                    [addresses addObject:address4];
                }
                else if (res->ai_family == AF_INET6)
                {
                    // Fixes connection issues with IPv6
                    // https://github.com/robbiehanson/CocoaAsyncSocket/issues/429#issuecomment-222477158
                    
                    // Found IPv6 address.
                    // Wrap the native address structure, and add to results.
                    
                    struct sockaddr_in6 *sockaddr = (struct sockaddr_in6 *)res->ai_addr;
                    in_port_t *portPtr = &sockaddr->sin6_port;
                    if ((portPtr != NULL) && (*portPtr == 0)) {
                        *portPtr = htons(port);
                    }
                    
                    NSData *address6 = [NSData dataWithBytes:res->ai_addr length:res->ai_addrlen];
                    [addresses addObject:address6];
                }
            }
            freeaddrinfo(res0);
            
            if ([addresses count] == 0)
            {
                error = [self gaiError:EAI_FAIL];
            }
        }
    }
    
    if (errPtr) *errPtr = error;
    return addresses;
}

+ (NSError *)gaiError:(int)gai_error
{
    NSString *errMsg = [NSString stringWithCString:gai_strerror(gai_error) encoding:NSASCIIStringEncoding];
    NSDictionary *userInfo = [NSDictionary dictionaryWithObject:errMsg forKey:NSLocalizedDescriptionKey];
    
    return [NSError errorWithDomain:@"kCFStreamErrorDomainNetDB" code:gai_error userInfo:userInfo];
}

@end

**Comment by zcinclude** [comment]
@ryanstout是的，问题就是由于T-Mobile不支持解析IPV6触发的。
问题的关键在于+（NSMutableArray *）lookupHost：（NSString *）主机端口：（uint16_t）端口错误：（NSError **）errPtr;这个方法。

请使用下面的分类来临时解决这个问题。记得替换IP地址。

[GCDAsyncSocket+Override.zip](https://github.com/robbiehanson/CocoaAsyncSocket/files/2187107/GCDAsyncSocket%2BOverride.zip)
