### ISSUE TITLE
Error Domain=NSPOSIXErrorDomain Code=64,3,53;how to solve?

### ISSUE THREAD

**Issue by OneWang** [robbiehanson/CocoaAsyncSocket#627]
Error Domain=NSPOSIXErrorDomain Code=64 "Host is down" UserInfo={NSLocalizedDescription=Host is down, NSLocalizedFailureReason=Error in connect() function}
Error Domain=GCDAsyncSocketErrorDomain Code=3 "Attempt to connect to host timed out" UserInfo={NSLocalizedDescription=Attempt to connect to host timed out}
Error Domain=NSPOSIXErrorDomain Code=53 "Software caused connection abort" UserInfo={NSLocalizedDescription=Software caused connection abort, NSLocalizedFailureReason=Error in connect() function}

**Comment by DavidTower** [comment]
hi OneWang！
Have you solved your problem?
