### ISSUE TITLE
断开重练会崩溃在这，我用的是SRWebSocket，不影响吧？

### ISSUE THREAD

**Issue by kangtian** [robbiehanson/CocoaAsyncSocket#631]
![3a5477ac-81a5-4661-9fc5-926d07a81484](https://user-images.githubusercontent.com/13611448/41082922-6d2b416a-6a62-11e8-814c-6a1d8bac9489.png)

**Comment by Jackielc** [comment]
_dispatch_call_block_end_release

**Comment by kangtian** [comment]
不懂
