### ISSUE TITLE
There are periods of time in which SSLHandshake(sslContext) always returns errSSLWouldBlock

### ISSUE THREAD

**Issue by apavalache** [robbiehanson/CocoaAsyncSocket#632]
What I'm doing so far is creating the socket, connecting to the host via the mobile network interface "pdp_ip0", starting TLS with nil as parameter. 

```
socket = GCDAsyncSocket(delegate: self, delegateQueue: DispatchQueue.main)
do {
    try socket?.connect(toAddress: address, viaInterface: "pdp_ip0", withTimeout: -1.0)
    socket?.startTLS(nil)
}           
```

From logging around in GCDAsyncSocket.m, there seem to be periods of time in which the socket will do everything right, but then there are periods where it gets into a sort of inactive state after SSLHandshake(sslContext) returns errSSLWouldBlock. These periods seem to be rather random. Even after restarting the phone, it's not guaranteed that SSLHandshake function will succeed.

When it does succeed, it seems that [self ssl_continueSSLHandshake] is automatically called 2-3 times and then continues the work with no other issues. I tries manually triggering this method every 1 second to see if it would produce a different result, but I keep getting errSSLWouldBlock from SSLHandshake(...)

didConnect(...) delegate method gets called, but during those problematic periods, it won't reach didSecure(...)

Is this a known issue? Is there anything that can be done to make it more reliable or are there any alternatives?

**Comment by ppaulojr** [comment]
happens to me too on pdp_ip0

**Comment by remiMargaria** [comment]
i'm experiencing the same on pdp_ip0

**Comment by matanyaofan** [comment]
Happened to me too. I found it happens while I read from the connection or write to it after startTls before socketDidSecure message.
