### ISSUE TITLE
Can't connect Socket

### ISSUE THREAD

**Issue by hoangson1989** [robbiehanson/CocoaAsyncSocket#633]
I have a Hardware Device (HD) what broadcast a local wifi,I used my tcp app to connect to HD and read/write data with it. The App using Cellular to update the data from HD to server.Everything work fine for a longtime.
But recently,I have a user (iPhone 7+  iOS 11.4) who getting error "Attempt to connect to host timed out" when create socket with HD.
There's a weird thing when i logged the interfaces which have "sa_family" == AF_INET, the user iphone only have lo0 & en0.
While with the other iphones (11.4) I have, the result is lo0,pdp_ip0,en0,en3.

Do anyone get same issue and how to fix it ?

**Comment by hoangson1989** [comment]
I use the "AsyncSocket" replace for "GCDAsyncSocket".the socket work fine.

**Comment by bigliang-hello** [comment]
I use "AsyncSocket", but it still doesn't work. @hoangson1989

**Comment by hoangson1989** [comment]
@bigliang-hello could you tell me more about your situation ?
did you try using CFStream with CFStreamCreatePairWithSocketToHost?
