### ISSUE TITLE
socket创建在主队列时传输大文件卡顿

### ISSUE THREAD

**Issue by lixiayi** [robbiehanson/CocoaAsyncSocket#634]
如果在主队列创建socket，比如按下面的写法：
_socket = [[GCDAsyncSocket alloc] initWithDelegate:self delegateQueue:dispatch_get_main_queue()]; 创建并初始化socket后，传输大的文件比如：图片，视频等会APP界面会卡顿；
尝试把初始化socket放到全局队列里面，但是收发数据会错乱；
请问怎么处理比较好？

**Comment by ChenChuanzhen** [comment]
请问你大文件写入会不会内存积累，我现在发生内存积累了，该怎么办？

**Comment by lixiayi** [comment]
你说的内存积累是内存占用高吗，我现在创建的时候放在自己创建的串行队列就不卡了，内存也比较正常。
