### ISSUE TITLE
Send hexString Data through UDP. 

### ISSUE THREAD

**Issue by coderli01** [robbiehanson/CocoaAsyncSocket#637]
I am trying to send a hexString data through UDP to an wifi camera, which will response while getting correct data. My code is shown below. However I can't get any response from my wifi camera. 

`NSString *sendMsg = @"6745000005000000000000000000000000000000000000001400000067450000140000000A";
NSData *bytes = [sendMsg dataUsingEncoding:NSUTF16BigEndianStringEncoding];
NSString *host = @"255.255.255.255";
[self.udpSocket sendData:bytes toHost:host port:ListenPort withTimeout:-1 tag:1];`

Beside, I've try send my data through PacketSender (an app can send UDP data), which has a correct response.
![image](https://user-images.githubusercontent.com/33228104/41593138-a2f5f018-73f1-11e8-83af-b31a19f1f387.png)

Can anyone show me some light about this issue?

**Comment by halmueller** [comment]
Give it a try running through Charles Proxy and see if the camera is sending anything back.

**Comment by coderli01** [comment]
Problem has been solved. The problem is while converting NSString to NSData. It's hex string which need to convert to NSData. Below is my code which works.

`- (NSData *)dataFromHexString:(NSString *)hexString {
	NSAssert((hexString.length > 0) && (hexString.length % 2 == 0), @"hexString.length mod 2 != 0");
	NSMutableData *data = [[NSMutableData alloc] init];
	for (NSUInteger i=0; i<hexString.length; i+=2) {
		NSRange tempRange = NSMakeRange(i, 2);
		NSString *tempStr = [hexString substringWithRange:tempRange];
		NSScanner *scanner = [NSScanner scannerWithString:tempStr];
		unsigned int tempIntValue;
		[scanner scanHexInt:&tempIntValue];
		[data appendBytes:&tempIntValue length:1];
	}
	return data;
}`
