### ISSUE TITLE
Network.framework support

### ISSUE THREAD

**Issue by akempgen** [robbiehanson/CocoaAsyncSocket#639]
I know it's still early, but any plans to support the new Network.framework from this year's WWDC? 😄

**Comment by gavineadie** [comment]
Is there any point?  Seems like CocoaAsyncSocket offered a very similar level of service to what Network will .. and Network’s feature set is richer (speaking as a UDP user) ..

**Comment by akempgen** [comment]
As a migration path for apps that target macOS < Mojave, so they can use Network on Mojave and use sockets on older systems. And that switch can be in two places, in the app using CocoaAsyncSocket, or in CocoaAsyncSocket itself, making it transparent to the app.

**Comment by svdo** [comment]
Also, there are going to be gaps: Network.framework will not support UDP multicast for one thing.
