### ISSUE TITLE
Incorrect BSD License

### ISSUE THREAD

**Issue by WPCTW** [robbiehanson/CocoaAsyncSocket#642]
Please check the License file, because the License does not include full text of BSD license.
Normally, a BSD license would refer to BSD 2-Clause license or BSD 3-Clause license.
Please refer to the following links:

BSD 2-Clause License (https://opensource.org/licenses/BSD-2-Clause)
BSD 3-Clause License (https://opensource.org/licenses/BSD-3-Clause)

**Comment by halmueller** [comment]
Perhaps you could submit a PR?

Hal
