### ISSUE TITLE
Invalid Certificate Chain while connecting with TLS

### ISSUE THREAD

**Issue by hassancielo** [robbiehanson/CocoaAsyncSocket#645]
Hi,
 I have converted key file and client cer to pfx file and used following code to generate certificate array.

NSString *clientKeyPath = [[NSBundle mainBundle] pathForResource:@"certificate" ofType:@"pfx"];
    NSData* clientKeyData = [NSData dataWithContentsOfFile:clientKeyPath];
    NSLog(@"key : %@",[[NSString alloc] initWithData:clientKeyData encoding:NSASCIIStringEncoding]);
    
    CFDataRef inPKCS12Data = (CFDataRef)CFBridgingRetain(clientKeyData);
    CFStringRef password = CFSTR("abc");
    const void *keys[] = { kSecImportExportPassphrase };
    const void *values[] = { password };
    CFDictionaryRef options = CFDictionaryCreate(NULL, keys, values, 1, NULL, NULL);
    
    CFArrayRef items = CFArrayCreate(NULL, 0, 0, NULL);
    
    OSStatus securityError = SecPKCS12Import(inPKCS12Data, options, &items);
    CFRelease(options);
    CFRelease(password);
    
    if(securityError == errSecSuccess)
        NSLog(@"Success opening p12 certificate.");
    
    CFDictionaryRef identityDict = CFArrayGetValueAtIndex(items, 0);
    SecIdentityRef myIdent = (SecIdentityRef)CFDictionaryGetValue(identityDict,
                                                                  kSecImportItemIdentity);
    
    
 
    const void *ref[] = {myIdent};
    CFArrayRef myCerts = CFArrayCreate(NULL, ref, 1, NULL);
    NSArray *array = CFBridgingRelease(myCerts);
    
The socket disconnects immediately saying "Invalid Certificate Chain (9807)".
I am not passing CA certificate as it is not required on the server side.
Please guide.

**Comment by Mononster** [comment]
Did you solve the issue here? @hassancielo
