### ISSUE TITLE
GCDAsyncSocket accept(onPort:) not opening up port

### ISSUE THREAD

**Issue by devon-stanley** [robbiehanson/CocoaAsyncSocket#646]
I'm trying to get the basic echo server example working with Swift 4.2 but it looks like there is something wrong. 
I've scanned my device's ip with a network tool and it doesn't show the port I specified as open (using  `nmap -p 65023 device_ip_here`)

I'm initialize the socket in my ViewController's viewDidAppear method like so:
```
// Save the socket so it doesn't get deallocated
self.listenSocket = GCDAsyncSocket(delegate: self, delegateQueue: DispatchQueue.main)

do {
    try listenSocket.accept(onPort: 65023)
}
catch {
    print("Couldn't listen on port: \(port)")
}
```

I also implemented the didAcceptNewSocket and didRead delegate methods as such:
```
func socket(_ sock: GCDAsyncSocket, didAcceptNewSocket newSocket: GCDAsyncSocket) {
    print("Somebody connected!")
    
    newSocket.readData(to: Data(), withTimeout: 15.0, tag: 123)
}

func socket(_ sock: GCDAsyncSocket, didRead data: Data, withTag tag: Int) {
    guard let contents = String(data: data, encoding: .utf8) else { return }
    print(contents)
}
```

Am I missing something? It seems odd to me that this code doesn't work out of the box...

**Comment by devon-stanley** [comment]
Looks like I was misusing the `to:` parameter for the read method.

**Comment by joysonjson** [comment]
> Looks like I was misusing the `to:` parameter for the read method.
Hi Devon can you please share you working code. Even I am facing the same issue, Thank you.
