### ISSUE TITLE
gcdasyncsocket in swift is not executing didreceive method

### ISSUE THREAD

**Issue by vincevillena** [robbiehanson/CocoaAsyncSocket#649]
I'm encountering problems with GCDAsyncSocket in Swift:

the didReceive does not execute
and I'm having problems reading the text data being sent by the server.

mSocket.readData(to: Data(), withTimeout: -1, maxLength: 768, tag: 0)

the output and code is in here [
https://stackoverflow.com/questions/51406530/gcdasyncsocket-in-swift-is-not-executing-didreceive-method](url)

many thanks in advance

**Comment by Michlong** [comment]
Have you solved this?

**Comment by starhblab** [comment]
@vincevillena  please try this:
`socket.readData(withTimeout: -1, tag: 1)`

and debug at:
`func socket(_ sock: GCDAsyncSocket, didRead data: Data, withTag tag: Int)`
