### ISSUE TITLE
-[GCDAsyncWritePacket bytes]: unrecognized selector sent to instance 0x1cc24f4e0

### ISSUE THREAD

**Issue by ghost** [robbiehanson/CocoaAsyncSocket#655]
The program crashed here, I am confused about the type change of the object.

GCDAsyncSocket.m -6229

**Comment by DeliriousLee** [comment]
the way you ask??!you must be  kidding me !

**Comment by DeliriousLee** [comment]
your explaination about your question,you must be kidding me !

**Comment by seanm** [comment]
Have you tried NSZombie, guard malloc, address sanitizer, or the like?
