### ISSUE TITLE
Issue inside - (void)connectSocket:(int)socketFD address:(NSData *)address stateIndex:(int)aStateIndex method

### ISSUE THREAD

**Issue by sajib-ghoshInnofied** [robbiehanson/CocoaAsyncSocket#656]
Hi, 

There is a crash inside this method: 

> - (void)connectSocket:(int)socketFD address:(NSData *)address stateIndex:(int)aStateIndex 

in this line: 
> int result = connect(socketFD, (const struct sockaddr *)[address bytes], (socklen_t)[address length]);

My current version is: 7.5.1
I am attaching Crashlytics crash report

![screen shot 2018-09-06 at 3 07 07 pm](https://user-images.githubusercontent.com/15829311/45149859-2967d600-b1e8-11e8-838d-ac10bb86e987.png)

Please look into this.
Thanks in advance.

**Comment by seanm** [comment]
Could you provide a reproducible example of the crash?  (Otherwise, I wouldn't expect open source volunteers to debug this for you.)

**Comment by sajib-ghoshInnofied** [comment]
I can't reproduce the crash. I will let you know if I can reproduce. Have you seen this crash before (in this line)?

**Comment by seanm** [comment]
As it looks like a memory error, you might try with Address Sanitizer, valgrind, guard malloc, or similar.
