### ISSUE TITLE
Sometimes crashes in CGDAsyncSocket.m (row: 7494)

### ISSUE THREAD

**Issue by iRory** [robbiehanson/CocoaAsyncSocket#657]
libobjc.A.dylib | objc_object::release() + 16
-- | --
1 | __destroy_helper_block_ (GCDAsyncSocket.m:7494)
2 | __destroy_helper_block_ (GCDAsyncSocket.m:7494)
3 libsystem_blocks.dylib | _Block_release + 152
4 libdispatch.dylib | __dispatch_client_callout + 16
5 libdispatch.dylib | __dispatch_queue_serial_drain$VARIANT$mp + 608
6 libdispatch.dylib | __dispatch_queue_invoke$VARIANT$mp + 336
7 libdispatch.dylib | __dispatch_root_queue_drain_deferred_wlh$VARIANT$mp + 340
8 libdispatch.dylib | __dispatch_workloop_worker_thread$VARIANT$mp + 668
9 libsystem_pthread.dylib | _pthread_wqthread + 860

{
			NSError *error = (__bridge_transfer  NSError *)CFReadStreamCopyError(stream);
			
			if (error == nil && type == kCFStreamEventEndEncountered)
			{
				error = [asyncSocket connectionClosedError];
			}
			
			dispatch_async(asyncSocket->socketQueue, ^{ @autoreleasepool {
				
				LogCVerbose(@"CFReadStreamCallback - Other");
				
				if (asyncSocket->readStream != stream)
					return_from_block;
				
				if ((asyncSocket->flags & kStartingReadTLS) && (asyncSocket->flags & kStartingWriteTLS))
				{
					[asyncSocket cf_abortSSLHandshake:error];
				}
				else
				{
					[asyncSocket closeWithError:error];
				}
			}});
			
			break;
		}

**Comment by msh940620** [comment]
I also found this crash. Have you found a solution.thanks.

**Comment by msh940620** [comment]
I found it happened in wifi to 4g，i try to use ‘disconnectAfterReadingAndWriting’  close socket . I want to know，are you also at this time crash?

**Comment by halmueller** [comment]
If someone can post source code for a reliably reproducible case, I have some time this week to look into it. But please start me with a reliable crasher, not just a stack trace. 

Hal Mueller 
halmueller@gmail.com

**Comment by halmueller** [comment]
By which I mean: a self contained Xcode project that always crashes immediately when I load it into current Xcode on Mojave and press Command-R. 

Hal Mueller 
halmueller@gmail.com

**Comment by msh940620** [comment]
> If someone can post source code for a reliably reproducible case, I have some time this week to look into it. But please start me with a reliable crasher, not just a stack trace. Hal Mueller halmueller@gmail.com
> […](#)

Thank you for your reply. But the frequency of crash is not frequent. The probability of this crash on my project happening near one in a hundred.But in our statistical it also happened in user change their Internet connection.
I think it crash in i try to close socket by 'disconnectAfterReadingAndWriting' and  set my object's asyncSocket is nil. Maybe this time asyncSocket has been destroyed by ARC, but i use    'disconnectAfterReadingAndWriting' make 'CFReadStreamCallback' also is called.
I try to check asyncSocket is used before 'dispatch_async(asyncSocket->socketQueue, ^{ @autoreleasepool {' and use 'disconnect' replace 'disconnectAfterReadingAndWriting'.
I'm going to modify it and go into production mode to see the effect.
