### ISSUE TITLE
Error in connect() function,Error Domain=NSPOSIXErrorDomain Code=0

### ISSUE THREAD

**Issue by zhudongqin** [robbiehanson/CocoaAsyncSocket#658]
Error Domain=NSPOSIXErrorDomain Code=0 "Undefined error: 0" UserInfo={NSLocalizedDescription=Undefined error: 0, NSLocalizedFailureReason=Error in connect() function.
Can you help me to solve this problem? thank you!

**Comment by AQ-TeppeiKikuchi** [comment]
I also get this error in the function that "func socketDidDisconnect(_ sock: GCDAsyncSocket, withError err: Error?)"

Error Domain=NSPOSIXErrorDomain Code=0 "Undefined error: 0" UserInfo={NSLocalizedDescription=Undefined error: 0, NSLocalizedFailureReason=Error in connect() function}

Need help...
