### ISSUE TITLE
Have a very weird log, after that cannot connect anymore

### ISSUE THREAD

**Issue by cctv1237** [robbiehanson/CocoaAsyncSocket#660]
There's an issue about connect to a server and close connect, sometimes this log will appear:
`2018-10-23 23:28:40.107757+0800 AppName[5247:1181239] [] [C9 192.168.123.142:9100 tcp, local: 192.168.123.64:59733, legacy-socket, server] cannot start after being torn down, in state cancelled`
After that socket cannot be reconnect, anyone see it before?

**Comment by ppaulojr** [comment]
I see that too.
```[C17 IPv4#5846fd68:80 udp, tls, indefinite, no cellular] cannot start after being torn down, in state cancelled```

**Comment by ppaulojr** [comment]
The `Network.framework` is very poorly documented.
