### ISSUE TITLE
startTLS doesn't work for me

### ISSUE THREAD

**Issue by ws752958369** [robbiehanson/CocoaAsyncSocket#661]
Pod Using CocoaAsyncSocket (7.6.3)

- (void)openClient
{
    dispatch_queue_t delegateQueue = dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0);
    self.clientSocket = [[GCDAsyncSocket alloc] initWithDelegate:self delegateQueue:delegateQueue];
    [self.clientSocket setIPv4PreferredOverIPv6:NO];
    
    NSError *error;
    BOOL isConnect = [self.clientSocket connectToHost:@"127.0.0.1" onPort:5036 error:&error];
    if (!isConnect) {
        NSLog(@"连接失败,:%@",error);
    }else{
        NSLog(@"连接成功");
        NSMutableDictionary *settings = [[NSMutableDictionary alloc] init];
        
        [settings setObject:[NSNumber numberWithBool:YES]
                     forKey:GCDAsyncSocketManuallyEvaluateTrust];
        
        [self.clientSocket startTLS:settings];
    }
}
when i call startTLS method,the delegate mehod :
-(void)socket:(GCDAsyncSocket *)sock didReceiveTrust:(SecTrustRef)trust completionHandler:(void (^)(BOOL))completionHandler.
it doesn't work too.
And it will occur a error "Error Domain=kCFStreamErrorDomainSSL Code=-9847 "(null)" UserInfo={NSLocalizedRecoverySuggestion=Error code definition can be found in Apple's SecureTransport.h}".
So How can i solve this problem? if you can help me solve it,i will be thanking for you very much!

**Comment by ws752958369** [comment]
if i couldn't use self-signed Validate cer,i should not call startTLS.

**Comment by ws752958369** [comment]
in this project,i must use self-signed certificate.

**Comment by alisolutions** [comment]
We are also getting same issue, please help.
