### ISSUE TITLE
nw_connection_copy_connected_path ERROR

### ISSUE THREAD

**Issue by ligui-iOS** [robbiehanson/CocoaAsyncSocket#667]
after connected,I meet this error "[] nw_connection_copy_connected_path [C1] Client called nw_connection_copy_connected_path on unconnected nw_connection" "tcp_connection_is_cellular No connected path",is anybody met this problem？

**Comment by ligui-iOS** [comment]
It seems to be openstreams

**Comment by manmanstrong** [comment]
Encountered the same problem, what solution is there, thank you

**Comment by seanm** [comment]
Nobody is going to be able to help you without much more info.  What OS?  What version of CocoaAsyncSocket? Have you tried the newest version?  Do you have example code that reproduces the problem?  etc. etc.

**Comment by Supecomer** [comment]
> Encountered the same problem, what solution is there, thank you

me ,too

**Comment by Jeremy-JM** [comment]
Encountered the same problem, what solution is there, thank you

**Comment by klh12345** [comment]
I am very sorry that I did not clearly understand your question. Is it convenient to add more descriptions of the problem?

**Comment by Supecomer** [comment]
> I am very sorry that I did not clearly understand your question. Is it convenient to add more descriptions of the problem?

`2019-03-20 14:29:46.913315+0800 MGVE[1079:248394] [] tcp_connection_is_cellular No connected path
2019-03-20 14:29:47.455291+0800 MGVE[1079:248394] [] nw_connection_copy_connected_path [C76] Client called nw_connection_copy_connected_path on unconnected nw_connection
2019-03-20 14:29:47.455320+0800 MGVE[1079:248394] [] tcp_connection_is_cellular No connected path
2019-03-20 14:29:47.918142+0800 MGVE[1079:248394] [] nw_connection_copy_connected_path [C77] Client called nw_connection_copy_connected_path on unconnected nw_connection
2019-03-20 14:29:47.918174+0800 MGVE[1079:248394] [] tcp_connection_is_cellular No connected path
2019-03-20 14:29:49.066857+0800 MGVE[1079:248394] [] nw_connection_copy_connected_path [C78] Client called nw_connection_copy_connected_path on unconnected nw_connection
2019-03-20 14:29:49.066936+0800 MGVE[1079:248394] [] tcp_connection_is_cellular No connected path
2019-03-20 14:29:50.716114+0800 MGVE[1079:248394] [] nw_connection_copy_connected_path [C79] Client called nw_connection_copy_connected_path on unconnected nw_connection
2019-03-20 14:29:50.716211+0800 MGVE[1079:248394] [] tcp_connection_is_cellular No connected path
2019-03-20 14:29:51.528205+0800 MGVE[1079:248394] [] nw_connection_copy_connected_path [C80] Client called nw_connection_copy_connected_path on unconnected nw_connection
2019-03-20 14:29:51.528257+0800 MGVE[1079:248394] [] tcp_connection_is_cellular No connected path
2019-03-20 14:29:51.694349+0800 MGVE[1079:248394] [] nw_connection_copy_connected_path [C81] Client called nw_connection_copy_connected_path on unconnected nw_connection
2019-03-20 14:29:51.694377+0800 MGVE[1079:248394] [] tcp_connection_is_cellular No connected path`
like this ， local server

**Comment by CodingInTheBrain** [comment]
- (void)socket:(GCDAsyncSocket *)sock didReadData:(NSData *)data withTag:(long)tag
{
}

**Comment by JianghuaZheng** [comment]
Please check the  method - (void)writeData:(NSData *)data withTimeout:(NSTimeInterval)timeout tag:(long)tag . If the data is mutable. You should call [mutableData copy].

 If the given data parameter is mutable (NSMutableData) then you MUST NOT alter the data while
 the socket is writing it. In other words, it's not safe to alter the data until after the delegate method
 socket:didWriteDataWithTag: is invoked signifying that this particular write operation has completed.

**Comment by Louts-Royer** [comment]
我也遇到了同样的问题，没有找到答案

**Comment by Dreamhai** [comment]
> > I am very sorry that I did not clearly understand your question. Is it convenient to add more descriptions of the problem?
> 
> `2019-03-20 14:29:46.913315+0800 MGVE[1079:248394] [] tcp_connection_is_cellular No connected path 2019-03-20 14:29:47.455291+0800 MGVE[1079:248394] [] nw_connection_copy_connected_path [C76] Client called nw_connection_copy_connected_path on unconnected nw_connection 2019-03-20 14:29:47.455320+0800 MGVE[1079:248394] [] tcp_connection_is_cellular No connected path 2019-03-20 14:29:47.918142+0800 MGVE[1079:248394] [] nw_connection_copy_connected_path [C77] Client called nw_connection_copy_connected_path on unconnected nw_connection 2019-03-20 14:29:47.918174+0800 MGVE[1079:248394] [] tcp_connection_is_cellular No connected path 2019-03-20 14:29:49.066857+0800 MGVE[1079:248394] [] nw_connection_copy_connected_path [C78] Client called nw_connection_copy_connected_path on unconnected nw_connection 2019-03-20 14:29:49.066936+0800 MGVE[1079:248394] [] tcp_connection_is_cellular No connected path 2019-03-20 14:29:50.716114+0800 MGVE[1079:248394] [] nw_connection_copy_connected_path [C79] Client called nw_connection_copy_connected_path on unconnected nw_connection 2019-03-20 14:29:50.716211+0800 MGVE[1079:248394] [] tcp_connection_is_cellular No connected path 2019-03-20 14:29:51.528205+0800 MGVE[1079:248394] [] nw_connection_copy_connected_path [C80] Client called nw_connection_copy_connected_path on unconnected nw_connection 2019-03-20 14:29:51.528257+0800 MGVE[1079:248394] [] tcp_connection_is_cellular No connected path 2019-03-20 14:29:51.694349+0800 MGVE[1079:248394] [] nw_connection_copy_connected_path [C81] Client called nw_connection_copy_connected_path on unconnected nw_connection 2019-03-20 14:29:51.694377+0800 MGVE[1079:248394] [] tcp_connection_is_cellular No connected path`
> like this ， local server

请问你这边这个问题是怎么解决的呢

**Comment by Dreamhai** [comment]
> 我也遇到了同样的问题，没有找到答案

大兄弟也思路没呀

**Comment by allan304** [comment]
> Please check the method - (void)writeData:(NSData *)data withTimeout:(NSTimeInterval)timeout tag:(long)tag . If the data is mutable. You should call [mutableData copy].
> 
> If the given data parameter is mutable (NSMutableData) then you MUST NOT alter the data while
> the socket is writing it. In other words, it's not safe to alter the data until after the delegate method
> socket:didWriteDataWithTag: is invoked signifying that this particular write operation has completed.

It's helpful for me.Thank you!

**Comment by parigelamadhubabu** [comment]
nw_connection_copy_connected_path [C1] Client called nw_connection_copy_connected_path on unconnected nw_connection
tcp_connection_is_cellular No connected path

I am getting above issue, please tell me what is issue exactly

**Comment by rameshkec85** [comment]
Getting this same issue when run the app in iPhone device. But works very well in Simulator.  Any clue about this issue. 
My device has support simcard and wifi. While i am running the app, simcard is not available in the iphone. 
What could be the issue. I am getting this issue frequently .

**Comment by HardikKMT** [comment]
I am also getting same issue always call mqtt willmessage after sometime so anyone help me thanks in advace
