### ISSUE TITLE
[GCDAsyncSocket closeWithError:]  crash

### ISSUE THREAD

**Issue by HatsuneMikuV** [robbiehanson/CocoaAsyncSocket#676]
![image](https://user-images.githubusercontent.com/14038743/54906081-7bbadb00-4f1d-11e9-94af-fd483b247311.png)

CocoaAsyncSocket version 7.6.3
Xcode version 10.1

![image](https://user-images.githubusercontent.com/14038743/54906207-c2103a00-4f1d-11e9-8291-ffc9be6f9d9e.png)

**Comment by HatsuneMikuV** [comment]
@chrisballinger

**Comment by seanm** [comment]
@HatsuneMikuV you might want to read https://www.chiark.greenend.org.uk/~sgtatham/bugs-cn.html
