### ISSUE TITLE
Can't get receive delegate method callback on iPhoneX or newer.

### ISSUE THREAD

**Issue by SuAdrenine** [robbiehanson/CocoaAsyncSocket#680]
I write this code, and it runs well except on device iPhoneX or newer.
```
dispatch_queue_t queue = dispatch_queue_create("com.pt.deviceScanner", DISPATCH_QUEUE_SERIAL);

self.receiveUDPSocket = [[GCDAsyncUdpSocket alloc] initWithDelegate:self delegateQueue:queue];
    
NSError *error;

if (![self.receiveUDPSocket bindToPort:MultiCastPort error:&error]) {
    [self.receiveUDPSocket bindToPort:MultiCastPort error:&error];
}

if (![self.receiveUDPSocket joinMulticastGroup:MultiCastAddress error:&error]) {

    [self.receiveUDPSocket joinMulticastGroup:MultiCastAddress error:&error];
}

if (![self.receiveUDPSocket enableBroadcast:YES error:&error]) {

    [self.receiveUDPSocket enableBroadcast:YES error:&error];
}

if (![self.receiveUDPSocket beginReceiving:&error]) {

    [self.receiveUDPSocket beginReceiving:&error];
}
```
I tried to initialize it by `dispatch_get_main_queue()`, but it doesn't work.
I have no idea about it，anyone helps?

**Comment by rlx** [comment]
this is probably very late but your code doesn't make sense to me with the if statement that calls same code if it returns false

here is a swift version (similar to what you were trying to do) that works for me

udpScoket = GCDAsyncUdpSocket(delegate: self, delegateQueue: DispatchQueue.global())
try udpScoket?.bind(toPort: PORT)
try udpScoket?.enableBroadcast(true)
try udpScoket?.joinMulticastGroup(ADDRESS)
try udpScoket?.beginReceiving()

You might need to send something from your receive socket to the server and make sure server response from your target port to your local port

**Comment by SuAdrenine** [comment]
@rlx Thank you for your advice. I did nothing, but it works now.
