### ISSUE TITLE
 how does enableBackgroundingOnSocket work

### ISSUE THREAD

**Issue by ZZHHAANNGG** [robbiehanson/CocoaAsyncSocket#683]
Hi, I am working on a project has the socket alive in the background. I am trying to use websocket to replace the XMPP. However, I implement the almost same way to keep the socket alive in the background, it does not work on. So I need some help. I need to understand how the socket can be alive in the background.

**Comment by andrewhavens** [comment]
@ZZHHAANNGG I was also wondering how it works, but then I found the documentation: https://github.com/robbiehanson/CocoaAsyncSocket/blob/master/Source/GCD/GCDAsyncSocket.h#L983-L1008
