### ISSUE TITLE
Project Catalyst Support (aka UIKit on macOS)

### ISSUE THREAD

**Issue by MauricioDomenech** [robbiehanson/CocoaAsyncSocket#687]
Please add support to adapt iOS applications to the new macOS framework.

**Comment by drewster99** [comment]
I've been working on a new Catalyst project using the current commit https://github.com/robbiehanson/CocoaAsyncSocket/commit/b179ea4013e94e31e6e637955e520ea4fb9d1b13 without issues on macOS.  I'm doing all UDP stuff -- not sure if that matters.

**Comment by MauricioDomenech** [comment]
Yeah, it was a configuration in my project
