### ISSUE TITLE
how to use SSL in swift

### ISSUE THREAD

**Issue by gogym** [robbiehanson/CocoaAsyncSocket#689]
how to use SSL in swift?
Can you provide  one-way and two-way  example?
the server is netty...

**Comment by gogym** [comment]
If GCDAsyncSocketManuallyEvaluateTrust = false, can be connected.But if the certificate is set up, the connection cannot be established.
Can you provide an example of a connection using certificate validation?

`settings = [
				kCFStreamSSLPeerName as String: kCFNULL,
				kCFStreamSSLIsServer as String: NSNumber(value: false),
				kCFStreamSSLCertificates as String: NSArray(array: [TestServer.identity])`

The above code does not shake hands successfully

**Comment by freddiezhao** [comment]
I have the same problem,Can you provide one-way example,thanks

**Comment by gogym** [comment]
> I have the same problem,Can you provide one-way example,thanks

`    
    func getSecIdentity()-> SecIdentity{
        
        //let bundle = Bundle(for: SocketClient.self)
        
        //        guard let url = bundle.url(forResource: "clientStore", withExtension: "p12",subdirectory: "res") else {
        //            fatalError("Missing the server cert resource from the bundle")
        //        }
        
        let url = SocketConfig.sharedInstance.getP12();
        let passwd=SocketConfig.sharedInstance.getP12Passwd();
        
        do {
            let p12 = try Data(contentsOf: url!) as CFData
            let options = [kSecImportExportPassphrase as String: passwd!] as CFDictionary
            
            var rawItems: CFArray?
            
            guard SecPKCS12Import(p12, options, &rawItems) == errSecSuccess else {
                fatalError("Error in p12 import")
            }
            
            let items = rawItems as! Array<Dictionary<String,Any>>
            let identity = items[0][kSecImportItemIdentity as String] as! SecIdentity
            
            return identity;
        }
        catch {
            fatalError("Could not create server certificate")
        }
        
        
    }`

`  if(SocketConfig.sharedInstance.getSsl()){
            var settings: [String: NSObject]
            
            settings = [
                kCFStreamSSLIsServer as String: NSNumber(value: false),
                GCDAsyncSocketManuallyEvaluateTrust as String: NSNumber(value: true),
            ]
            
            if(SocketConfig.sharedInstance.getNeedClientAuth()){
               //two way
                settings[kCFStreamSSLCertificates as String] = NSArray(array: [getSecIdentity()]);
            }
            sock.startTLS(settings)
        }`

**Comment by freddiezhao** [comment]
> > I have the same problem,Can you provide one-way example,thanks
> 
> `
> func getSecIdentity()-> SecIdentity{
> 
> ```
>     //let bundle = Bundle(for: SocketClient.self)
>     
>     //        guard let url = bundle.url(forResource: "clientStore", withExtension: "p12",subdirectory: "res") else {
>     //            fatalError("Missing the server cert resource from the bundle")
>     //        }
>     
>     let url = SocketConfig.sharedInstance.getP12();
>     let passwd=SocketConfig.sharedInstance.getP12Passwd();
>     
>     do {
>         let p12 = try Data(contentsOf: url!) as CFData
>         let options = [kSecImportExportPassphrase as String: passwd!] as CFDictionary
>         
>         var rawItems: CFArray?
>         
>         guard SecPKCS12Import(p12, options, &rawItems) == errSecSuccess else {
>             fatalError("Error in p12 import")
>         }
>         
>         let items = rawItems as! Array<Dictionary<String,Any>>
>         let identity = items[0][kSecImportItemIdentity as String] as! SecIdentity
>         
>         return identity;
>     }
>     catch {
>         fatalError("Could not create server certificate")
>     }
>     
>     
> }`
> ```
> 
> ` if(SocketConfig.sharedInstance.getSsl()){
> var settings: [String: NSObject]
> 
> ```
>         settings = [
>             kCFStreamSSLIsServer as String: NSNumber(value: false),
>             GCDAsyncSocketManuallyEvaluateTrust as String: NSNumber(value: true),
>         ]
>         
>         if(SocketConfig.sharedInstance.getNeedClientAuth()){
>            //two way
>             settings[kCFStreamSSLCertificates as String] = NSArray(array: [getSecIdentity()]);
>         }
>         sock.startTLS(settings)
>     }`
> ```

Thanks, can you tell me p12 file is  public key or  private key, I think it should be public key for app or web browser

**Comment by freddiezhao** [comment]
I want to use Self-signed SSL certificate in my app, can you tell me  those code can work ? 

I'm sorry for my poor English

**Comment by gogym** [comment]
> I want to use Self-signed SSL certificate in my app, can you tell me those code can work ?
> 
> I'm sorry for my poor English
哥们，原来都是中国人啊。这个是可以用的。也是自签名证书。用keystore生成的。代码是能用的，单向验证在IOS上其实不需要证书。双向才需要证书

**Comment by freddiezhao** [comment]
> I want to use Self-signed SSL certificate in my app, can you tell me those code can work ?
> 
> I'm sorry for my poor English
> 哥们，原来都是中国人啊。这个是可以用的。也是自签名证书。用keystore生成的。代码是能用的，单向验证在IOS上其实不需要证书。双向才需要证书

github果真是同性交友的好地方,这里也遇到祖国的同行,可以加个好友不,方便沟通,哈哈 QQ:59894703

**Comment by freddiezhao** [comment]
> I want to use Self-signed SSL certificate in my app, can you tell me those code can work ?
> 
> I'm sorry for my poor English
> 哥们，原来都是中国人啊。这个是可以用的。也是自签名证书。用keystore生成的。代码是能用的，单向验证在IOS上其实不需要证书。双向才需要证书

我其实是想实现一个抓取 https 数据包的功能,查了不少资料,看下来是要自签证书才行,一头雾水中
