### ISSUE TITLE
Delay in read data

### ISSUE THREAD

**Issue by MaximTrioSoft** [robbiehanson/CocoaAsyncSocket#69]
i'm using GCDAsyncSocket and i came across a problem, when i send a few write data requests i have  a delay in receiving read data responses.

it's like the data is received  but it doesn't read it from the stream or something like that.

i tried to change to AsyncSocket and its the same problem.

the server that i'm working with sends protobuf messages if it matters.

**Comment by nickplee** [comment]
+1

**Comment by rodrigobusata** [comment]
+1
