### ISSUE TITLE
writeData:withTimeout:tag:  crash

### ISSUE THREAD

**Issue by GitHubZHH** [robbiehanson/CocoaAsyncSocket#690]
There are several ways:
## One
#1 Thread
SIGSEGV
SEGV_ACCERR

libdispatch.dylib | _dispatch_async$VARIANT$mp + 160
1 libdispatch.dylib | _dispatch_async$VARIANT$mp + 56
DriverApp | -[GCDAsyncSocket writeData:withTimeout:tag:] (GCDAsyncSocket.m:5856)
......

## Two
#35 Thread
SIGSEGV
SEGV_ACCERR

libdispatch.dylib | __dispatch_continuation_push + 4
DriverApp | -[GCDAsyncSocket writeData:withTimeout:tag:] (GCDAsyncSocket.m:5856)
......

## Three
#30 Thread
SIGSEGV
SEGV_ACCERR

libdispatch.dylib | __dispatch_lane_push$VARIANT$armv81 + 136
DriverApp | -[GCDAsyncSocket writeData:withTimeout:tag:] (GCDAsyncSocket.m:5856)

...

Specific code：
<img width="957" alt="image" src="https://user-images.githubusercontent.com/9910841/62851539-06f40c00-bd19-11e9-8639-8220b308a101.png">

Through the above stack analysis, all the problems occurred in `libdispatch.dylib', which is related to the use of `dispatch_async'. Excuse me: What do I need to pay attention to when calling `writeData: with Timeout: tag: `method?

**Comment by madonya** [comment]
hi, i have same issue, have you solved this?
