### ISSUE TITLE
The socket closes after 3 minutes after putting the application in the background

### ISSUE THREAD

**Issue by ibrahimdn** [robbiehanson/CocoaAsyncSocket#696]
I am using "GCDAsyncSocket" in my project. My project A video conversation project using the Linphone library. And I also use socket connection. The application only works between devices connected to the local modem.

The socket I use in my application closes 3 minutes after entering the application background. I want the socket not to close as long as the application is running (unless the application is killed). My application doesn't have a backend. All communication, except for Linphone, only takes place via the socket.

How can I do that?

I've tried

```
    func socket(_ sock: GCDAsyncSocket, didAcceptNewSocket newSocket: GCDAsyncSocket) {
        print("connect succuess")
        print("connect to" + newSocket.connectedHost!)
        print("port" + String(newSocket.connectedPort))
        clients.append(newSocket)
        callIP = newSocket.connectedHost!
        sock.enableBackgroundingOnSocket()
        
        newSocket.readData(withTimeout: -1, tag: 0)
    }
```

**Comment by amcalgates** [comment]
iOS is likely terminating your application - 3 minutes is often how long iOS gives you to continue running in the background before terminating it.

https://developer.apple.com/documentation/uikit/uiapplication/1623029-backgroundtimeremaining?language=objc
