### ISSUE TITLE
Couldn't open sockets port 

### ISSUE THREAD

**Issue by atayew** [robbiehanson/CocoaAsyncSocket#698]
I use CocoAsyncSocket in my project. I'm trying to open socket ports and nothing happens. 
import UIKit
import CocoaAsyncSocket

final class TCPSocket: NSObject, GCDAsyncSocketDelegate {
  private var socket: GCDAsyncSocket!
  var onRecieveData: ((Data) -> Void)?
  var onOpenedSocket: (() -> Void)?
  var onDisconnect: (() -> Void)?
  
  // MARK: Initializer
  override init() {
    super.init()
    self.socket = GCDAsyncSocket(delegate: self, delegateQueue: .main)
  }
    
  // MARK: Socket lifecycle methods
  func socket(_ sock: GCDAsyncSocket, didAcceptNewSocket newSocket: GCDAsyncSocket) {
    do {
            try socket.accept(onPort: 6002)
    } catch {
        print("Socket not accepted")
    }
        print("TCP accept new socket")
    }
    
  func connect(toHost host: String, onPort port: UInt16) {
    do {
      try socket.connect(toHost: host, onPort: port)
    } catch {
      print("Couldn't open socket")
    }
  }
  
  func sendCommand(command: Command, input: String?) {
    let dataToSend: Data
    if let input = input {
      dataToSend = command.dataWithInput(input)
    } else {
      dataToSend = command.data
    }
    socket.write(dataToSend, withTimeout: -1, tag: 0)
  }
  
  func disconnect() {
    socket.disconnect()
  }
  
  // MARK: Socket delegate methods
  func socket(_ sock: GCDAsyncSocket, didConnectToHost host: String, port: UInt16) {
    socket.readData(withTimeout: -1, tag: 0)
    onOpenedSocket?()
    print("Socket has been opened on \(host):\(port)")
  }
    
  func socket(_ sock: GCDAsyncSocket, didRead data: Data, withTag tag: Int) {
    socket.readData(withTimeout: -1, tag: 0)
    onRecieveData?(data)
    print("Did recieve response on TCP socket: \(data)")
  }
  
  func socketDidDisconnect(_ sock: GCDAsyncSocket, withError err: Error?) {
    onDisconnect?()
  }
} 
This is my code. What i'm doing wrong? Or this framework doesn't work on iOS 13.2?

**Comment by kimplwjf** [comment]
I also encountered this problem, have you solved it?
