### ISSUE TITLE
Private API usage unable to upload to Appstore!!

### ISSUE THREAD

**Issue by chrisghub** [robbiehanson/CocoaAsyncSocket#705]
When I last tried to submit my to testflight I got the following error message from Apple: ITMS-90338: Non-public API usage - The app contains or inherits from non-public classes in Frameworks/XMPPFramework.framework/XMPPFramework: GCDAsyncSocket .

Is there any way to quickly fix this?? Because it is really blocking me from releasing the app.

**Comment by chrisballinger** [comment]
This is definitely a false alarm and possibly related to how you integrated them into your project. Did you use CocoaPods or manual integration? If you used manual integration, you may have it set up incorrectly and it's embedding a framework inside of another framework, which isn't allowed.

**Comment by dminoror** [comment]
I had same issue.
I resolved it by change integrate way from Pod to Carthage. Submit successed.
But I still interested why it happened.

**Comment by chrisballinger** [comment]
Please submit a report to Apple indicating a false positive: https://feedbackassistant.apple.com/welcome
