### ISSUE TITLE
This repository uses UIWebview instead of using WKWebview which is not supported by Apple appstore guildlines  

### ISSUE THREAD

**Issue by arjungupta0107** [robbiehanson/CocoaAsyncSocket#710]

**Comment by chrisballinger** [comment]
Although this is technically true, it's only in some of the example code: https://github.com/robbiehanson/CocoaAsyncSocket/search?q=uiwebview&unscoped_q=uiwebview

Maybe you could submit a pull request porting it to WKWebView?

**Comment by arjungupta0107** [comment]
Okay!
I replaced UIWebView with WKWebView and modified changes after taking clone of your repo but i can not push my changes as i do not have permission to push my changes into your repo. showing this error to me :
<img width="599" alt="Screenshot 2020-03-20 at 5 17 47 PM" src="https://user-images.githubusercontent.com/37107527/77161563-03570d80-6ad0-11ea-80f7-7ab37388c97a.png">
Suggest me how can i submit my changes?

**Comment by chrisballinger** [comment]
https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request

**Comment by arjungupta0107** [comment]
Created PR https://github.com/robbiehanson/CocoaAsyncSocket/pull/712
and please let me know the further process to make this done.
Thanks.

**Comment by arjungupta0107** [comment]
Can you create a new tag so i can use that tag? because i do not want to add commit number.

**Comment by arjungupta0107** [comment]
Thanks
