### ISSUE TITLE
Linker Issue

### ISSUE THREAD

**Issue by Florent75** [robbiehanson/CocoaAsyncSocket#716]
Hi,

I am finalizing the portage of react native from React Native 0.59.10 -> 0.62.2.

I have never installed CocoaAsynSocket before and It seems not tot be mandatory in 0.59.10 React native.

Now that I am in 0.62.2,
Even though I have never installed CocoaAsyncSocket, It seems that Xcode need it as I do have a linker error specifying that CocoaAsynSocket library has not been found.

What I have tried :
- Install CocoaAsyncSocket by following the installation section (pod ...)
- Do a full reinstallation of Pod : 
-> Pod deintegrate
-> rm Pods directory
-> Pod install

But It still do have the issue.

Any idea why it seems mandatory in 0.62.2 and how to solve this issue ?

**Comment by zyestin** [comment]
This problem happen on my react-native proj, too

Xcode error log as below
```
ld: warning: directory not found for option '-L-L/Users/dl/Library/Developer/Xcode/DerivedData/AwesomeProject2-giwtpfenakfobuhgidjxpzvogfnc/Build/Products/Debug-iphonesimulator/CocoaAsyncSocket'
ld: library not found for -lCocoaAsyncSocket
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

my proj version info as below
```
react-native: 0.63.2
Xcode: 11.3.1
CocoaAsyncSocket: 7.6.0
```

**Comment by zyestin** [comment]
> Hi,
> 
> I am finalizing the portage of react native from React Native 0.59.10 -> 0.62.2.
> 
> I have never installed CocoaAsynSocket before and It seems not tot be mandatory in 0.59.10 React native.
> 
> Now that I am in 0.62.2,
> Even though I have never installed CocoaAsyncSocket, It seems that Xcode need it as I do have a linker error specifying that CocoaAsynSocket library has not been found.
> 
> What I have tried :
> 
>     * Install CocoaAsyncSocket by following the installation section (pod ...)
> 
>     * Do a full reinstallation of Pod :
>       -> Pod deintegrate
>       -> rm Pods directory
>       -> Pod install
> 
> 
> But It still do have the issue.
> 
> Any idea why it seems mandatory in 0.62.2 and how to solve this issue ?

Have you fixed this issue? This problem stuck me. Please help me~ 3q

**Comment by zyestin** [comment]
> This problem happen on my react-native proj, too
> 
> Xcode error log as below
> 
> ```
> ld: warning: directory not found for option '-L-L/Users/dl/Library/Developer/Xcode/DerivedData/AwesomeProject2-giwtpfenakfobuhgidjxpzvogfnc/Build/Products/Debug-iphonesimulator/CocoaAsyncSocket'
> ld: library not found for -lCocoaAsyncSocket
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> ```
> 
> my proj version info as below
> 
> ```
> react-native: 0.63.2
> Xcode: 11.3.1
> CocoaAsyncSocket: 7.6.0
> ```

Finally, I found the solution
https://github.com/facebook/react-native/issues/28483#issuecomment-653276470
