### ISSUE TITLE
The SecureTransport functions are deprecated in iOS 14

### ISSUE THREAD

**Issue by simonmaddox** [robbiehanson/CocoaAsyncSocket#724]
I've just tried building CocoaAsyncSocket with Xcode 12 for iOS 14, and I'm seeing 32 warnings for deprecated methods. It looks like the SecureTransport API has been deprecated. The deprecation notice points you towards the Network framework (which, as far as I can tell, is Swift only).

**Comment by gavineadie** [comment]
When Network was introduced, a few years back, the example code was in Objective-C.

**Comment by karimhm** [comment]
> I've just tried building CocoaAsyncSocket with Xcode 12 for iOS 14, and I'm seeing 32 warnings for deprecated methods. It looks like the SecureTransport API has been deprecated. The deprecation notice points you towards the Network framework (which, as far as I can tell, is Swift only).

[Network](https://developer.apple.com/documentation/network?language=objc) framework have a *C* interface and can be used from a variety of programing languages including *Objective-C*.

**Comment by simonmaddox** [comment]
> [Network](https://developer.apple.com/documentation/network?language=objc) framework have a _C_ interface and can be used from a variety of programing languages including _Objective-C_.

Yup. Back when I reported this issue, no C documentation was linked to from the Network framework’s documentation. Apple have now resolved that issue.
