### ISSUE TITLE
Swift Example of GCDAsyncUdpSocketReceiveFilterBlock

### ISSUE THREAD

**Issue by bensuffolk** [robbiehanson/CocoaAsyncSocket#731]
I would like to understand how to use GCDAsyncUdpSocketReceiveFilterBlock from within swift.

I have tried to define a function like this 

`
func filter(_ data: Data, fromAddress address: Data, withFilterContext filterContext: Any) -> Bool
`

The problem is that I can't then assign anything to the filterContext as it needs to be set as inout, e.g. 

`
func filter(_ data: Data, fromAddress address: Data, withFilterContext filterContext: inout Any) -> Bool
`

But then the compiler complains when I try to set that function 

`
Cannot convert value of type '(Data, Data, inout Any) -> Bool' to expected argument type 'GCDAsyncUdpSocketReceiveFilterBlock?' (aka 'Optional<(Data, Data, AutoreleasingUnsafeMutablePointer<Optional<AnyObject>>) -> Bool>')
`

I'm sure I'm missing something simple as I'm new to swift programming, so any advice / examples you can provide would be very helpful.

**Comment by Joebayld** [comment]
I overcame this by setting to the AutoreleasingUnsafeMutablePointer as such:

`pointer.pointee = “Any Data” as AnyObject`

Not sure how safe that is? But it seemed to do the trick.
