### ISSUE TITLE
Carthage Update Fails After Moving to Xcode 12

### ISSUE THREAD

**Issue by carpemobile** [robbiehanson/CocoaAsyncSocket#737]
I just upgraded to Xcode 12.0 and tried to perform a carthage update on my workspace which failed. It failed using the "carthage update" as well as what I typically run "carthage update --platform iOS --no-use-binaries"

carthage update --platform iOS --no-use-binaries

*** Fetching CocoaAsyncSocket
*** Checking out CocoaAsyncSocket at "72e0fa9e62d56e5bbb3f67e9cfd5aa85841735bc"
*** xcodebuild output can be found in /var/folders/kr/4nfgd0v56rg9p8l_96b54nkmb0knsx/T/carthage-xcodebuild.M3BL41.log
*** Building scheme "iOS Framework" in CocoaAsyncSocket.xcodeproj
Build Failed
	Task failed with exit code 1:
	/usr/bin/xcrun lipo -create /Users/smartin/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A7209/CocoaAsyncSocket/72e0fa9e62d56e5bbb3f67e9cfd5aa85841735bc/Build/Intermediates.noindex/ArchiveIntermediates/iOS\ Framework/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/CocoaAsyncSocket.framework/CocoaAsyncSocket /Users/smartin/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A7209/CocoaAsyncSocket/72e0fa9e62d56e5bbb3f67e9cfd5aa85841735bc/Build/Products/Release-iphonesimulator/CocoaAsyncSocket.framework/CocoaAsyncSocket -output /Users/smartin/Documents/src/ios/temp/temppp/Carthage/Build/iOS/CocoaAsyncSocket.framework/CocoaAsyncSocket

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details:

Build settings from command line:
    CARTHAGE = YES
    CLANG_ENABLE_CODE_COVERAGE = NO
    CODE_SIGN_IDENTITY = 
    CODE_SIGNING_REQUIRED = NO
    GCC_INSTRUMENT_PROGRAM_FLOW_ARCS = NO
    ONLY_ACTIVE_ARCH = NO
    SDKROOT = iphoneos14.0
    SKIP_INSTALL = YES
    STRIP_INSTALLED_PRODUCT = NO

note: Using new build system
note: Building targets in parallel
note: Using codesigning identity override: 
note: Planning build
note: Constructing build description
warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.4, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'iOS CocoaAsyncSocket' from project 'CocoaAsyncSocket')

**Comment by aviditi** [comment]
I am also experiencing this issue. 

I am running the latest version of carthage (0.36.0)

*** Building scheme "iOS Framework" in CocoaAsyncSocket.xcodeproj
Build Failed
Task failed with exit code 1:
/usr/bin/xcrun lipo -create /Users/_omitted_/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A7209/CocoaAsyncSocket/72e0fa9e62d56e5bbb3f67e9cfd5aa85841735bc/Build/Intermediates.noindex/ArchiveIntermediates/iOS\ Framework/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/CocoaAsyncSocket.framework/CocoaAsyncSocket /Users/_omitted_/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A7209/CocoaAsyncSocket/72e0fa9e62d56e5bbb3f67e9cfd5aa85841735bc/Build/Products/Release-iphonesimulator/CocoaAsyncSocket.framework/CocoaAsyncSocket -output /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-webdriveragent/Carthage/Build/iOS/CocoaAsyncSocket.framework/CocoaAsyncSocket
This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/k8/x3h6sf8j2tv8n93nghqkh6zr0000gn/T/carthage-xcodebuild.uHtQEf.log

**Comment by chrisballinger** [comment]
This is a problem with Carthage, and cannot be solved by library authors. See https://github.com/Rightpoint/BonMot/issues/394#issuecomment-697134998 for a more detailed explanation.

**Comment by hw-1** [comment]
Build Settings of your project and add " Any iOS Simulator SDK" with value  "arm64" inside Excluded Architecture.
