### ISSUE TITLE
iOS 14 Local Network

### ISSUE THREAD

**Issue by popamihai** [robbiehanson/CocoaAsyncSocket#740]
I can't manage to get this to work using Xcode 11 on iOS 14. The prompt is never triggered. According to this thread, you need at least one send request (e.g. ping) in order to get the privacy alert triggered - https://developer.apple.com/forums/thread/660260.

Is the new privacy alert working for you guys?

**Comment by bitcrumb** [comment]
This could be helpful: https://developer.apple.com/forums/thread/663858
It's an extremely insightful explanation of an Apple employee. This should have been in de the Apple documentation imho.

I'm seeing the popup being triggered in our app when built using Xcode 11 & running on iOS 14.

**Comment by Omarj** [comment]
@popamihai  any luck?
