### ISSUE TITLE
7.6.5 has not been pushed to specs repo

### ISSUE THREAD

**Issue by jonathandann** [robbiehanson/CocoaAsyncSocket#753]
The specs repo only has up to 7.6.4, so the iOS min deployment target isn't up to date with Xcode 12's requirements.

Pushing 7.6.5 fixes this. Thanks!

**Comment by chrisballinger** [comment]
Thanks for the reminder. This should be resolved now.

**Comment by jonathandann** [comment]
@chrisballinger Thanks!
