### ISSUE TITLE
A weird crash in the thread of GCDAsyncSocket-CFStream

### ISSUE THREAD

**Issue by manguoge** [robbiehanson/CocoaAsyncSocket#754]
![image](https://user-images.githubusercontent.com/13343984/103391639-62fd4180-4b55-11eb-8a5d-e4a0610dec8e.png)

Failure to locate the cause of a crash in a concurrent scene，please help to solve it.

**Comment by manguoge** [comment]
@robbiehanson @chrisballinger

**Comment by Loadex** [comment]
@chrisballinger @robbiehanson experiencing the same crash too. Any advice on how to solve it? Seems to only affect clients using `7.6.5` so far...
