### ISSUE TITLE
'SSLClose' is deprecated: first deprecated in iOS 13.0

### ISSUE THREAD

**Issue by moleculo27** [robbiehanson/CocoaAsyncSocket#756]
Trying to compile against an iOS Deployment Target of iOS 13.0 through iOS 14.3 gives the following warnings:

/Users/me/Documents/Projects/myapp/myapp/Controls/GCDAsyncSocket.m:3251:3: 'SSLClose' is deprecated: first deprecated in iOS 13.0 - No longer supported. Use Network.framework.

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.3.sdk/System/Library/Frameworks/Security.framework/Headers/SecureTransport.h:1731:1: 'SSLClose' has been explicitly marked deprecated here

This same warning is repeated for:

'SSLGetBufferedReadSize' is deprecated: first deprecated in iOS 13.0
'SSLRead' is deprecated: first deprecated in iOS 13.0
'SSLGetBufferedReadSize' is deprecated: first deprecated in iOS 13.0
'SSLRead' is deprecated: first deprecated in iOS 13.0
'SSLWrite' is deprecated: first deprecated in iOS 13.0
'SSLCreateContext' is deprecated: first deprecated in iOS 13.0
'kSSLServerSide' is deprecated: first deprecated in iOS 13.0
'kSSLStreamType' is deprecated: first deprecated in iOS 13.0
'kSSLClientSide' is deprecated: first deprecated in iOS 13.0
'SSLSetIOFuncs' is deprecated: first deprecated in iOS 13.0
'SSLSetConnection' is deprecated: first deprecated in iOS 13.0
'SSLSetSessionOption' is deprecated: first deprecated in iOS 13.0
'kSSLSessionOptionBreakOnServerAuth' is deprecated: first deprecated in iOS 13.0
'SSLSetPeerDomainName' is deprecated: first deprecated in iOS 13.0
'SSLSetCertificate' is deprecated: first deprecated in iOS 13.0
'SSLSetPeerID' is deprecated: first deprecated in iOS 13.0
'kSSLProtocolUnknown' is deprecated: first deprecated in iOS 13.0
'SSLSetProtocolVersionMin' is deprecated: first deprecated in iOS 13.0
'kSSLProtocolUnknown' is deprecated: first deprecated in iOS 13.0
'SSLSetProtocolVersionMax' is deprecated: first deprecated in iOS 13.0
'kSSLSessionOptionFalseStart' is deprecated: first deprecated in iOS 13.0
'kSSLSessionOptionSendOneByteRecord' is deprecated: first deprecated in iOS 13.0
'SSLSetEnabledCiphers' is deprecated: first deprecated in iOS 13.0
'SSLSetALPNProtocols' is deprecated: first deprecated in iOS 13.0
'SSLHandshake' is deprecated: first deprecated in iOS 13.0
'SSLCopyPeerTrust' is deprecated: first deprecated in iOS 13.0

Is there an update for supporting iOS 13.0 and later?

**Comment by chrisballinger** [comment]
Switching to Network.framework would basically be a complete rewrite of this library. In fact, I'd recommend using Network.framework instead of this for most new projects.
