### ISSUE TITLE
Security findings

### ISSUE THREAD

**Issue by bbmk** [robbiehanson/CocoaAsyncSocket#761]
Hello, multiple security issues are found when security test is performed: 

1. Heap Inspection(3 Issues) :
[HeapInspection.pdf](https://github.com/robbiehanson/CocoaAsyncSocket/files/6002458/HeapInspection.pdf)
2. MemoryLeak:
[MemoryLeak.pdf](https://github.com/robbiehanson/CocoaAsyncSocket/files/6002460/MemoryLeak.pdf)
3. TypeMismatch:
[TypeMismatch.pdf](https://github.com/robbiehanson/CocoaAsyncSocket/files/6002463/TypeMismatch.pdf)
4. UncheckedReturnValue:
[UncheckedReturnValue.pdf](https://github.com/robbiehanson/CocoaAsyncSocket/files/6002466/UncheckedReturnValue.pdf)
5. UnreleasedResource:
[UnreleasedResource.pdf](https://github.com/robbiehanson/CocoaAsyncSocket/files/6002469/UnreleasedResource.pdf)

**Comment by seanm** [comment]
I looked these over, and they all seem pretty useless to me.
