### ISSUE TITLE
Can't receive any data on iOS 14.5.1 Xcode 12.5

### ISSUE THREAD

**Issue by kaaaaai** [robbiehanson/CocoaAsyncSocket#768]
Always log like this:
```swift
[connection] nw_socket_handle_socket_event [C3.1:3] Socket SO_ERROR [61: Connection refused]
Init discovery failed, failed to receiving Error Domain=GCDAsyncUdpSocketErrorDomain Code=1 "Must bind socket before you can receive data. You can do this explicitly via bind, or implicitly via connect or by sending data." UserInfo={NSLocalizedDescription=Must bind socket before you can receive data. You can do this explicitly via bind, or implicitly via connect or by sending data.}
Init discovery failed, failed to receiving Error Domain=GCDAsyncUdpSocketErrorDomain Code=1 "Must bind socket before you can receive data. You can do this explicitly via bind, or implicitly via connect or by sending data." UserInfo={NSLocalizedDescription=Must bind socket before you can receive data. You can do this explicitly via bind, or implicitly via connect or by sending data.}
......
[connection] nw_socket_handle_socket_event [C5.1:3] Socket SO_ERROR [61: Connection refused]
[connection] nw_socket_handle_socket_event [C5.1:3] Socket SO_ERROR [61: Connection refused]
```

About the first part of the log, I have checked my `info.plist` file and confirmed that there is already a description of the local network permissions.

About the second part of the log, i don't what's wrong with the code

and Another strange thing is that you don't have these problems under iOS 13

**Comment by kaaaaai** [comment]
by the way, the version i am useing is 7.6.4, do i need to update?

**Comment by JNYJdev** [comment]
You can try using Xcode 12.0(may be the other 12.1 | 12.2 is working) to running.

**Comment by kaaaaai** [comment]
> You can try using Xcode 12.0(may be the other 12.1 | 12.2 is working) to running.

 @JNYJdev  Thank you very much, I have reinstalled my xcode and the problem has been fixed, It looks like an official issue

**Comment by paradoxally** [comment]
I've experienced the same with some client apps that use this library. 

You will need to add the Multicast entitlement [following these steps](https://developer.apple.com/forums/thread/663271) and that should get you up and running again on the latest Xcode 12.5. There is no issue with 12.2 or earlier versions of Xcode, but going forward this is needed.
