### ISSUE TITLE
Xcode 12.5&iOS 14.5.1 with UDP access got: Error Domain=NSPOSIXErrorDomain Code=65 "No route to host"

### ISSUE THREAD

**Issue by JNYJdev** [robbiehanson/CocoaAsyncSocket#769]
ERROR-DESC:
Error Domain=NSPOSIXErrorDomain Code=65 "No route to host" UserInfo={NSLocalizedDescription=No route to host, NSLocalizedFailureReason=Error in send() function.
Device infos: 
Mac air (M1 2020)
Xcode 12.5 
iPhone XR 14.5.1 

code example:

socketUDP bindToPort: port
socketUDP enableBroadcast:YES
socketUDP sendData:data toHost:"255.255.255.255" port:port withTimeout:-1 tag:TAG_DEFAULT];
next:
got error:  Error Domain=NSPOSIXErrorDomain Code=65 "No route to host" UserInfo={NSLocalizedDescription=No route to host, NSLocalizedFailureReason=Error in send() function.

but the other iOS 14.0 is work well
and Using Xcode 12.0 with 14.5.1 and 14.0 are work well

**Comment by chasen-d** [comment]
I have the same problem，Have you solved it？

**Comment by paradoxally** [comment]
Please see my comment on #768, this is almost certainly due to a missing entitlement.

**Comment by mgatelabs** [comment]
I just had the same error, this page seems to go over how to resolve it https://developer.apple.com/forums/thread/663271  but you need to request the entitlement first.

Weirdest thing is you need to manually edit the entitlements file and place the keys in the file.
