### ISSUE TITLE
Will it release for the iOS14.5~ crash

### ISSUE THREAD

**Issue by shanksGuo** [robbiehanson/CocoaAsyncSocket#770]
According to the issue on Apple DeveloperForums: https://developer.apple.com/forums/thread/679095
it will crash when the iOS system version is 14.5~, and the reply from Apple is  moving to Network framework. 
<img width="1010" alt="image" src="https://user-images.githubusercontent.com/8662571/119317250-764aae00-bcaa-11eb-86c2-c05afe1fbde2.png">
I wonder if CocoaAsyncSocket release for this system bug?

**Comment by nguyenhuutinh** [comment]
you have to change to network framework
