### ISSUE TITLE
Address already in use

### ISSUE THREAD

**Issue by lyz0925** [robbiehanson/CocoaAsyncSocket#776]
When I used the interface:"- (BOOL)acceptOnInterface:(NSString *)inInterface port:(uint16_t)port error:(NSError **)errPtr" to start socket, sometimes it would return failed with the message which is "48, Address already in use". How should I do if I got this situation?

**Comment by dyhe83** [comment]
It's because that port is in use, I think the root cause might be program didn't exit correctly.

Type the following command.
The second column represent `pid`.
```shell
sudo lsof -i - P | grep LISTEN
```

Then kill it.
```shell
kill 1234
```
