### ISSUE TITLE
Proposal: create a branch to enable logging for both TCP and UDP async socket by default!

### ISSUE THREAD

**Issue by zhaorui** [robbiehanson/CocoaAsyncSocket#777]
I use Swift Package Manager to import CocoaAsyncSocket that runs very smoothly.
However, when I want to enable logging on CocoaAsyncSocket, I meet a problem. 
For the TCP socket, we have a macro GCDAsyncSocketLoggingEnabled to do that.
But for the UDP socket, there is no such thing.

In the Swift Package Manager case, the macro is useless. I can't tell SPM to build 
CocoaAsyncSocket with this macro. 

Consider that we usually want to enable logging for debugging purposes, so I think
we should create a branch to enable the logging feature.

In SPM it's super easy to switch branches, when I'm done with the debugging, I can easily
switch it back.

**Comment by N1nomiya** [comment]
@zhaorui How to enable logging in Swift? 
I install the pod CocoaLumberjack, and change the line 39 `#define GCDAsyncSocketLoggingEnabled 1 `.
But still got `'DDLog.h' file not found` compile error.
