### ISSUE TITLE
Xcode 12 Analyzer memory warnings

### ISSUE THREAD

**Issue by funnel20** [robbiehanson/CocoaAsyncSocket#778]
In Xcode 12.5.1, when using Xcode Menu bar -> Product -> Analyze, Xcode reports 3 memory warnings:

1) _/ASyncSocket/GCDAsyncSocket.m_:1097:9: **Write to autoreleasing out parameter inside locally-scoped autorelease pool; consider writing first to a strong local variable declared outside of the autorelease pool**:

```ObjC
*error = [NSError errorWithDomain:GCDAsyncSocketErrorDomain code:GCDAsyncSocketOtherError userInfo:userInfo];
```

2) _/ASyncSocket/GCDAsyncSocket.m_:1119:9: **Write to autoreleasing out parameter inside locally-scoped autorelease pool; consider writing first to a strong local variable declared outside of the autorelease pool**:

```ObjC
*error = [NSError errorWithDomain:GCDAsyncSocketErrorDomain code:GCDAsyncSocketOtherError userInfo:userInfo];
```

3) _/ASyncSocket/GCDAsyncUdpSocket.m_:3305:28: **nil passed to a callee that requires a non-null 1st parameter**:

```ObjC
cachedConnectedHost = [[self class] hostFromAddress:address];
```

Can you please have a look into this?

**Comment by andyliuzs** [comment]
您好我已经收到您的邮件了，待查看后马上回复！

**Comment by funnel20** [comment]
Time doesn't heal all bugs. So please bot, reopen this issue

**Comment by funnel20** [comment]
I see that this has been resolved in commit https://github.com/robbiehanson/CocoaAsyncSocket/commit/2d131acff5fcd82027c0b76fdce0e408f972ea33 and PR #764 👏

When will an update be released?
