### ISSUE TITLE
Issue - GCDAsyncSocketErrorDomain - While using Mobile Hotspot

### ISSUE THREAD

**Issue by iosleadmoweb** [robbiehanson/CocoaAsyncSocket#783]
Hello,

I'm creating an app which enables you to record audio on multiple iPhones, iPads or iPod touches while remotely monitoring and managing your recording session on another iOS device. 

The issue is, If I turn on the hotspot with "**Telstra SIM Provider**" and from another iOS device I'm trying to join that session with the connection of hotspot.
1st iOS Device - Create Session (Hotspot host)
2nd iOS Device - Join Session (Connect 1st device's hotspot)
So on the 1st iOS device while trying to create a session, It is not working and giving me the below error. 

**Error Domain=GCDAsyncSocketErrorDomain Code=8 "IPv6 has been disabled and DNS lookup found no IPv4 address." UserInfo={NSLocalizedDescription=IPv6 has been disabled and DNS lookup found no IPv4 address.}**

But when I'm using another SIM Provider or wifi, it is working fine as expected. So when I use "**Telstra SIM Provider**", it is giving me the above error.

Anticipating your feedback soon.

Thank you,
Ashit

**Comment by cherishloveyou** [comment]
have the same issue
