### ISSUE TITLE
Linker Issue with Simulator

### ISSUE THREAD

**Issue by maferder** [robbiehanson/CocoaAsyncSocket#784]
I get the following errors when trying to build/run against a Xcode simulator.  Builds and runs fine when building for a real device.

Undefined symbol: _OBJC_CLASS_$_GCDAsyncUdpSocket
Undefined symbol: _OBJC_CLASS_$_GCDAsyncSocket

Using: Xcode Version 13.2.1 (13C100), Simulator Version 13.2 (972.2), iOS 12.0 target (doesn't matter what iOS version I use)

Thanks for your commitment and support.

**Comment by Breiby** [comment]
I've been experiencing a similar issue. As suggested in #63, you could try adding `GCDAsyncSocket.m` to _Compile Sources_ in _Build Phases_. That solved it for me.
