### ISSUE TITLE
version 7.6.5=======[GCDAsyncSocket cfstreamThread]crash

### ISSUE THREAD

**Issue by 405092901** [robbiehanson/CocoaAsyncSocket#791]
pod 'CocoaAsyncSocket', '7.6.5'

it is crash log, fix it crash as soon as possible please

Crashed: GCDAsyncSocket-CFStream
0  CoreFoundation                 0x1d65c CFRetain + 32
1  CoreFoundation                 0x120978 __CFSocketPerformV0 + 384
2  CoreFoundation                 0xbbf04 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 28
3  CoreFoundation                 0xccc90 __CFRunLoopDoSource0 + 208
4  CoreFoundation                 0x6184 __CFRunLoopDoSources0 + 268
5  CoreFoundation                 0xbb4c __CFRunLoopRun + 828
6  CoreFoundation                 0x1f6b8 CFRunLoopRunSpecific + 600
7  Foundation                     0x18414 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 236
8 XXXXxx                           0x31c6d60 +[GCDAsyncSocket cfstreamThread:] + 7686 (GCDAsyncSocket.m:7686)
9  Foundation                     0x6855c __NSThread__start__ + 808
10 libsystem_pthread.dylib        0x19ac _pthread_start + 148
11 libsystem_pthread.dylib        0xe68 thread_start + 8

**Comment by herman602** [comment]
Have you tried this?
https://github.com/robbiehanson/CocoaAsyncSocket/pull/785/commits/59c1f82523558756cee62e472f17923a1833c24f
