### ISSUE TITLE
Version 7.6.5 will CRASH on iOS 16 due to removed `kCFStreamNetworkServiceTypeVoIP`

### ISSUE THREAD

**Issue by funnel20** [robbiehanson/CocoaAsyncSocket#801]
As [reported](https://github.com/robbiehanson/CocoaAsyncSocket/issues/361#issuecomment-1227076872) the latest version will crash on iOS 16, since Apple finally removed constant `kCFStreamNetworkServiceTypeVoIP` which is still be used by AsyncSocket.

I have provided a solution for issue https://github.com/robbiehanson/CocoaAsyncSocket/issues/361 more than 2 years ago via PR #717 but this has never be implemented.
Please release an update asap where `kCFStreamNetworkServiceTypeVoIP` should be replaced by `kCFStreamNetworkServiceTypeBackground` as indicated in the above mentioned comments and PR.

**Comment by fabiosoft** [comment]
YES!
Every app calling "enableBackgroundingOnSocket" method to support background will crash due to missing of this flag.
Hope someone will merge and update....
