### ISSUE TITLE
GCDAsyncUdpSocket 在iOS16上无法弹起本地网络权限申请窗口

### ISSUE THREAD

**Issue by tikejc** [robbiehanson/CocoaAsyncSocket#805]
GCDAsyncUdpSocket 在iOS16上无法弹起本地网络权限申请窗口

**Comment by KalininAndrey** [comment]
In iOS 16 You need to get multicast entitlement from Apple. If you have it, multicast is working and permission alert is showing. https://developer.apple.com/forums/thread/663271
