### ISSUE TITLE
Xcode14.0 App Store Connect Operation Error

### ISSUE THREAD

**Issue by KorsChen** [robbiehanson/CocoaAsyncSocket#806]
”The app references non-public selectors in Payload/xxx.app/Frameworks/CocoaAsyncSocket_-2A89F950105224A4_PackageProduct.framework/CocoaAsyncSocket_-2A89F950105224A4_PackageProduct: newSocketQueueForConnectionFromAddress:onSocket:, socket:didAcceptNewSocket:, socket:didConnectToHost:port:, socket:didConnectToUrl:, socket:didReadData:withTag:, socket:didReadPartialDataOfLength:tag:, socket:didReceiveTrust:completionHandler:, socket:didWriteDataWithTag:, socket:didWritePartialDataOfLength:tag:, socket:shouldTimeoutReadWithTag:elapsed:bytesDone:, socket:shouldTimeoutWriteWithTag:elapsed:bytesDone:, socketDidCloseReadStream:, socketDidDisconnect:withError:, socketDidSecure:“

The application does not use any private functions. However, the CocoaAsyncSocket of the dependent SwiftPM prompts references non public selectors on Xcode14.0. The package is unusable. Please take a look

**Comment by FluffyDiscord** [comment]
This is critical issue, can we get more attention please ?

**Comment by qianlishun** [comment]
It seems that it hasn't been updated for a long time...

**Comment by comeStudy** [comment]
同样的问题，解决了吗？

**Comment by atypiape** [comment]
> 同样的问题，解决了吗？

我也是同样的问题，正在尝试解决
