### ISSUE TITLE
Is this library supported for iOS 13+ ?

### ISSUE THREAD

**Issue by iserbius** [robbiehanson/CocoaAsyncSocket#811]
Hello, guys. 
I'm working with third party library, depended on _CocoaAsyncSocket_. The target of my host project is iOS 14+ and on compile time I got a lot of warnings from `GCDAsyncSocket.m`, looks like

`'SSLSetIOFuncs' is deprecated: first deprecated in iOS 13.0 - No longer supported. Use Network.framework.`

1. Have we any way to solve this issues in future releases of _CocoaAsyncSocket_?
2. Can you explain, have we any risc to got removeance of deprected API in release with your framework?

I can't connect with maintainer of third-party framework, depended on _CocoaAsyncSocket_ and has no way to solve this issues with them, so, hopes you'll give me any info about.

PS Also, I found issues
[#795](https://github.com/robbiehanson/CocoaAsyncSocket/issues/795)
[#756](https://github.com/robbiehanson/CocoaAsyncSocket/issues/756)
but their contents cannot be reassuring - we can't stop using your framework and migrate to Apple's Network.framework 
¯\\\_(ツ)_/¯

I will be glad for any information from you. Thanks!

**Comment by seanm** [comment]
If you only care about very new OSes, like iOS 14+, why don't you just use Network.framework?

Part of the raison d'etre of CocoaAsyncSocket to to provide a nice async API for older OSes.

**Comment by dsmurfin** [comment]
There are some very real issues with Network.framework which Apple has not made any moves to resolve.

Multicast support was only added very recently. What is more significant is that port reuse or what is called allowLocalEndpointReuse does not work on either iOS or macOS. This is a major problem for anyone who requires this.
