### ISSUE TITLE
crashed on iOS 16.1, SIGTRAP

### ISSUE THREAD

**Issue by jufn** [robbiehanson/CocoaAsyncSocket#815]
libsystem_platform.dylib    0x1d3d7008c    __os_semaphore_wait.cold.1 + 48544
libsystem_platform.dylib    0x1d3d6a898    __os_semaphore_wait.cold.1 + 26028
CoreFoundation    0x186e6d0c0    _CFBagGetValue + 76
CFNetwork    0x188085498    __CFNetworkErrorGetLocalizedDescription + 357868
CoreFoundation    0x186db2c70    ___NSSetM_copy + 24
CFNetwork    0x188063014    __CFNetworkErrorGetLocalizedDescription + 217448
CoreFoundation    0x186e1aa10    ___CFRunLoopDoTimer + 996
CoreFoundation    0x186e6d3f8    __CFXNotificationRegistrarAddName + 800
CFNetwork    0x18806faec    __CFNetworkErrorGetLocalizedDescription + 269376
CoreFoundation    0x186ddf5dc    ___CFStringAppendFormatCore + 3212
superstar    0x1000fbfd8    -[GCDAsyncSocket closeWithError:] (GCDAsyncSocket.m:3236)
superstar    0x100100a08    -[GCDAsyncSocket doReadEOF] (GCDAsyncSocket.m:5719)
superstar    0x1000ff0b0    ___66-[GCDAsyncSocket setupReadAndWriteSourcesForNewlyConnectedSocket:]_block_invoke (GCDAsyncSocket.m:4281)
libdispatch.dylib    0x18e375fdc    __dispatch_channel_invoke + 2896
libdispatch.dylib    0x18e37946c    __dispatch_sync_f_slow + 240
libdispatch.dylib    0x18e38ca58    __dispatch_kq_drain + 188
libdispatch.dylib    0x18e37d56c    __dispatch_workloop_worker_thread + 2536
libdispatch.dylib    0x18e37e1e0    __dispatch_apply_with_attr_f + 612
libdispatch.dylib    0x18e388e10    __dispatch_mach_msg_not_sent + 296
libsystem_pthread.dylib    0x1d3dffdf8    _pthread_dependency_wait_np.cold.3 + 8720

**Comment by seanm** [comment]
There is not enough information there for anyone to help you.
