### ISSUE TITLE
App crash in Xcode 14 and iOS 16

### ISSUE THREAD

**Issue by Nipagohel** [robbiehanson/CocoaAsyncSocket#818]
App crash in Xcode 14 and iOS 16.

<img width="359" alt="image" src="https://user-images.githubusercontent.com/49637108/214556169-916cbd28-e6eb-407a-a18f-a878e6e9fa97.png">
<img width="340" alt="Screenshot 2023-01-25 at 5 20 19 PM" src="https://user-images.githubusercontent.com/49637108/214556272-0194423d-c7ae-47ff-8426-18500f41c02d.png">

**Comment by GodLiek** [comment]
➕1⃣️

**Comment by Rajai-Sunnyclock** [comment]
@GodLiek Do you need a solution? We were able to fix this with this👇🏼
https://github.com/robbiehanson/CocoaAsyncSocket/pull/717/commits

**Comment by lovederh** [comment]
+1

**Comment by lovederh** [comment]
> @GodLiek Do you need a solution? We were able to fix this with this👇🏼 https://github.com/robbiehanson/CocoaAsyncSocket/pull/717/commits

try it , but not work for me

**Comment by GodLiek** [comment]
> @GodLiek您需要解决方案吗？我们能够用这个👇🏼 [https://github.com/robbiehanson/CocoaAsyncSocket/pull/717/commits来解决这个问题](https://github.com/robbiehanson/CocoaAsyncSocket/pull/717/commits)

谢谢，已解决
