### ISSUE TITLE
Not work with bitcode enable

### ISSUE THREAD

**Issue by luizricardo-co** [robbiehanson/CocoaAsyncSocket#827]
When I build a react native app to device or build to archive my app with bitcode enable, show this error bellow

'/Users/app/Library/Developer/Xcode/DerivedData/app-guoprshhgcpdbwgeihjqmsixufwi/Build/Products/Debug-iphoneos/CocoaAsyncSocket/libCocoaAsyncSocket.a(GCDAsyncSocket.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Users/app/Library/Developer/Xcode/DerivedData/app-guoprshhgcpdbwgeihjqmsixufwi/Build/Products/Debug-iphoneos/CocoaAsyncSocket/libCocoaAsyncSocket.a' for architecture arm64

In my case I need bitcode is enable. Someone can help me?

Environment
React
  "react": "18.2.0",
  "react-native": "0.71.6",
Xcode: v14.3
CocoaAsyncSocket: (7.6.5)

**Comment by mtettmar** [comment]
Same here. Anyone?

**Comment by luizricardo-co** [comment]
> Same here. Anyone?

Put this in your podfile and run pod install again. This solved my problem for any bitcode dependency.
```
post_install do |installer |
  flipper_post_install(installer)
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'YES'
    end
  end
end 
```
