### ISSUE TITLE
GCDAsyncSocket with local ip address changed

### ISSUE THREAD

**Issue by amacymind** [robbiehanson/CocoaAsyncSocket#828]
Hello,
I am using GCDAsyncSocket for communicate between iOS app & tvOS app in same local network. Once apple tv connected with iOS application then we saved address in iphone local. So when user open application next time & apple tv application also running then if connected automatically. Its works fine. But now suddenly our local network changed apple tv ip address. So now connectToAddress method not works & we can't able to connect with apple tv. So how can i managed this communication if local ip address changed so next time when app open its connect automatically?

Thanks,

**Comment by andyliuzs** [comment]
您好我已经收到您的邮件了，待查看后马上回复！

**Comment by sokarax** [comment]
> Hello,
> 
> I am using GCDAsyncSocket for communicate between iOS app & tvOS app in same local network. Once apple tv connected with iOS application then we saved address in iphone local. So when user open application next time & apple tv application also running then if connected automatically. Its works fine. But now suddenly our local network changed apple tv ip address. So now connectToAddress method not works & we can't able to connect with apple tv. So how can i managed this communication if local ip address changed so next time when app open its connect automatically?
> 
> 
> 
> Thanks,

**Comment by amacymind** [comment]
any update?

> 您好我已经收到您的邮件了，待查看后马上回复！

**Comment by amacymind** [comment]
any update on this issue?
