### ISSUE TITLE
Privacy Manifest

### ISSUE THREAD

**Issue by amcalgates** [robbiehanson/CocoaAsyncSocket#832]
According [Apple docs](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api?language=objc):

> From Fall 2023 you’ll receive an email from Apple if you upload an app to App Store Connect that uses required reason API without describing the reason in its privacy manifest file. From Spring 2024, apps that don’t describe their use of required reason API in their privacy manifest file won’t be accepted by App Store Connect.

Does CocoaAsyncSocket use any APIs mentioned here? If so, are there plans to include a privacy manifest? I'm not 100% sure what that'd even look like, but [this thread](https://developer.apple.com/forums/thread/733537) maybe has a little insight.

**Comment by corentios** [comment]
Following this, any news ?

**Comment by andyliuzs** [comment]
您好我已经收到您的邮件了，待查看后马上回复！

**Comment by wlxo0401** [comment]
+1 

I'm curious about this, too.

**Comment by amcalgates** [comment]
Looks like the hard deadline for this is May 1st:

> While no action is required at this time, starting May 1, 2024, when you upload a new app or app update, you must include a NSPrivacyAccessedAPITypes array in your app’s privacy manifest to provide approved reasons for these APIs used by your app’s code. For more details about this policy, including a list of required reason APIs and approved reasons for usage, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api

**Comment by dikshit38** [comment]
You need to add an App Privacy file in your existing project and declare what data you are collecting in your app.

**Comment by amcalgates** [comment]
Returning to this, a privacy manifest is probably unnecessary. The results from

`grep -r -E 'NSURLVolumeAvailableCapacityKey|NSURLVolumeAvailableCapacityForImportantUsageKey|NSURLVolumeAvailableCapacityForOpportunisticUsageKey|NSURLVolumeTotalCapacityKey|NSFileSystemFreeSize|NSFileSystemSize|statfs|statvfs|fstatfs|fstatvfs|getattrlist|fgetattrlist|getattrlistat|activeInputModes|NSUserDefaults'`

Are just in the example app. And I can't imagine this library is tracking users.
