### ISSUE TITLE
Is there any plan to update TLS API  to Network.framework?

### ISSUE THREAD

**Issue by aBusyAnt** [robbiehanson/CocoaAsyncSocket#833]
Is there any plan to update to Network.framework?

[SecureTransport framework](https://developer.apple.com/documentation/security/secure_transport) (for TLS support) that is deprecated since macOS 10.15， in favour of [Network framework](https://developer.apple.com/documentation/network).

`
'SSLSetProtocolVersionMin' is deprecated: first deprecated in macOS 10.15 - No longer supported. Use Network.framework.`

**Comment by seanm** [comment]
If you can use Network.framework (don't need to support old OS), why do you still need CocoaAsyncSocket at all?
