### ISSUE TITLE
Crash: Thread 8: EXC_BAD_ACCESS (code=1, address=0x555555555555555d)

### ISSUE THREAD

**Issue by dikshit38** [robbiehanson/CocoaAsyncSocket#835]
Hello,

I am troubleshooting with crash issue. It's showing me **Thread 8: EXC_BAD_ACCESS (code=1, address=0x555555555555555d)**
Can anyone please help me out? 

Thanks in advance!

Please find the attached screenshot for more details

![Screenshot 2024-03-26 at 6 24 59 PM](https://github.com/robbiehanson/CocoaAsyncSocket/assets/102949288/1c91c925-51ef-4d7f-b4a8-800c230f19bb)

**Comment by seanm** [comment]
That's not enough info for anyone to help you.

The 55 may be a clue though, see `man malloc`.

**Comment by dikshit38** [comment]
@seanm, It seems the same as with #384 but there is no solution for that.

**Comment by seanm** [comment]
Yeah, and my comment is the same as 9 years ago.  Did you try address sanitizer or thread sanitizer?

**Comment by dikshit38** [comment]
Yes, I have tried address sanitiser and found the crash location as below:

![Screenshot 2024-03-26 at 2 16 00 PM](https://github.com/robbiehanson/CocoaAsyncSocket/assets/102949288/882d2b31-95bc-4043-bdf5-7ef7b1e1e727)

**Comment by seanm** [comment]
ASan should also output details about whether its an over-read or over-write, etc.

Also, that's swift, so presumably your code, not CocoaAsyncSocket.
