### ISSUE TITLE
Increase macOS deployment target

### ISSUE THREAD

**Issue by eliaSchenker** [robbiehanson/CocoaAsyncSocket#836]
The current deployment target for macOS (10.10) is no longer supported on newer version of Xcode (which causes build issues) and should be increased to 10.13.

This has been addressed in a past pull request (https://github.com/robbiehanson/CocoaAsyncSocket/pull/830), which has unfortunately been closed due to inactivity.

**Comment by onezens** [comment]
+1

pod lib lint xx.podspc Error
```
 - NOTE  | [OSX] xcodebuild:  clang: error: SDK does not contain 'libarclite' at the path '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/arc/libarclite_macosx.a'; try increasing the minimum deployment target
    - NOTE  | [OSX] xcodebuild:  Pods.xcodeproj: warning: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 10.8, but the range of supported deployment target versions is 10.13 to 14.2.99. (in target 'CocoaAsyncSocket' from project 'Pods')

[!] YCLog did not pass validation, due to 1 error and 17 warnings.
You can use the `--no-clean` option to inspect any issue.
```

**Comment by seanm** [comment]
Personally, I'm against increasing the minimum requirement. If you can use modern macOS, why do you even need CocoaAsyncSocket? Just use Network.framework.

CocoaAsyncSocket is great for older macOS, where we didn't have Network.framework.
