### ISSUE TITLE
How to search for a specific smart tv

### ISSUE THREAD

**Issue by Coger541** [robbiehanson/CocoaAsyncSocket#839]
Hello

Thanks for this library

Sorry I am noob in iOS swift development. I wanna know how to get IP address and friendly name of a specific smart tv like android, samsung, LG webOS, roku, fire tv etc

**Comment by andyliuzs** [comment]
您好我已经收到您的邮件了，待查看后马上回复！

**Comment by Coger541** [comment]
Hello @andyliuzs 

Do you have any experience in ARKit, I need a developer right now for now who have experience in ARKit
