### ISSUE TITLE
Read stream never completes

### ISSUE THREAD

**Issue by basvankuijck** [robbiehanson/CocoaAsyncSocket#89]
I am playing with GCDAsyncSocket (MRC / iOS5.1) for a while, especially with "large" files (5 - 10 mb). Unfortunately sometimes the read stream is never completed (e.g. it gets stuck) just a few bytes at the end of the stream; the `didReadPartialDataOfLength:` stops giving me information and the `didReadData` is not fired at all.

Here's some of my code (for both writing / reading examples the connection between the host and client have been established)
### WRITING

``` objective-c

#define kHeadTag 0
#define kDataTag 1

typedef struct {
    NSUInteger size;
} head_t;

-(void)sendData:(NSData *)__data  {
    _sendData = [__data retain];

    head_t header;
    header.size = __data.length;
    [_socket writeData:[NSData dataWithBytes:&header
                                   length:sizeof(header)]
       withTimeout:-1
       tag:kHeadTag];
}

-(void)socket:(GCDAsyncSocket *)sock
       didWriteDataWithTag:(long)tag {
    if (tag == kHeadTag) {
        [sock writeData:_sendData withTimeout:-1 tag:kDataTag];
        [_sendData release];
        _sendData = nil;
    }
}
```
### READING

``` objective-c
-(void)socket:(GCDAsyncSocket *)sock
       didReadData:(NSData *)data
       withTag:(long)tag {
    switch (tag) {            
            // ------------------------------------- HEAD
        case kHeadTag:{
            head_t head;
            [data getBytes:&head length:sizeof(head)];
            _readHead = head;
            NSLog(@"Received header (total size = %i bytes)", head.size);
            [sock readDataToLength:head.size
                withTimeout:-1
                tag:kDataTag];
        }
            break;

            // ------------------------------------- BODY
        case kDataTag: {
             NSLog(@"Data received with %i bytes", data.length);
        }
            break;
    }
};

-(void)socket:(GCDAsyncSocket *)sock
       didReadPartialDataOfLength:(NSUInteger)partialLength
       tag:(long)tag {
    if (tag == kDataTag) {
        NSLog(@"Data read with %i bytes", partialLength);
    }
};
```

I hope this is enough code to see what I'm doing wrong or maybe this is a bad practice for writing/reading large chunks of data.

**Comment by timlukens** [comment]
Chiming back in on this. Here we are 5 years later and it's still happening, though it only seems to happen to me when I'm using TLS. It seems to always be about 8 bytes away from completion regardless of how small I chunk the data reads.

**Comment by mikezriel** [comment]
Add the following code on line 5480 for GCDAsyncSocket.m file.

     // Check if over received expected size and truncate, othersize message will next be done
    if(!done && currentRead->readLength > currentRead->done) {
        currentRead->buffer = [currentRead->buffer subdataWithRange:NSMakeRange(0, currentRead->bytesDone)];
        done = YES;
    }
    
This made all the difference for me!
