### ISSUE TITLE
WebSocket Chrome Client

### ISSUE THREAD

**Issue by mlego** [robbiehanson/CocoaAsyncSocket#96]
I am having problems connecting with a Chrome client to my desktop server (via GCDAsyncSocket).  I am using a Echo test found here as my client: http://www.websocket.org/echo.html

My server output is as follows:

Accepted client ::1:55024
msg GET /?encoding=text HTTP/1.1
msg Upgrade: websocket
msg Connection: Upgrade
msg Host: localhost:5555
msg Origin: http://www.websocket.org
msg Sec-WebSocket-Key: Jvkpbf51/SW01P8f8euUOA==
msg Sec-WebSocket-Version: 13
msg Sec-WebSocket-Extensions: x-webkit-deflate-frame
msg  
Client Disconnected Error Domain=GCDAsyncSocketErrorDomain Code=7 "Socket closed by remote peer" UserInfo=0x10056cdc0 {NSLocalizedDescription=Socket closed by remote peer}: 

It seems to me that the server is having issues with Sec-WebSocket-Extensions, but I am not entirely sure. Any ideas on how to solve this?

**Comment by johnryan** [comment]
@dvor @mlego I'm running this test now and seeing the same issue..was this ever resolved? Thanks.
